/*
 * Ghost Protocol — Player System
 *
 * 3 playable classes with stats, shooting, movement state machine.
 * Uses physics.c for platformer movement + collision.
 */
#include "game/player.h"
#include "game/projectile.h"
#include "game/abilities.h"
#include "game/loot.h"
#include "game/hud.h"
#include "game/skills.h"
#include "game/colors.h"
#include "engine/input.h"
#include "engine/collision.h"
#include "engine/sprite.h"
#include "engine/audio.h"
#include "engine/video.h"
#include "game/particle.h"
#include "game/enemy.h"
#include "engine/entity.h"
#include "engine/rng.h"
#include <string.h>
#include <stddef.h>

PlayerState player_state;
GameStats game_stats;
static Entity* p_ent = NULL;
#define COYOTE_FRAMES 6

/* ---- Player sprite data (16x16, 4 tiles per frame) ---- */
/* 6 frames: idle0, idle1, run0, run1, jump, shoot */
/* Placeholder: simple humanoid silhouette */

/* Player sprites: 16x16 cyberpunk netrunner, 12 frames x 4 tiles = 48 tiles
 * Palette indices: 0=transparent, 1=armor deep shadow, 2=armor shadow,
 *   3=armor base, 4=armor highlight, 5=visor dim, 6=visor bright,
 *   7=visor core, 8=skin shadow, 9=skin base, A=skin highlight,
 *   B=circuit dark, C=circuit bright, D=AA edge dark, E=AA edge light,
 *   F=pure white highlight */
/* Samus-inspired cyberpunk netrunner facing RIGHT.
 * Dominant round helmet (rows 0-6), glowing full-face visor (rows 2-4),
 * chunky 4px arm cannon (cols 10-13 rows 7-8), thick paired legs.
 * Generated by tools/sprite_gen.py. */
/* Sprite tiles generated by tools/sprite_gen.py — correctly split 16x16→4 quadrant tiles */
static const u32 player_tiles[48][8] = {
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 0 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 0 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 0 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 0 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 1 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x00000012 }, /* Frame 1 TR */
    { 0x34443100, 0x33343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 1 BL */
    { 0x01BCCB12, 0x01BCCB12, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 1 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 2 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 2 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00013310, 0x00013311, 0x00013110, 0x00011100, 0x00000000 }, /* Frame 2 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00013310, 0x00013310, 0x00012310, 0x00011110, 0x00000000 }, /* Frame 2 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 3 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 3 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 3 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 3 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 4 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 4 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 4 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00013310, 0x00013310, 0x00003310, 0x00000110, 0x00000000 }, /* Frame 4 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 5 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 5 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00233100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 5 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00002331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 5 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 6 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 6 TR */
    { 0x34443100, 0x13331000, 0x12333100, 0x01233100, 0x00121100, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 6 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 6 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 7 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 7 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00133100, 0x00123100, 0x00111100 }, /* Frame 7 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001331, 0x00001231, 0x00001111 }, /* Frame 7 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 8 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01FCCB12 }, /* Frame 8 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 8 BL */
    { 0x01FCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 8 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 9 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01DCCB12 }, /* Frame 9 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 9 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 9 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 10 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x00000001 }, /* Frame 10 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x01233100, 0x01233310, 0x00123310, 0x00011110, 0x00000000 }, /* Frame 10 BL */
    { 0x00000001, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 10 BR */
    { 0x00000000, 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x44431000, 0x11111000, 0x34444431 }, /* Frame 11 TL */
    { 0x00000000, 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001344, 0x00001111, 0x01FCCB12 }, /* Frame 11 TR */
    { 0x34444310, 0x23310000, 0x12331000, 0x01233100, 0x00011110, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 11 BL */
    { 0x01BCCB12, 0x00000001, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 11 BR */
};

/* Per-class palettes — full 16-color material shading ramps
 * 0=transparent, 1-4=metal ramp (shadow→base→highlight→rim),
 * 5-7=glow ramp (dim→bright→core), 8-A=skin ramp,
 * B-C=circuit accent pair, D-E=AA edge colors, F=pure white */
static const u16 class_palettes[CLASS_COUNT][16] = {
    [CLASS_TROJAN] = {
        /* Heavy combat spec: blue-steel armor, blazing red visor, teal circuits */
        0x0000,                /* 0: transparent */
        RGB15_C(1,2,6),        /* 1: deep navy outline */
        RGB15_C(6,10,20),      /* 2: armor shadow — blue-steel */
        RGB15_C(12,16,26),     /* 3: armor base */
        RGB15_C(20,24,31),     /* 4: armor highlight — bright blue */
        RGB15_C(26,4,2),       /* 5: visor dim — blood red */
        RGB15_C(31,12,6),      /* 6: visor bright — fire red */
        RGB15_C(31,22,14),     /* 7: visor core — hot white-red */
        RGB15_C(14,10,8),      /* 8: skin shadow */
        RGB15_C(22,18,14),     /* 9: skin base */
        RGB15_C(28,24,20),     /* A: skin highlight */
        RGB15_C(2,12,18),      /* B: circuit dark — deep teal */
        RGB15_C(6,24,31),      /* C: circuit bright — electric cyan */
        RGB15_C(3,5,12),       /* D: AA edge dark */
        RGB15_C(14,18,28),     /* E: AA edge light */
        RGB15_C(31,31,31),     /* F: pure white */
    },
    [CLASS_INFILTRATOR] = {
        /* Stealth spec: near-black suit, neon green visor, dark green circuits */
        0x0000,                /* 0: transparent */
        RGB15_C(1,1,2),        /* 1: near-black outline */
        RGB15_C(3,4,6),        /* 2: suit shadow — very dark grey */
        RGB15_C(6,7,9),        /* 3: suit base — dark charcoal */
        RGB15_C(10,12,14),     /* 4: suit highlight — medium grey */
        RGB15_C(2,22,8),       /* 5: visor dim — dark neon green */
        RGB15_C(8,31,14),      /* 6: visor bright — neon green */
        RGB15_C(18,31,22),     /* 7: visor core — white-green glow */
        RGB15_C(12,8,6),       /* 8: skin shadow */
        RGB15_C(20,16,12),     /* 9: skin base */
        RGB15_C(26,22,18),     /* A: skin highlight */
        RGB15_C(1,8,4),        /* B: circuit dark — forest green */
        RGB15_C(4,22,12),      /* C: circuit bright — emerald */
        RGB15_C(2,2,4),        /* D: AA edge dark */
        RGB15_C(6,8,10),       /* E: AA edge light */
        RGB15_C(24,31,26),     /* F: green-tinted white */
    },
    [CLASS_TECHNOMANCER] = {
        /* Tech spec: dark coat with purple tones, amber visor, gold circuits */
        0x0000,                /* 0: transparent */
        RGB15_C(4,2,4),        /* 1: deep purple-brown outline */
        RGB15_C(10,6,10),      /* 2: coat shadow — dark plum */
        RGB15_C(16,12,16),     /* 3: coat base — grey-purple */
        RGB15_C(24,20,24),     /* 4: coat highlight — light mauve */
        RGB15_C(24,16,2),      /* 5: visor dim — dark amber */
        RGB15_C(31,24,6),      /* 6: visor bright — vivid amber */
        RGB15_C(31,30,16),     /* 7: visor core — white-amber glow */
        RGB15_C(14,10,8),      /* 8: skin shadow */
        RGB15_C(22,18,14),     /* 9: skin base */
        RGB15_C(28,24,20),     /* A: skin highlight */
        RGB15_C(14,10,2),      /* B: circuit dark — deep gold */
        RGB15_C(28,22,6),      /* C: circuit bright — bright gold */
        RGB15_C(6,4,6),        /* D: AA edge dark */
        RGB15_C(14,10,14),     /* E: AA edge light */
        RGB15_C(31,28,22),     /* F: warm white-gold */
    },
};

#define PLAYER_TILE_BASE 0
#define PLAYER_PAL_BANK  0
#define PLAYER_W  16
#define PLAYER_H  16
#define PLAYER_HITBOX_W 12
#define PLAYER_HITBOX_H 14

/* ---- Classless base stats (level 0) ---- */
#define CLASSLESS_HP   20
#define CLASSLESS_ATK   5
#define CLASSLESS_DEF   5
#define CLASSLESS_SPD   5
#define CLASSLESS_LCK   5
#define CLASSLESS_GAIN  1

/* Per-class auto-allocation (L5+): 5 pts/level, spread 2+2+1 */
static const s16 class_alloc[CLASS_COUNT][5] = {
    [CLASS_TROJAN]       = { 3, 2, 2, 1, 0 },
    [CLASS_INFILTRATOR]  = { 2, 1, 0, 2, 2 },
    [CLASS_TECHNOMANCER] = { 2, 2, 1, 0, 2 },
};

/* ---- Implementation ---- */

void player_get_base_stats(int cls, int lvl, s16* hp, s16* atk, s16* def, s16* spd, s16* lck) {
    *hp  = CLASSLESS_HP;
    *atk = CLASSLESS_ATK;
    *def = CLASSLESS_DEF;
    *spd = CLASSLESS_SPD;
    *lck = CLASSLESS_LCK;

    int classless_levels = (lvl < TIER_1_LEVEL) ? lvl : (TIER_1_LEVEL - 1);
    *hp  += (s16)(classless_levels * 2);
    *atk += (s16)(classless_levels * CLASSLESS_GAIN);
    *def += (s16)(classless_levels * CLASSLESS_GAIN);
    *spd += (s16)(classless_levels * CLASSLESS_GAIN);
    *lck += (s16)(classless_levels * CLASSLESS_GAIN);

    if (lvl >= TIER_1_LEVEL && cls >= 0 && cls < CLASS_COUNT) {
        int class_levels = lvl - TIER_1_LEVEL + 1;
        *hp  += (s16)(class_levels * class_alloc[cls][0]);
        *atk += (s16)(class_levels * class_alloc[cls][1]);
        *def += (s16)(class_levels * class_alloc[cls][2]);
        *spd += (s16)(class_levels * class_alloc[cls][3]);
        *lck += (s16)(class_levels * class_alloc[cls][4]);
    }
}

static void apply_equipment_bonuses(s16* hp, s16* atk, s16* def, s16* spd, s16* lck) {
    /* Reset armor passive flags (preserve regen timer if regen stays active) */
    u8 had_regen = player_state.armor_flags & AFLAG_HP_REGEN;
    player_state.armor_flags = 0;

    /* Armor DEF bonus + passive effects based on subtype */
    LootItem* armor = inventory_get_equipped_armor();
    if (armor) {
        int asub = LOOT_SUBTYPE(armor->type);
        int aval = armor->stat1;
        switch (asub) {
        case ARMOR_DATA_VEST:
            *def = (s16)(*def + aval);
            break;
        case ARMOR_FIREWALL:
            *def = (s16)(*def + aval);
            player_state.armor_flags |= AFLAG_HAZARD_RESIST;
            break;
        case ARMOR_NEURAL_PLATE:
            *def = (s16)(*def + aval * 3 / 2);
            break;
        case ARMOR_STEALTH_SUIT:
            *def = (s16)(*def + aval);
            *spd = (s16)(*spd + aval / 3);
            break;
        case ARMOR_CIRCUIT_WEAVE:
            *def = (s16)(*def + aval);
            player_state.armor_flags |= AFLAG_HP_REGEN;
            break;
        case ARMOR_PLATING:
            *def = (s16)(*def + aval * 2);
            break;
        case ARMOR_NANO_MESH:
            *def = (s16)(*def + aval);
            player_state.armor_flags |= AFLAG_DAMAGE_RESIST;
            break;
        case ARMOR_PHASE_SHELL:
            *def = (s16)(*def + aval);
            player_state.armor_flags |= AFLAG_DODGE_CHANCE;
            break;
        case ARMOR_QUANTUM_GUARD:
            *def = (s16)(*def + aval);
            player_state.armor_flags |= AFLAG_REFLECT;
            break;
        case ARMOR_TITAN_FRAME:
            *def = (s16)(*def + aval * 5 / 2);
            player_state.armor_flags |= AFLAG_KB_RESIST;
            break;
        default:
            *def = (s16)(*def + aval);
            break;
        }
    }

    /* Accessory bonuses */
    LootItem* acc = inventory_get_equipped_accessory();
    if (acc) {
        int sub = LOOT_SUBTYPE(acc->type);
        int val = acc->stat1;
        switch (sub) {
        case ACC_SPRINT_MODULE: *spd = (s16)(*spd + val); break;
        case ACC_LUCKY_CHIP:    *lck = (s16)(*lck + val); break;
        case ACC_SHIELD_CELL:   *hp  = (s16)(*hp + val * 3); break;
        case ACC_POWER_CELL:    *atk = (s16)(*atk + val); break;
        case ACC_REGEN_CORE:    player_state.armor_flags |= AFLAG_HP_REGEN; break;
        default: break; /* Crit/XP/Credit/Ammo/Phase read at use site */
        }
    }

    /* Reset regen timer only when regen flag was lost */
    if (had_regen && !(player_state.armor_flags & AFLAG_HP_REGEN))
        player_state.armor_regen_timer = 0;
}

static void compute_stats(void) {
    int cls = player_state.player_class;
    int lvl = player_state.level;
    player_get_base_stats(cls, lvl,
                          &player_state.max_hp, &player_state.atk,
                          &player_state.def, &player_state.spd,
                          &player_state.lck);
    apply_equipment_bonuses(&player_state.max_hp, &player_state.atk,
                            &player_state.def, &player_state.spd,
                            &player_state.lck);
    if (player_state.hp > player_state.max_hp)
        player_state.hp = player_state.max_hp;
}

void player_recompute_stats(void) {
    compute_stats();
}

/* player_init: Full initialization for a NEW character.
 * Zeroes the entire PlayerState (both persistent and level-scope fields).
 * INTEGRATION NOTE: Only call this for character creation. For level re-entry,
 * call player_init_level() instead to preserve persistent fields. */
void player_init(int player_class) {
    entity_init();
    p_ent = entity_spawn(ENT_PLAYER);
    if (!p_ent) return;

    memset(&player_state, 0, sizeof(player_state));
    player_state.player_class = (u8)player_class;
    player_state.tier_choices[0] = 0xFF;
    player_state.tier_choices[1] = 0xFF;
    player_state.tier_choices[2] = 0xFF;
    player_state.slotted_skill = 0xFF;
    player_state.level = 0;
    player_state.state = PSTATE_IDLE;
    player_state.credits = 0;

    compute_stats();
    player_state.hp = player_state.max_hp;
    ability_reset();

    p_ent->x = FP8(64);
    p_ent->y = FP8(128);
    p_ent->width = PLAYER_HITBOX_W;
    p_ent->height = PLAYER_HITBOX_H;
    p_ent->facing = FACING_RIGHT;
    player_state.last_safe_x = p_ent->x;
    player_state.last_safe_y = p_ent->y;

    /* Physics: classless uses CLASS_TROJAN params as default */
    int phys_cls = (player_class >= 0 && player_class < CLASS_COUNT) ? player_class : CLASS_TROJAN;
    player_state.jumps_remaining = physics_class[phys_cls].max_jumps;

    /* Allocate OAM sprite (16x16) */
    int oam = sprite_alloc();
    if (oam >= 0) {
        p_ent->oam_index = (u8)oam;
        OBJ_ATTR* spr = sprite_get(oam);
        if (spr) {
            spr->attr0 = ATTR0_SQUARE | ATTR0_4BPP;
            spr->attr1 = ATTR1_SIZE_16;
            spr->attr2 = (u16)(ATTR2_ID(PLAYER_TILE_BASE) | ATTR2_PALBANK(PLAYER_PAL_BANK));
        }
    }

    /* Load graphics */
    memcpy16(&tile_mem_obj[0][PLAYER_TILE_BASE], player_tiles, sizeof(player_tiles) / 2);
    int pal_cls = (player_class >= 0 && player_class < CLASS_COUNT) ? player_class : CLASS_TROJAN;
    memcpy16(&pal_obj_mem[PLAYER_PAL_BANK * 16], class_palettes[pal_cls], 16);
    colors_apply_player_palette(player_state.suit_color, player_state.visor_color);

    /* Init projectile pool */
    projectile_init();
}

/* player_init_level: Zero only level-scope fields for level re-entry.
 * Preserves all persistent fields (class, level, XP, stats, inventory, etc.). */
void player_init_level(void) {
    size_t offset = offsetof(PlayerState, _level_scope_start);
    memset((u8*)&player_state + offset, 0, sizeof(PlayerState) - offset);
    player_state.hp = player_state.max_hp;
    int phys_cls = (player_state.player_class < CLASS_COUNT) ? player_state.player_class : CLASS_TROJAN;
    player_state.jumps_remaining = physics_class[phys_cls].max_jumps;
    ability_reset();
}

/* player_enter_level: Full level entry — creates entity, allocates sprite,
 * loads graphics, and resets level-scope fields. Call from state_net_enter().
 * Preserves all persistent fields (unlike player_init which is for new characters). */
void player_enter_level(void) {
    /* Reset level-scope fields first */
    player_init_level();

    /* Create player entity in the entity pool */
    p_ent = entity_spawn(ENT_PLAYER);
    if (!p_ent) return;

    /* Setup entity hitbox */
    p_ent->width = PLAYER_HITBOX_W;
    p_ent->height = PLAYER_HITBOX_H;
    p_ent->facing = FACING_RIGHT;

    /* Allocate OAM sprite (16x16) */
    int oam = sprite_alloc();
    if (oam >= 0) {
        p_ent->oam_index = (u8)oam;
        OBJ_ATTR* spr = sprite_get(oam);
        if (spr) {
            spr->attr0 = ATTR0_SQUARE | ATTR0_4BPP;
            spr->attr1 = ATTR1_SIZE_16;
            spr->attr2 = (u16)(ATTR2_ID(PLAYER_TILE_BASE) | ATTR2_PALBANK(PLAYER_PAL_BANK));
        }
    }

    /* Load player graphics into VRAM */
    memcpy16(&tile_mem_obj[0][PLAYER_TILE_BASE], player_tiles, sizeof(player_tiles) / 2);

    /* Load base palette then apply customization colors */
    int pal_cls = (player_state.player_class < CLASS_COUNT) ? player_state.player_class : CLASS_TROJAN;
    memcpy16(&pal_obj_mem[PLAYER_PAL_BANK * 16],
             class_palettes[pal_cls], 16);
    colors_apply_player_palette(player_state.suit_color, player_state.visor_color);
}

Entity* player_get(void) {
    return p_ent;
}

int player_is_alive(void) {
    return player_state.hp > 0;
}

/* ---- Shooting ---- */

static void do_shoot(void) {
    if (!p_ent) return;
    int cls = player_state.player_class;
    s16 dir_x;
    s32 spawn_x, spawn_y;

    spawn_y = p_ent->y + FP8(4);
    if (p_ent->facing == FACING_LEFT) {
        dir_x = -512;
        spawn_x = p_ent->x - FP8(4);
    } else {
        dir_x = 512;
        spawn_x = p_ent->x + FP8(12);
    }

    /* Get equipped weapon stats (if any) */
    LootItem* weapon = inventory_get_equipped();
    int dmg = player_state.atk;
    int base_cooldown;

    if (weapon) {
        /* Weapon adds to damage and modifies fire rate */
        dmg += weapon->stat1;
        base_cooldown = weapon->stat2; /* Lower = faster */
        /* Ammo Belt accessory: reduce fire cooldown */
        {
            LootItem* ammo_acc = inventory_get_equipped_accessory();
            if (ammo_acc && LOOT_SUBTYPE(ammo_acc->type) == ACC_AMMO_BELT) {
                base_cooldown -= ammo_acc->stat1 / 2;
                if (base_cooldown < 1) base_cooldown = 1;
            }
        }
    } else {
        base_cooldown = 0; /* No weapon = use class default */
    }

    /* Berserk (Assault ability): ATK x1.5 while active */
    if (ability_is_berserk_active()) dmg = dmg * 3 / 2;

    /* Weapon type modifies projectile behavior */
    int wtype = weapon ? LOOT_SUBTYPE(weapon->type) : WEAPON_BUSTER;

    /* Per-weapon projectile color — write 4 key palette entries to bank 14 */
    {
        u16 c1, c2, c3, c4; /* bright, mid, dark, glow */
        switch (wtype) {
        case WEAPON_RAPID:
            c1 = RGB15_C(4,31,12);  c2 = RGB15_C(2,22,8);
            c3 = RGB15_C(0,14,4);   c4 = RGB15_C(12,31,20);
            break;
        case WEAPON_SPREAD:
            c1 = RGB15_C(31,24,4);  c2 = RGB15_C(24,16,2);
            c3 = RGB15_C(16,10,0);  c4 = RGB15_C(31,28,12);
            break;
        case WEAPON_CHARGER:
            c1 = RGB15_C(31,31,20); c2 = RGB15_C(24,24,14);
            c3 = RGB15_C(16,16,8);  c4 = RGB15_C(31,31,28);
            break;
        case WEAPON_BEAM:
            c1 = RGB15_C(28,8,31);  c2 = RGB15_C(20,4,24);
            c3 = RGB15_C(12,2,16);  c4 = RGB15_C(31,16,31);
            break;
        case WEAPON_LASER:
            c1 = RGB15_C(31,4,4);   c2 = RGB15_C(24,2,2);
            c3 = RGB15_C(16,0,0);   c4 = RGB15_C(31,12,8);
            break;
        case WEAPON_HOMING:
            c1 = RGB15_C(20,31,8);  c2 = RGB15_C(14,24,4);
            c3 = RGB15_C(8,16,2);   c4 = RGB15_C(24,31,16);
            break;
        case WEAPON_NOVA:
            c1 = RGB15_C(31,20,31); c2 = RGB15_C(24,14,24);
            c3 = RGB15_C(16,8,16);  c4 = RGB15_C(31,28,31);
            break;
        default: /* WEAPON_BUSTER — cyan (default) */
            c1 = RGB15_C(0,28,31);  c2 = RGB15_C(0,20,24);
            c3 = RGB15_C(0,12,16);  c4 = RGB15_C(8,31,31);
            break;
        }
        pal_obj_mem[14*16 + 1] = c1;
        pal_obj_mem[14*16 + 2] = c2;
        pal_obj_mem[14*16 + 3] = c3;
        pal_obj_mem[14*16 + 4] = c4;
    }

    switch (cls) {
    default: /* Classless (0xFF) defaults to Trojan behavior */
    case CLASS_TROJAN:
    {
        int cd = weapon ? base_cooldown : 12;
        if (wtype == WEAPON_SPREAD && weapon) {
            /* 3 projectiles in a spread, 2/3 damage each */
            s16 sdmg = (s16)(dmg * 2 / 3);
            projectile_spawn(spawn_x, spawn_y, dir_x, 0, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, -96, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, 96, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            cd += 4; /* Spread fires slower */
        } else if (wtype == WEAPON_BEAM && weapon) {
            /* Piercing beam, slightly slower */
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BEAM, PROJ_PIERCE, 0);
            cd += 6;
        } else if (wtype == WEAPON_CHARGER && weapon) {
            /* Slow but 2x damage */
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 2 / 3), 0,
                             (s16)(dmg * 2), SUBTYPE_PROJ_CHARGE, 0, 0);
            cd += 8;
        } else if (wtype == WEAPON_LASER && weapon) {
            /* Continuous stream, faster fire rate, pierces enemies */
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)(dmg * 2 / 3), SUBTYPE_PROJ_LASER, PROJ_PIERCE, 0);
            cd = GP_MAX(cd - 4, 2);
        } else if (wtype == WEAPON_HOMING && weapon) {
            /* Slow tracking projectile */
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 2 / 3), 0,
                             (s16)(dmg * 3 / 2), SUBTYPE_PROJ_HOMING, 0, 0);
            cd += 10;
        } else if (wtype == WEAPON_NOVA && weapon) {
            /* Short-range AoE burst (3 directions) — pierces + phases through walls */
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)(dmg * 2), SUBTYPE_PROJ_NOVA, PROJ_PIERCE | PROJ_PHASE, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, -192,
                             (s16)(dmg * 2), SUBTYPE_PROJ_NOVA, PROJ_PIERCE | PROJ_PHASE, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, 192,
                             (s16)(dmg * 2), SUBTYPE_PROJ_NOVA, PROJ_PIERCE | PROJ_PHASE, 0);
            cd += 15;
        } else {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BUSTER, 0, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        break;
    }
    case CLASS_INFILTRATOR:
    {
        int cd = weapon ? GP_MAX(base_cooldown - 3, 4) : 6;
        /* TODO: pierce chance driven by skill ranks — added in Task 11 */
        u8 pierce_flags = 0;
        if (wtype == WEAPON_RAPID && weapon) {
            /* Extra fast with bonus speed */
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 3 / 2), 0,
                             (s16)(dmg * 2 / 3), SUBTYPE_PROJ_RAPID, pierce_flags, 0);
            cd = GP_MAX(cd - 2, 3);
        } else if (wtype == WEAPON_SPREAD && weapon) {
            s16 sdmg = (s16)(dmg / 2);
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), -64, sdmg, SUBTYPE_PROJ_RAPID, pierce_flags, 0);
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), 64, sdmg, SUBTYPE_PROJ_RAPID, pierce_flags, 0);
            cd += 2;
        } else {
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), 0,
                             (s16)(dmg * 2 / 3), SUBTYPE_PROJ_RAPID, pierce_flags, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        break;
    }
    case CLASS_TECHNOMANCER:
    {
        int cd = weapon ? base_cooldown : 10;
        if (wtype == WEAPON_BEAM && weapon) {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BEAM, PROJ_PIERCE, 0);
            cd += 4;
        } else if (wtype == WEAPON_CHARGER && weapon) {
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 2 / 3), 0,
                             (s16)(dmg * 2), SUBTYPE_PROJ_CHARGE, 0, 0);
            cd += 6;
        } else {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BUSTER, 0, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        break;
    }
    }

    /* Weapon-type-specific SFX */
    switch (wtype) {
    case WEAPON_BEAM:    audio_play_sfx(SFX_BEAM_FIRE); break;
    case WEAPON_SPREAD:  audio_play_sfx(SFX_SPREAD_BURST); break;
    case WEAPON_CHARGER: audio_play_sfx(SFX_CHARGER_WHINE); break;
    case WEAPON_LASER:   audio_play_sfx(SFX_LASER_CRACK); break;
    case WEAPON_RAPID:   audio_play_sfx(SFX_SHOOT_RAPID); break;
    case WEAPON_HOMING:  audio_play_sfx(SFX_HOMING_WHINE); break;
    case WEAPON_NOVA:    audio_play_sfx(SFX_NOVA_WHOOSH); break;
    default:             audio_play_sfx(SFX_SHOOT); break;
    }

    /* Muzzle flash particles — scale with weapon type */
    {
        int flash_count = 1; /* default: 1 SPARK */
        int flash_speed = 128;
        if (wtype == WEAPON_NOVA) { flash_count = 3; flash_speed = 192; }
        else if (wtype == WEAPON_CHARGER) { flash_count = 2; flash_speed = 160; }
        else if (wtype == WEAPON_SPREAD) { flash_count = 2; flash_speed = 144; }
        else if (wtype == WEAPON_BEAM || wtype == WEAPON_LASER) { flash_count = 1; flash_speed = 96; }
        particle_burst(spawn_x, spawn_y, flash_count, PART_SPARK, flash_speed, 8);
    }

    /* No screen flash on regular weapon fire — too noisy */

    /* Recoil — nudge player opposite to shot direction, with collision check */
    {
        s32 old_x = p_ent->x;
        if (p_ent->facing == FACING_LEFT)
            p_ent->x += FP8(1);
        else
            p_ent->x -= FP8(1);
        /* Undo recoil if it pushed us into a solid tile */
        int check_x = (int)(p_ent->x >> 8) + (p_ent->facing == FACING_LEFT ? (int)p_ent->width : 0);
        int check_y_top = (int)(p_ent->y >> 8) + 2;
        int check_y_bot = (int)(p_ent->y >> 8) + (int)p_ent->height - 2;
        if (collision_point_solid(check_x, check_y_top) ||
            collision_point_solid(check_x, check_y_bot)) {
            p_ent->x = old_x;
        }
    }

    /* Overclock: halve cooldown when active (Assault ability) */
    if (ability_is_overclock_active()) {
        player_state.shoot_cooldown = (u8)(player_state.shoot_cooldown / 2);
        if (player_state.shoot_cooldown < 1) player_state.shoot_cooldown = 1;
    }
}

/* ---- Movement + state machine ---- */

void player_update(void) {
    if (!p_ent || player_state.state == PSTATE_DEAD) return;

    int cls = player_state.player_class;
    int phys_cls = (cls < CLASS_COUNT) ? cls : CLASS_TROJAN;
    const PhysicsParams* phys = &physics_class[phys_cls];

    int effective_speed = phys->move_speed;

    /* Tick timers */
    if (player_state.shoot_cooldown > 0) player_state.shoot_cooldown--;
    if (player_state.invincible_timer > 0) player_state.invincible_timer--;
    if (player_state.dash_timer > 0) player_state.dash_timer--;
    if (player_state.dash_cooldown > 0) player_state.dash_cooldown--;
    if (player_state.charge_rush_cooldown > 0) player_state.charge_rush_cooldown--;
    if (player_state.tether_cooldown > 0) player_state.tether_cooldown--;

    /* Hit stun */
    if (player_state.state == PSTATE_HIT) {
        /* Knockback deceleration — bleed off velocity during stun */
        if (p_ent->vx > 0) { p_ent->vx -= 16; if (p_ent->vx < 0) p_ent->vx = 0; }
        else if (p_ent->vx < 0) { p_ent->vx += 16; if (p_ent->vx > 0) p_ent->vx = 0; }
        physics_update(p_ent, phys);
        if (player_state.invincible_timer < 50) {
            player_state.state = PSTATE_IDLE;
        }
        return;
    }

    /* Dash state (Infiltrator) */
    if (player_state.state == PSTATE_DASH) {
        if (player_state.dash_timer == 0) {
            player_state.state = p_ent->on_ground ? PSTATE_IDLE : PSTATE_FALL;
            player_state.dash_cooldown = phys->dash_cooldown;
        } else if ((player_state.dash_timer & 1) == 0) {
            /* Dash trail: spawn spark behind player every 2 frames */
            s32 trail_x = p_ent->x + (p_ent->facing ? FP8(12) : -FP8(4));
            s16 trail_vx = p_ent->facing ? 80 : -80;
            particle_spawn(trail_x, p_ent->y + FP8(4), trail_vx, -32, PART_SPARK, 10);
        }
        physics_update(p_ent, phys);
        return;
    }

    /* Charge Rush state (Assault) */
    if (player_state.state == PSTATE_CHARGE) {
        if (player_state.charge_rush_timer > 0) {
            player_state.charge_rush_timer--;
            /* Maintain charge velocity, skip gravity */
            p_ent->vx = player_state.charge_vx;
            p_ent->vy = player_state.charge_vy;
            /* Trail particles every 2 frames */
            if ((player_state.charge_rush_timer & 1) == 0) {
                s32 trail_x = p_ent->x + (p_ent->facing ? FP8(12) : -FP8(4));
                particle_spawn(trail_x, p_ent->y + FP8(4),
                               p_ent->facing ? (s16)80 : (s16)-80, -32, PART_SPARK, 10);
            }
            physics_update(p_ent, phys);
            /* Wall contact during horizontal/upward charge: enter wall slide */
            if (p_ent->on_wall && player_state.charge_vy <= 0) {
                player_state.charge_rush_timer = 0;
                player_state.state = PSTATE_WALL_SLIDE;
                p_ent->vx = 0;
                return;
            }
            /* Ground contact during downward slam */
            if (p_ent->on_ground && player_state.charge_vy > 0) {
                player_state.charge_rush_timer = 0;
                player_state.state = PSTATE_IDLE;
                video_shake(3, 1);
                particle_burst(p_ent->x + FP8(6), p_ent->y + FP8(12), 4, PART_BURST, 160, 12);
                return;
            }
            /* INTEGRATION NOTE: enemy.c should check player_state.state == PSTATE_CHARGE
             * and call player_charge_rush_damage() for contact damage. */
            return;
        } else {
            /* Charge expired: return to normal movement */
            player_state.state = p_ent->on_ground ? PSTATE_IDLE : PSTATE_FALL;
        }
    }

    /* Tether pull state (Technomancer) */
    if (player_state.state == PSTATE_TETHER) {
        if (player_state.tether_timer > 0) {
            player_state.tether_timer--;
            /* Move toward target at fixed speed */
            s32 dx = player_state.tether_target_x - p_ent->x;
            s32 dy = player_state.tether_target_y - p_ent->y;
            /* Check arrival (distance < 512 in 8.8 FP = ~2 pixels) */
            s32 dist_sq = (dx >> 4) * (dx >> 4) + (dy >> 4) * (dy >> 4);
            if (dist_sq < (512 >> 4) * (512 >> 4) || player_state.tether_timer == 0) {
                /* Snap to target, but verify target isn't inside solid geometry */
                s32 snap_x = player_state.tether_target_x;
                s32 snap_y = player_state.tether_target_y;
                int sx = (int)(snap_x >> 8);
                int sy = (int)(snap_y >> 8);
                if (collision_point_solid(sx + 1, sy + 2) ||
                    collision_point_solid(sx + (int)p_ent->width - 1, sy + (int)p_ent->height - 1)) {
                    /* Target is inside solid — stay at current position */
                    snap_x = p_ent->x;
                    snap_y = p_ent->y;
                }
                p_ent->x = snap_x;
                p_ent->y = snap_y;
                p_ent->vx = 0;
                p_ent->vy = 0;
                /* If target was horizontal (scan_dy was 0), check for wall hold */
                /* Determine if we hit a wall by checking wall adjacency */
                if (p_ent->on_wall || physics_check_wall(p_ent, p_ent->facing ? -1 : 1)) {
                    /* Enter tether hold: stick to wall */
                    player_state.state = PSTATE_TETHER_HOLD;
                    player_state.tether_hold = 1;
                    player_state.tether_hold_timer = 90;
                    p_ent->on_wall = 1;
                } else {
                    player_state.state = p_ent->on_ground ? PSTATE_IDLE : PSTATE_FALL;
                    player_state.tether_cooldown = 30;
                }
                player_state.tether_timer = 0;
            } else {
                /* Normalize direction and move at speed 512/frame */
                /* Approximate: use dominant axis for speed distribution */
                s32 adx = dx < 0 ? -dx : dx;
                s32 ady = dy < 0 ? -dy : dy;
                s32 total = adx + ady;
                if (total > 0) {
                    p_ent->vx = (s16)(dx * 512 / total);
                    p_ent->vy = (s16)(dy * 512 / total);
                }
            }
            /* Apply velocity with collision checking (no gravity during tether) */
            {
                s32 old_x = p_ent->x;
                s32 old_y = p_ent->y;
                p_ent->x += p_ent->vx;
                p_ent->y += p_ent->vy;
                /* Collision check — if we entered a solid tile, revert that axis */
                int cx = (int)(p_ent->x >> 8);
                int cy = (int)(p_ent->y >> 8);
                int w = (int)p_ent->width;
                int h = (int)p_ent->height;
                if (collision_point_solid(cx + 1, cy + 2) || collision_point_solid(cx + w - 1, cy + 2) ||
                    collision_point_solid(cx + 1, cy + h - 1) || collision_point_solid(cx + w - 1, cy + h - 1)) {
                    /* Hit solid — snap to pre-collision position and end tether */
                    p_ent->x = old_x;
                    p_ent->y = old_y;
                    p_ent->vx = 0;
                    p_ent->vy = 0;
                    player_state.tether_timer = 0;
                    player_state.state = p_ent->on_ground ? PSTATE_IDLE : PSTATE_FALL;
                }
                /* World bounds clamping (all edges) */
                if (p_ent->x < 0) { p_ent->x = 0; p_ent->vx = 0; }
                if (p_ent->y < 0) { p_ent->y = 0; p_ent->vy = 0; }
                s32 max_x = (s32)(NET_MAP_PX - w) << 8;
                s32 max_y = (s32)(NET_MAP_PY - h) << 8;
                if (p_ent->x > max_x) { p_ent->x = max_x; p_ent->vx = 0; }
                if (p_ent->y > max_y) { p_ent->y = max_y; p_ent->vy = 0; }
            }
            return;
        }
    }

    /* Tether hold state (Technomancer wall grip) */
    if (player_state.state == PSTATE_TETHER_HOLD) {
        if (player_state.tether_hold_timer > 0) {
            player_state.tether_hold_timer--;
            p_ent->vx = 0;
            p_ent->vy = 0;
            p_ent->on_wall = 1;
            /* A pressed during tether hold: wall jump + reset tether cooldown (chain tether) */
            if (input_hit(KEY_A)) {
                p_ent->vy = phys->wall_jump_vy;
                int wall_side = physics_check_wall(p_ent, -1) ? -1 : 1;
                p_ent->vx = (wall_side < 0) ? phys->wall_jump_vx : -phys->wall_jump_vx;
                p_ent->facing = (wall_side < 0) ? FACING_RIGHT : FACING_LEFT;
                player_state.tether_cooldown = 0; /* Allow chain tether */
                player_state.state = PSTATE_JUMP;
                player_state.tether_hold = 0;
                audio_play_sfx(SFX_WALL_JUMP);
            }
        } else {
            /* Timer expired: release to normal wall slide */
            player_state.state = PSTATE_WALL_SLIDE;
            player_state.tether_hold = 0;
            player_state.tether_cooldown = 30;
        }
        return;
    }

    /* Update animation state (before input for immediate draw response).
     * Preserve PSTATE_SHOOT for 6 frames so mid-air shooting is visible. */
    p_ent->anim_timer++;
    int keep_shoot = (player_state.state == PSTATE_SHOOT && player_state.shoot_cooldown > 0);
    if (p_ent->on_ground) {
        if (!keep_shoot) {
            if (p_ent->vx != 0) {
                player_state.state = PSTATE_RUN;
            } else {
                player_state.state = PSTATE_IDLE;
            }
        }
        /* Landing impact: spawn dust scaled to airborne time */
        if (player_state.coyote_timer > 4) {
            int intensity = (player_state.coyote_timer > 20) ? 3 : ((player_state.coyote_timer > 10) ? 2 : 1);
            s32 feet_y = p_ent->y + FP8(12);
            particle_spawn(p_ent->x + FP8(2), feet_y, -80, -40, PART_BURST, 10);
            particle_spawn(p_ent->x + FP8(10), feet_y, 80, -40, PART_BURST, 10);
            if (intensity >= 2) {
                /* Heavier landing: extra dust spread */
                particle_spawn(p_ent->x + FP8(6), feet_y, -40, -60, PART_BURST, 12);
                particle_spawn(p_ent->x + FP8(6), feet_y, 40, -60, PART_BURST, 12);
            }
            if (intensity >= 3) {
                /* Heavy slam: screen shake + more particles + SFX */
                particle_burst(p_ent->x + FP8(6), feet_y, 3, PART_SPARK, 120, 8);
                video_shake(3, 1);
                audio_play_sfx(SFX_LAND_HEAVY);
            }
        }
        player_state.jumps_remaining = phys->max_jumps;
        player_state.coyote_timer = 0;
        /* Track last safe ground position (solid tile, not platform) */
        {
            int foot_x = (int)(p_ent->x >> 8) + p_ent->width / 2;
            int foot_y = (int)(p_ent->y >> 8) + p_ent->height;
            int tile = collision_tile_at(foot_x, foot_y);
            if (tile == TILE_SOLID || tile == TILE_BREAKABLE || tile == TILE_PLATFORM) {
                player_state.last_safe_x = p_ent->x;
                player_state.last_safe_y = p_ent->y;
            }
        }
    } else {
        /* Coyote time */
        if (player_state.coyote_timer < 255) player_state.coyote_timer++;
    }

    /* Jump buffer: decrement each frame */
    if (player_state.jump_buffer > 0) player_state.jump_buffer--;
    if (!p_ent->on_ground && !keep_shoot) {
        if (p_ent->on_wall) {
            if (player_state.state != PSTATE_WALL_SLIDE)
                audio_play_sfx(SFX_WALL_SLIDE); /* Contact SFX on entry */
            player_state.state = PSTATE_WALL_SLIDE;
            /* Wall slide dust: spawn particle at feet every 8 frames */
            if ((p_ent->anim_timer & 7) == 0) {
                s32 dust_x = p_ent->x + (p_ent->facing ? -FP8(2) : FP8(14));
                particle_spawn(dust_x, p_ent->y + FP8(12),
                               p_ent->facing ? -60 : 60, -40, PART_BURST, 12);
            }
        } else if (p_ent->vy < 0) {
            player_state.state = PSTATE_JUMP;
        } else {
            player_state.state = PSTATE_FALL;
        }
    }

    /* ---- Input ---- */

    /* ==== SELECT: open/close skill wheel ==== */
    if (input_hit(KEY_SELECT) && player_has_class()) {
        player_state.skill_wheel_open ^= 1;
        if (player_state.skill_wheel_open) {
            player_state.skill_wheel_cursor = player_state.slotted_skill;
            if (player_state.skill_wheel_cursor == 0xFF)
                player_state.skill_wheel_cursor = 0;
            audio_play_sfx(SFX_MENU_SELECT);
        }
    }

    /* D-pad in wheel — blocks other input */
    if (player_state.skill_wheel_open) {
        int count = player_get_skill_count();
        if (input_hit(KEY_UP) && player_state.skill_wheel_cursor > 0)
            player_state.skill_wheel_cursor--;
        if (input_hit(KEY_DOWN) && player_state.skill_wheel_cursor < count - 1)
            player_state.skill_wheel_cursor++;
        if (input_hit(KEY_A)) {
            player_state.slotted_skill = player_state.skill_wheel_cursor;
            player_state.skill_wheel_open = 0;
            audio_play_sfx(SFX_MENU_SELECT);
        }
        if (input_hit(KEY_B) || input_hit(KEY_SELECT)) {
            player_state.skill_wheel_open = 0;
            audio_play_sfx(SFX_MENU_BACK);
        }
        goto post_input; /* Block movement/combat input while wheel open */
    }

    /* ==== R: fire slotted skill ==== */
    if (input_hit(KEY_R) && player_state.slotted_skill != 0xFF) {
        if (player_state.skill_cooldown == 0) {
            int sid = player_get_skill_id(player_state.slotted_skill);
            if (sid >= 0) {
                int rank = player_state.skill_ranks[player_state.slotted_skill];
                if (skill_activate(sid, rank, player_state.atk)) {
                    player_state.skill_cooldown = (u16)skill_get_cooldown(sid, rank);
                    audio_play_sfx(SFX_ABILITY);
                }
            }
        }
    }

    /* Horizontal movement */
    if (input_held(KEY_RIGHT)) {
        p_ent->facing = FACING_RIGHT;
        if (p_ent->on_ground) {
            p_ent->vx += phys->accel;
        } else {
            p_ent->vx += phys->air_accel;
        }
        if (p_ent->vx > effective_speed) p_ent->vx = (s16)effective_speed;
    } else if (input_held(KEY_LEFT)) {
        p_ent->facing = FACING_LEFT;
        if (p_ent->on_ground) {
            p_ent->vx -= phys->accel;
        } else {
            p_ent->vx -= phys->air_accel;
        }
        if (p_ent->vx < -effective_speed) p_ent->vx = (s16)(-effective_speed);
    } else {
        /* Decelerate — full on ground, half in air for platformer feel */
        s16 dec = p_ent->on_ground ? phys->decel : (s16)(phys->decel / 2);
        if (p_ent->vx > 0) {
            p_ent->vx -= dec;
            if (p_ent->vx < 0) p_ent->vx = 0;
        } else if (p_ent->vx < 0) {
            p_ent->vx += dec;
            if (p_ent->vx > 0) p_ent->vx = 0;
        }
    }

    /* Jump buffer: store press while airborne */
    if (input_hit(KEY_A)) player_state.jump_buffer = 6;

    /* Jump (with coyote time + jump buffer) */
    {
        int want_jump = input_hit(KEY_A) || player_state.jump_buffer > 0;
        if (want_jump) {
            if (p_ent->on_ground || player_state.coyote_timer <= COYOTE_FRAMES) {
                /* Normal/coyote jump */
                p_ent->vy = phys->jump_vel;
                player_state.jumps_remaining = (u8)(phys->max_jumps - 1);
                p_ent->on_ground = 0;
                player_state.coyote_timer = 255; /* Consume coyote window */
                player_state.jump_buffer = 0;
                audio_play_sfx(SFX_JUMP);
            } else if (p_ent->on_wall && phys->can_wall_jump) {
                /* Wall jump */
                p_ent->vy = phys->wall_jump_vy;
                int wall_side = physics_check_wall(p_ent, -1) ? -1 : 1;
                p_ent->vx = (wall_side < 0) ? phys->wall_jump_vx : -phys->wall_jump_vx;
                p_ent->facing = (wall_side < 0) ? FACING_RIGHT : FACING_LEFT;
                player_state.jumps_remaining = (u8)(phys->max_jumps - 1);
                player_state.jump_buffer = 0;
                audio_play_sfx(SFX_WALL_JUMP);
            } else if (player_state.jumps_remaining > 0 && input_hit(KEY_A)) {
                /* Double jump (Infiltrator) — only on fresh press, not buffer */
                p_ent->vy = (s16)(phys->jump_vel * 7 / 8);
                player_state.jumps_remaining--;
                player_state.jump_buffer = 0;
                audio_play_sfx(SFX_DOUBLE_JUMP);
                particle_burst(p_ent->x + ((s32)p_ent->width << 7),
                               p_ent->y + FP8(12),
                               3, PART_STAR, 140, 12);
            }
        }
    }

    /* Variable-height jump: cut velocity on button release */
    if (input_released(KEY_A) && p_ent->vy < phys->jump_cut) {
        p_ent->vy = phys->jump_cut;
    }

    /* Shooting (B button) */
    if (input_held(KEY_B) && player_state.shoot_cooldown == 0) {
        do_shoot();
        player_state.state = PSTATE_SHOOT;
    }

    /* ==== L button: class-specific movement skill ==== */
    if (input_hit(KEY_L)) {
        if (cls == CLASS_TROJAN && player_state.charge_rush_cooldown == 0) {
            /* Assault: Charge Rush */
            s16 cvx = 0, cvy = 0;
            if (input_held(KEY_UP)) {
                /* Diagonal upward charge */
                cvx = p_ent->facing == FACING_LEFT ? -448 : 448;
                cvy = -640;
            } else if (input_held(KEY_DOWN) && !p_ent->on_ground) {
                /* Downward slam (airborne only) */
                cvx = 0;
                cvy = 768;
            } else {
                /* Horizontal charge */
                cvx = p_ent->facing == FACING_LEFT ? -640 : 640;
                cvy = 0;
            }
            player_state.charge_vx = cvx;
            player_state.charge_vy = cvy;
            player_state.charge_rush_timer = 12;
            player_state.charge_rush_cooldown = 40;
            player_state.invincible_timer = 12;
            player_state.state = PSTATE_CHARGE;
            audio_play_sfx(SFX_CHARGE_RUSH);
            particle_burst(p_ent->x + FP8(6), p_ent->y + FP8(6), 3, PART_BURST, 180, 12);
        } else if (cls == CLASS_INFILTRATOR &&
                   player_state.dash_timer == 0 && player_state.dash_cooldown == 0) {
            /* Infiltrator: Dash (moved from R to L) */
            player_state.dash_timer = phys->dash_frames;
            p_ent->vx = p_ent->facing == FACING_LEFT ? -phys->dash_speed : phys->dash_speed;
            /* Phase Ring accessory: boost dash speed */
            {
                LootItem* dash_acc = inventory_get_equipped_accessory();
                if (dash_acc && LOOT_SUBTYPE(dash_acc->type) == ACC_PHASE_RING) {
                    s16 boost = (s16)(dash_acc->stat1 * 16);
                    if (p_ent->facing == FACING_LEFT) p_ent->vx = (s16)(p_ent->vx - boost);
                    else p_ent->vx = (s16)(p_ent->vx + boost);
                }
            }
            p_ent->vy = 0;
            player_state.state = PSTATE_DASH;
            if (player_state.invincible_timer < phys->dash_frames)
                player_state.invincible_timer = (u8)phys->dash_frames;
            audio_play_sfx(SFX_DASH);
        } else if (cls == CLASS_TECHNOMANCER && player_state.tether_cooldown == 0) {
            /* Technomancer: Tether Dash — scan for solid tile along d-pad direction */
            int scan_dx = 0, scan_dy = 0;
            if (input_held(KEY_UP)) {
                scan_dy = -1;
                if (input_held(KEY_LEFT)) scan_dx = -1;
                else if (input_held(KEY_RIGHT)) scan_dx = 1;
            } else if (input_held(KEY_DOWN)) {
                scan_dy = 1;
            } else {
                scan_dx = p_ent->facing == FACING_LEFT ? -1 : 1;
            }
            /* Scan for solid tile within 6 tiles along direction */
            int px = (int)(p_ent->x >> 8) + p_ent->width / 2;
            int py = (int)(p_ent->y >> 8) + p_ent->height / 2;
            int base_tx = px >> 3;
            int base_ty = py >> 3;
            int found = 0;
            for (int i = 1; i <= 6; i++) {
                int tx = base_tx + scan_dx * i;
                int ty = base_ty + scan_dy * i;
                /* Bounds check */
                if (tx < 0 || tx >= NET_MAP_W || ty < 0 || ty >= NET_MAP_H) break;
                /* Check tile at pixel center of that tile */
                int tile = collision_tile_at(tx * 8 + 4, ty * 8 + 4);
                if (tile == TILE_SOLID) {
                    /* Target = one tile before the solid tile */
                    player_state.tether_target_x = (s32)(tx - scan_dx) * 8 * 256;
                    player_state.tether_target_y = (s32)(ty - scan_dy) * 8 * 256;
                    /* Clamp to level bounds */
                    if (player_state.tether_target_x < 0) player_state.tether_target_x = 0;
                    if (player_state.tether_target_y < 0) player_state.tether_target_y = 0;
                    s32 max_tx = (s32)(NET_MAP_W * 8 - PLAYER_HITBOX_W) << 8;
                    s32 max_ty = (s32)(NET_MAP_H * 8 - PLAYER_HITBOX_H) << 8;
                    if (player_state.tether_target_x > max_tx) player_state.tether_target_x = max_tx;
                    if (player_state.tether_target_y > max_ty) player_state.tether_target_y = max_ty;
                    found = 1;
                    break;
                }
            }
            if (found) {
                player_state.state = PSTATE_TETHER;
                player_state.tether_timer = 30; /* Max 30 frames to reach target */
                player_state.tether_cooldown = 30;
                player_state.invincible_timer = 30; /* Invincible during pull */
                audio_play_sfx(SFX_TETHER_DASH);
                particle_spawn(p_ent->x + FP8(6), p_ent->y + FP8(6), 0, 0, PART_ELECTRIC, 12);
            } else {
                /* Fizzle: no solid tile found */
                particle_spawn(p_ent->x + FP8(6), p_ent->y + FP8(6), 0, 0, PART_SPARK, 8);
                /* Don't consume cooldown on fizzle */
            }
        }
    }

    /* Drop through platform (DOWN on one-way platform) */
    if (input_held(KEY_DOWN) && p_ent->on_ground) {
        int foot_x = (int)(p_ent->x >> 8) + p_ent->width / 2;
        int foot_y = (int)(p_ent->y >> 8) + p_ent->height;
        if (collision_tile_at(foot_x, foot_y) == TILE_PLATFORM) {
            p_ent->y += FP8(2); /* Nudge past platform top */
            p_ent->vy = 64;     /* Small downward velocity */
            p_ent->on_ground = 0;
        }
    }

post_input:
    /* Physics */
    physics_update(p_ent, phys);

    /* Speed trail: spawn fading spark every 3 frames when running fast */
    if (player_state.state == PSTATE_RUN && player_state.spd >= 6 &&
        (p_ent->anim_timer & 3) == 0) {
        s32 tx = p_ent->x + (p_ent->facing ? FP8(12) : -FP8(2));
        s32 ty = p_ent->y + FP8(8);
        s16 tvx = p_ent->facing ? (s16)40 : (s16)(-40);
        particle_spawn(tx, ty, tvx, (s16)-16, PART_SPARK, 8);
    }

    /* Screen shake + hit flash from video */
    video_shake_update();
    video_hit_flash_update();

    /* Abilities update */
    ability_update();

    /* Skill cooldown tick */
    if (player_state.skill_cooldown > 0)
        player_state.skill_cooldown--;

    /* Armor passive: HP regen tick */
    if (player_state.armor_flags & AFLAG_HP_REGEN) {
        if (player_state.armor_regen_timer > 0) player_state.armor_regen_timer--;
        else if (player_state.hp < player_state.max_hp) {
            player_state.hp++;
            player_state.armor_regen_timer = 120; /* 1 HP per 2 seconds */
        }
    }

    /* Projectiles updated by state_net_update — NOT here (avoid double-update) */
}

/* ---- Damage ---- */

void player_take_damage(int dmg, s16 kb_vx, s16 kb_vy) {
    if (!p_ent || player_state.invincible_timer > 0) return;
    if (player_state.state == PSTATE_DEAD) return;

    /* Phase Shell: dodge chance (stat1/4 percent) */
    if (player_state.armor_flags & AFLAG_DODGE_CHANCE) {
        LootItem* dodge_armor = inventory_get_equipped_armor();
        if (dodge_armor) {
            int dodge_pct = dodge_armor->stat1 / 4;
            if (dodge_pct > 0 && (int)rand_range(100) < dodge_pct) {
                hud_notify("DODGE!", 20);
                player_state.invincible_timer = 15;
                return;
            }
        }
    }

    /* Diminishing returns defense: actual = dmg * 256 / (256 + def * 8)
     * At DEF=16, reduces damage by ~33%. At DEF=32, ~50%. At DEF=64, ~67%. */
    int def_val = player_state.def;
    /* Iron Skin (Assault ability): DEF doubled while active */
    if (ability_is_iron_skin_active()) def_val *= 2;
    /* Berserk (Assault ability): DEF halved while active (tradeoff for ATK boost) */
    if (ability_is_berserk_active()) def_val /= 2;
    int def_factor = 256 + def_val * 8;
    int actual = dmg * 256 / def_factor;
    /* Data Shield (Technomancer ability): halve incoming damage */
    if (ability_is_data_shield_active()) {
        actual = actual / 2;
    }
    /* Firewall (Technomancer ability): absorb half, reflect to nearby enemies */
    if (ability_is_firewall_active()) {
        int reflected = actual / 2;
        actual = actual - reflected;
        if (reflected > 0) enemy_stun_all(reflected);
    }
    /* TODO: skill rank defense resist — added in Task 11 */
    if (actual < 1) actual = 1;

    /* Nano Mesh: flat -1 damage resist */
    if (player_state.armor_flags & AFLAG_DAMAGE_RESIST) {
        actual--;
        if (actual < 1) actual = 1;
    }

    player_state.hp -= (s16)actual;
    /* Track damage taken stat */
    if (game_stats.damage_taken < 65535 - actual) game_stats.damage_taken += (u16)actual;
    else game_stats.damage_taken = 65535;
    /* Reset kill combo on taking damage */
    game_stats.current_combo = 0;

    if (player_state.hp <= 0) {
        player_state.hp = 0;
        player_state.state = PSTATE_DEAD;
        if (game_stats.total_deaths < 65535) game_stats.total_deaths++;
        audio_play_sfx(SFX_PLAYER_DIE);
        video_shake(10, 2);
        video_flash_start(2, 6); /* white flash on death */
        /* Death explosion particles */
        {
            s32 cx = p_ent->x + ((s32)p_ent->width << 7);
            s32 cy = p_ent->y + ((s32)p_ent->height << 7);
            particle_burst(cx, cy, 6, PART_BURST, 200, 20);
            particle_burst(cx, cy, 4, PART_SPARK, 160, 14);
        }
        return;
    }

    p_ent->vx = kb_vx;
    p_ent->vy = kb_vy;
    /* Titan Frame: halve knockback velocity */
    if (player_state.armor_flags & AFLAG_KB_RESIST) {
        p_ent->vx /= 2;
        p_ent->vy /= 2;
    }
    /* Clamp knockback to prevent OOB launches (boss knockback fix) */
    if (p_ent->vx > MAX_KNOCKBACK) p_ent->vx = MAX_KNOCKBACK;
    if (p_ent->vx < -MAX_KNOCKBACK) p_ent->vx = -MAX_KNOCKBACK;
    if (p_ent->vy > MAX_KNOCKBACK) p_ent->vy = MAX_KNOCKBACK;
    if (p_ent->vy < -MAX_KNOCKBACK) p_ent->vy = -MAX_KNOCKBACK;
    player_state.invincible_timer = 60;
    player_state.state = PSTATE_HIT;
    audio_play_sfx(SFX_PLAYER_HIT);
    video_shake(4, 1); /* subtle shake on hit */
    video_hit_flash_start(0, 2); /* Brief red tint on player palette bank */
    /* Damage direction indicator — kb_vx > 0 means hit from left (pushed right) */
    hud_damage_direction(kb_vx < 0 ? 1 : 0);
}

/* ---- XP / Level-up ---- */

int player_xp_to_next(void) {
    /* Quadratic: BASE_XP * level * (100 + level) / 100
     * L10: 990, L20: 2160, L30: 3510, L40: 5040 */
    int lv = player_state.level;
    return BASE_XP * lv * (100 + lv) / 100;
}

void player_add_xp(int amount) {
    /* TODO: shop_buff_active(CHARGE_XP_BOOSTER) check -- added in Task 11 */
    int xp_bonus = 0;
    /* XP Booster accessory */
    {
        LootItem* xp_acc = inventory_get_equipped_accessory();
        if (xp_acc && LOOT_SUBTYPE(xp_acc->type) == ACC_XP_BOOSTER)
            xp_bonus += xp_acc->stat1 * 3;
    }
    if (xp_bonus > 0) amount = amount * (100 + xp_bonus) / 100;
    /* Use int accumulator to prevent u32 overflow/wrap */
    int xp = (int)player_state.xp + amount;
    int cap = game_stats.endgame_unlocked ? MAX_LEVEL_ENDGAME : MAX_LEVEL_BASE;
    while ((int)player_state.level < cap) {
        int needed = player_xp_to_next();
        if (xp < needed) break;
        xp -= needed;
        /* Apply stat GAINS as deltas to preserve any shop upgrade bonuses */
        {
            int cls = (int)player_state.player_class;
            int old_lv = (int)player_state.level;
            player_state.level++;
            int new_lv = (int)player_state.level;
            /* Track highest level for endgame stats */
            if (new_lv > (int)game_stats.bb_highest_level)
                game_stats.bb_highest_level = (u8)(new_lv > 255 ? 255 : new_lv);
            s16 old_hp, old_atk, old_def, old_spd, old_lck;
            s16 new_hp, new_atk, new_def, new_spd, new_lck;
            player_get_base_stats(cls, old_lv, &old_hp, &old_atk, &old_def, &old_spd, &old_lck);
            player_get_base_stats(cls, new_lv, &new_hp, &new_atk, &new_def, &new_spd, &new_lck);
            int dhp = new_hp - old_hp;
            int datk = new_atk - old_atk;
            int ddef = new_def - old_def;
            player_state.max_hp = (s16)(player_state.max_hp + dhp);
            player_state.atk    = (s16)(player_state.atk    + datk);
            player_state.def    = (s16)(player_state.def    + ddef);
            player_state.spd    = (s16)(player_state.spd    + (new_spd - old_spd));
            player_state.lck    = (s16)(player_state.lck    + (new_lck - old_lck));

            /* Build level-up message with stat gains */
            {
                static char lvl_buf[24];
                int pos = 0;
                lvl_buf[pos++] = 'L';
                lvl_buf[pos++] = 'V';
                lvl_buf[pos++] = 'L';
                lvl_buf[pos++] = ' ';
                if (new_lv >= 100) lvl_buf[pos++] = (char)('0' + new_lv / 100);
                if (new_lv >= 10) lvl_buf[pos++] = (char)('0' + (new_lv / 10) % 10);
                lvl_buf[pos++] = (char)('0' + new_lv % 10);
                lvl_buf[pos++] = '!';
                /* Append stat gains if any */
                if (dhp > 0 || datk > 0 || ddef > 0) {
                    lvl_buf[pos++] = ' ';
                    if (dhp > 0) {
                        lvl_buf[pos++] = 'H';
                        lvl_buf[pos++] = '+';
                        lvl_buf[pos++] = (char)('0' + (dhp > 9 ? 9 : dhp));
                    }
                    if (datk > 0) {
                        lvl_buf[pos++] = ' ';
                        lvl_buf[pos++] = 'A';
                        lvl_buf[pos++] = '+';
                        lvl_buf[pos++] = (char)('0' + (datk > 9 ? 9 : datk));
                    }
                    if (ddef > 0) {
                        lvl_buf[pos++] = ' ';
                        lvl_buf[pos++] = 'D';
                        lvl_buf[pos++] = '+';
                        lvl_buf[pos++] = (char)('0' + (ddef > 9 ? 9 : ddef));
                    }
                }
                lvl_buf[pos] = '\0';
                hud_notify(lvl_buf, 90);
            }
        }
        /* 75% heal on level up -- maintains endurance tension */
        player_state.hp = (s16)(player_state.max_hp * 3 / 4);
        if (player_state.hp < 1) player_state.hp = 1;
        /* Grant 1 skill point per level */
        player_state.skill_points++;
        /* Level-up celebration: subtle particles */
        if (p_ent) {
            particle_burst(p_ent->x, p_ent->y - FP8(4), 3, PART_STAR, 180, 16);
        }
        audio_play_sfx(SFX_EVOLVE);
        /* Brief invincibility as level-up reward */
        if (player_state.invincible_timer < 30)
            player_state.invincible_timer = 30;
        /* Achievement: Max Level */
        if (player_state.level >= MAX_LEVEL_BASE && !ach_unlocked(ACH_MAX_LEVEL)) {
            ach_unlock_celebrate(ACH_MAX_LEVEL);
        }
    }
    if (xp < 0) xp = 0;
    player_state.xp = (u32)xp;
}

/* ---- Render ---- */

void player_draw(s32 cam_x, s32 cam_y) {
    if (!p_ent || p_ent->oam_index == OAM_NONE) return;

    /* Invincibility flash */
    if (player_state.invincible_timer > 0 && (player_state.invincible_timer & 2)) {
        OBJ_ATTR* spr = sprite_get(p_ent->oam_index);
        if (spr) obj_hide(spr);
        return;
    }

    int cx = (int)(cam_x >> 8);
    int cy = (int)(cam_y >> 8);
    int sx = (int)(p_ent->x >> 8) - cx - 2;  /* Center 12px hitbox in 16px sprite */
    int sy = (int)(p_ent->y >> 8) - cy - 1;

    /* Select animation frame (12 frames: idle0-1, run0-3, jump, fall,
     * shoot0-1, wallslide, dash) */
    int frame;
    switch (player_state.state) {
    case PSTATE_RUN:
        frame = 2 + ((p_ent->anim_timer >> 2) & 3); /* 4-frame run cycle @ ~15fps */
        break;
    case PSTATE_JUMP:
        frame = 6;
        break;
    case PSTATE_FALL:
        frame = 7;
        break;
    case PSTATE_SHOOT:
        frame = 8 + ((p_ent->anim_timer >> 3) & 1); /* shoot0/shoot1 */
        break;
    case PSTATE_WALL_SLIDE:
        frame = 10;
        break;
    case PSTATE_DASH:
    case PSTATE_CHARGE:   /* Reuse dash animation for charge rush */
    case PSTATE_TETHER:   /* Reuse dash animation for tether pull */
        frame = 11;
        break;
    case PSTATE_TETHER_HOLD:
        frame = 10; /* Reuse wall slide animation for tether hold */
        break;
    default:
        frame = (p_ent->anim_timer >> 4) & 1; /* idle0/idle1 breathing @ ~4fps */
        break;
    }

    int tile_id = PLAYER_TILE_BASE + frame * 4;

    OBJ_ATTR* spr = sprite_get(p_ent->oam_index);
    if (!spr) return;

    u16 flip = p_ent->facing ? ATTR1_HFLIP : 0;  /* sprite faces RIGHT natively */

    obj_unhide(spr, ATTR0_REG);
    spr->attr0 = (u16)((sy & ATTR0_Y_MASK) | ATTR0_SQUARE | ATTR0_4BPP);
    spr->attr1 = (u16)((sx & ATTR1_X_MASK) | ATTR1_SIZE_16 | flip);
    spr->attr2 = (u16)(ATTR2_ID(tile_id) | ATTR2_PALBANK(PLAYER_PAL_BANK));

    /* Projectiles drawn by state_net_draw — NOT here (avoid double-draw) */
}

/* ---- New tier-based helper functions ---- */

int player_has_class(void) {
    return player_state.player_class != 0xFF;
}

int player_get_skill_count(void) {
    u8 ids[MAX_PLAYER_SKILLS];
    return skills_get_unlocked(
        player_state.tier_choices[0],
        player_state.tier_choices[1],
        player_state.tier_choices[2],
        ids);
}

int player_get_skill_id(int idx) {
    u8 ids[MAX_PLAYER_SKILLS];
    int count = skills_get_unlocked(
        player_state.tier_choices[0],
        player_state.tier_choices[1],
        player_state.tier_choices[2],
        ids);
    if (idx < 0 || idx >= count) return -1;
    return ids[idx];
}

const char* player_get_tier_name(void) {
    if (player_state.tier_choices[2] != 0xFF)
        return tier_get_name(3, player_state.tier_choices[2]);
    if (player_state.tier_choices[1] != 0xFF)
        return tier_get_name(2, player_state.tier_choices[1]);
    if (player_state.tier_choices[0] != 0xFF)
        return tier_get_name(1, player_state.tier_choices[0]);
    return "Classless";
}

/* Achievement short names (max ~20 chars for hud_notify) */
static const char* const ach_names[ACH_COUNT] = {
    "First Blood!",    "Hunter!",        "Exterminator!",
    "Boss Slayer!",    "Speed Run!",     "Pacifist!",
    "Untouchable!",    "Looter!",        "Legendary Find!",
    "Full Set!",       "Craftsman!",     "Master Crafter!",
    "Tier Up!",        "Max Level!",     "Completionist!",
    "Bug Hunter!",     "Millionaire!",   "Skill Master!",
    "NG+ Cleared!",    "True Ghost!",    "Endgame!",
    "Bounty Hunter!",  "Mythic Find!",   "Threat Lv5!",
};

/* ---- Charge Rush Contact Damage ----
 * INTEGRATION NOTE: enemy.c should call this when the player is in PSTATE_CHARGE
 * to determine contact damage (1.5x ATK). Returns the damage amount. */
int player_charge_rush_damage(void) {
    return player_state.atk * 3 / 2;
}

int player_load_preview(int screen_x, int screen_y, int suit_color, int visor_color) {
    /* Load idle frame (4 tiles) into OBJ tile memory */
    memcpy16(&tile_mem_obj[0][PLAYER_TILE_BASE], player_tiles, 4 * 32 / 2);

    /* Load base palette (classless = Trojan base) and apply colors */
    memcpy16(&pal_obj_mem[PLAYER_PAL_BANK * 16], class_palettes[CLASS_TROJAN], 16);
    colors_apply_player_palette(suit_color, visor_color);

    /* Allocate OAM sprite */
    int oam = sprite_alloc();
    if (oam < 0) return -1;

    OBJ_ATTR* spr = sprite_get(oam);
    if (!spr) { sprite_free(oam); return -1; }

    obj_unhide(spr, ATTR0_REG);
    spr->attr0 = (u16)((screen_y & ATTR0_Y_MASK) | ATTR0_SQUARE | ATTR0_4BPP);
    spr->attr1 = (u16)((screen_x & ATTR1_X_MASK) | ATTR1_SIZE_16);
    spr->attr2 = (u16)(ATTR2_ID(PLAYER_TILE_BASE) | ATTR2_PALBANK(PLAYER_PAL_BANK));

    return oam;
}

/* Achievement unlock with visual celebration */
void ach_unlock_celebrate(int id) {
    if (ach_unlocked(id)) return;
    ach_unlock(id);
    if (id >= 0 && id < ACH_COUNT) {
        hud_notify(ach_names[id], 90);
    } else {
        hud_notify("ACHIEVEMENT!", 90);
    }
    audio_play_sfx(SFX_ACHIEVEMENT);
    /* Spawn celebration stars at top of screen if player entity exists */
    if (p_ent) {
        particle_burst(p_ent->x + FP8(6), p_ent->y - FP8(8), 3, PART_STAR, 150, 16);
    }
}
