/*
 * Ghost Protocol — Player System
 *
 * 3 playable classes with stats, shooting, movement state machine.
 * Uses physics.c for platformer movement + collision.
 */
#include "game/player.h"
#include "game/projectile.h"
#include "game/abilities.h"
#include "game/loot.h"
#include "game/hud.h"
#include "engine/input.h"
#include "engine/collision.h"
#include "engine/sprite.h"
#include "engine/audio.h"
#include "engine/video.h"
#include "engine/entity.h"
#include <string.h>

PlayerState player_state;
static Entity* p_ent = NULL;
static int selected_ability = 0; /* Currently selected ability slot (0-3) */
static int coyote_timer = 0;     /* Frames since leaving ground (4 = coyote window) */

/* ---- Player sprite data (16x16, 4 tiles per frame) ---- */
/* 6 frames: idle0, idle1, run0, run1, jump, shoot */
/* Placeholder: simple humanoid silhouette */

/* Player sprites: 16x16 cyberpunk netrunner, 12 frames x 4 tiles = 48 tiles
 * Palette indices: 0=transparent, 1=armor deep shadow, 2=armor shadow,
 *   3=armor base, 4=armor highlight, 5=visor dim, 6=visor bright,
 *   7=visor core, 8=skin shadow, 9=skin base, A=skin highlight,
 *   B=circuit dark, C=circuit bright, D=AA edge dark, E=AA edge light,
 *   F=pure white highlight */
/* Samus-inspired cyberpunk netrunner facing RIGHT.
 * Dominant round helmet (rows 0-6), glowing full-face visor (rows 2-4),
 * chunky 4px arm cannon (cols 10-13 rows 7-8), thick paired legs.
 * Generated by tools/sprite_gen.py. */
static const u32 player_tiles[48][8] = {
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 0 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 0 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 0 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 0 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 1 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x00000012 }, /* Frame 1 TR */
    { 0x34443100, 0x33343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 1 BL */
    { 0x01BCCB12, 0x01BCCB12, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 1 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 2 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 2 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00013310, 0x00013311, 0x00013110, 0x00011100, 0x00000000 }, /* Frame 2 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00013310, 0x00013310, 0x00012310, 0x00011110, 0x00000000 }, /* Frame 2 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 3 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 3 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 3 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 3 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 4 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 4 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 4 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00013310, 0x00013310, 0x00003310, 0x00000110, 0x00000000 }, /* Frame 4 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 5 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 5 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00233100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 5 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00002331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 5 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 6 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 6 TR */
    { 0x34443100, 0x13331000, 0x12333100, 0x01233100, 0x00121100, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 6 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 6 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 7 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01BCCB12 }, /* Frame 7 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00133100, 0x00123100, 0x00111100 }, /* Frame 7 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001331, 0x00001231, 0x00001111 }, /* Frame 7 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 8 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01FCCB12 }, /* Frame 8 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 8 BL */
    { 0x01FCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 8 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 9 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x01DCCB12 }, /* Frame 9 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x00133100, 0x00133100, 0x00123100, 0x00111100, 0x00000000 }, /* Frame 9 BL */
    { 0x01BCCB12, 0x00000000, 0x00000000, 0x00001331, 0x00001331, 0x00001231, 0x00001111, 0x00000000 }, /* Frame 9 BR */
    { 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x66631000, 0x44431000, 0x11111000, 0x34443100 }, /* Frame 10 TL */
    { 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001366, 0x00001344, 0x00001111, 0x00000001 }, /* Frame 10 TR */
    { 0x34443100, 0x12343100, 0x13331000, 0x01233100, 0x01233310, 0x00123310, 0x00011110, 0x00000000 }, /* Frame 10 BL */
    { 0x00000001, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 10 BR */
    { 0x00000000, 0x11100000, 0x44431000, 0x66631000, 0x77731000, 0x44431000, 0x11111000, 0x34444431 }, /* Frame 11 TL */
    { 0x00000000, 0x00000111, 0x00001344, 0x00001366, 0x00001377, 0x00001344, 0x00001111, 0x01FCCB12 }, /* Frame 11 TR */
    { 0x34444310, 0x23310000, 0x12331000, 0x01233100, 0x00011110, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 11 BL */
    { 0x01BCCB12, 0x00000001, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000 }, /* Frame 11 BR */
};

/* Per-class palettes — full 16-color material shading ramps
 * 0=transparent, 1-4=metal ramp (shadow→base→highlight→rim),
 * 5-7=glow ramp (dim→bright→core), 8-A=skin ramp,
 * B-C=circuit accent pair, D-E=AA edge colors, F=pure white */
static const u16 class_palettes[CLASS_COUNT][16] = {
    [CLASS_ASSAULT] = {
        0x0000,                /* 0: transparent */
        RGB15_C(2,3,8),        /* 1: outline (near-black) */
        RGB15_C(8,12,22),      /* 2: armor shadow */
        RGB15_C(12,17,27),     /* 3: armor base */
        RGB15_C(18,22,29),     /* 4: armor highlight */
        RGB15_C(24,4,2),       /* 5: visor dim red */
        RGB15_C(30,10,6),      /* 6: visor bright */
        RGB15_C(31,18,12),     /* 7: visor core glow */
        RGB15_C(16,12,10),     /* 8: skin shadow */
        RGB15_C(22,18,14),     /* 9: skin base */
        RGB15_C(26,22,18),     /* A: skin highlight */
        RGB15_C(2,10,14),      /* B: circuit dark teal */
        RGB15_C(4,22,28),      /* C: circuit bright cyan */
        RGB15_C(4,6,14),       /* D: AA edge dark */
        RGB15_C(14,18,26),     /* E: AA edge light */
        RGB15_C(31,31,31),     /* F: pure white */
    },
    [CLASS_INFILTRATOR] = {
        0x0000,                /* 0: transparent */
        RGB15_C(2,2,3),        /* 1: outline (near-black) */
        RGB15_C(4,5,7),        /* 2: suit shadow */
        RGB15_C(7,8,10),       /* 3: suit base dark grey */
        RGB15_C(11,12,14),     /* 4: suit highlight */
        RGB15_C(2,20,8),       /* 5: visor dim green */
        RGB15_C(6,28,14),      /* 6: visor bright green */
        RGB15_C(14,31,20),     /* 7: visor core glow */
        RGB15_C(14,10,8),      /* 8: skin shadow */
        RGB15_C(20,16,12),     /* 9: skin base */
        RGB15_C(24,20,16),     /* A: skin highlight */
        RGB15_C(2,8,4),        /* B: circuit dark */
        RGB15_C(4,20,10),      /* C: circuit bright */
        RGB15_C(2,3,5),        /* D: AA edge dark */
        RGB15_C(8,10,12),      /* E: AA edge light */
        RGB15_C(28,31,28),     /* F: green-white highlight */
    },
    [CLASS_TECHNOMANCER] = {
        0x0000,                /* 0: transparent */
        RGB15_C(4,3,2),        /* 1: outline (near-black) */
        RGB15_C(12,9,5),       /* 2: coat shadow */
        RGB15_C(18,14,8),      /* 3: coat base */
        RGB15_C(24,20,14),     /* 4: coat highlight */
        RGB15_C(22,14,2),      /* 5: visor dim amber */
        RGB15_C(28,22,6),      /* 6: visor bright amber */
        RGB15_C(31,28,14),     /* 7: visor core glow */
        RGB15_C(16,12,10),     /* 8: skin shadow */
        RGB15_C(22,18,14),     /* 9: skin base */
        RGB15_C(26,22,18),     /* A: skin highlight */
        RGB15_C(14,10,4),      /* B: circuit dark gold */
        RGB15_C(24,18,6),      /* C: circuit bright gold */
        RGB15_C(8,6,3),        /* D: AA edge dark */
        RGB15_C(16,12,8),      /* E: AA edge light */
        RGB15_C(31,28,20),     /* F: warm white */
    },
};

#define PLAYER_TILE_BASE 0
#define PLAYER_PAL_BANK  0
#define PLAYER_W  16
#define PLAYER_H  16
#define PLAYER_HITBOX_W 12
#define PLAYER_HITBOX_H 14

/* ---- Base stat tables ---- */
/* Stats at level 1 */
static const s16 base_stats[CLASS_COUNT][5] = {
    /* HP, ATK, DEF, SPD, LCK */
    [CLASS_ASSAULT]      = { 40, 10, 6, 4, 2 },
    [CLASS_INFILTRATOR]  = { 30,  7, 4, 8, 5 },
    [CLASS_TECHNOMANCER] = { 35,  8, 7, 5, 3 },
};
/* Per-level gains */
static const s16 level_gains[CLASS_COUNT][5] = {
    [CLASS_ASSAULT]      = { 3, 2, 1, 1, 0 },
    [CLASS_INFILTRATOR]  = { 2, 1, 1, 2, 1 },
    [CLASS_TECHNOMANCER] = { 2, 1, 2, 1, 1 },
};

/* ---- Implementation ---- */

void player_get_base_stats(int cls, int lvl, s16* hp, s16* atk, s16* def, s16* spd, s16* lck) {
    int lv = lvl - 1;
    if (lv < 0) lv = 0;
    *hp  = (s16)(base_stats[cls][0] + level_gains[cls][0] * lv);
    *atk = (s16)(base_stats[cls][1] + level_gains[cls][1] * lv);
    *def = (s16)(base_stats[cls][2] + level_gains[cls][2] * lv);
    *spd = (s16)(base_stats[cls][3] + level_gains[cls][3] * lv);
    *lck = (s16)(base_stats[cls][4] + level_gains[cls][4] * lv);
}

static void compute_stats(void) {
    int cls = player_state.player_class;
    int lvl = player_state.level;
    player_get_base_stats(cls, lvl,
                          &player_state.max_hp, &player_state.atk,
                          &player_state.def, &player_state.spd,
                          &player_state.lck);
}

static void check_ability_unlocks(void) {
    int lv = player_state.level;
    u8 mask = 0;
    if (lv >= AB_UNLOCK_1) mask |= ABILITY_1;
    if (lv >= AB_UNLOCK_2) mask |= ABILITY_2;
    if (lv >= AB_UNLOCK_3) mask |= ABILITY_3;
    if (lv >= AB_UNLOCK_4) mask |= ABILITY_4;
    player_state.ability_unlocks = mask;
}

void player_init(int player_class) {
    /* Bounds check */
    if (player_class < 0 || player_class >= CLASS_COUNT) player_class = CLASS_ASSAULT;

    /* Spawn entity */
    entity_init();
    p_ent = entity_spawn(ENT_PLAYER);
    if (!p_ent) return;

    /* Clear state */
    memset(&player_state, 0, sizeof(player_state));
    player_state.player_class = (u8)player_class;
    player_state.level = 1;
    player_state.state = PSTATE_IDLE;
    player_state.credits = 100;

    /* Compute stats */
    compute_stats();
    player_state.hp = player_state.max_hp;

    check_ability_unlocks();
    ability_reset();

    /* Setup entity */
    p_ent->x = FP8(64);
    p_ent->y = FP8(128);
    p_ent->width = PLAYER_HITBOX_W;
    p_ent->height = PLAYER_HITBOX_H;
    p_ent->facing = FACING_RIGHT;

    /* Allocate OAM sprite (16x16) */
    int oam = sprite_alloc();
    if (oam >= 0) {
        p_ent->oam_index = (u8)oam;
        OBJ_ATTR* spr = sprite_get(oam);
        if (spr) {
            spr->attr0 = ATTR0_SQUARE | ATTR0_4BPP;
            spr->attr1 = ATTR1_SIZE_16;
            spr->attr2 = (u16)(ATTR2_ID(PLAYER_TILE_BASE) | ATTR2_PALBANK(PLAYER_PAL_BANK));
        }
    }

    /* Load graphics */
    memcpy16(&tile_mem_obj[0][PLAYER_TILE_BASE], player_tiles, sizeof(player_tiles) / 2);
    memcpy16(&pal_obj_mem[PLAYER_PAL_BANK * 16], class_palettes[player_class], 16);

    /* Init projectile pool */
    projectile_init();
}

Entity* player_get(void) {
    return p_ent;
}

int player_is_alive(void) {
    return player_state.hp > 0;
}

/* ---- Shooting ---- */

static void do_shoot(void) {
    if (!p_ent) return;
    int cls = player_state.player_class;
    s16 dir_x;
    s32 spawn_x, spawn_y;

    spawn_y = p_ent->y + FP8(4);
    if (p_ent->facing == FACING_LEFT) {
        dir_x = -512;
        spawn_x = p_ent->x - FP8(4);
    } else {
        dir_x = 512;
        spawn_x = p_ent->x + FP8(12);
    }

    /* Get equipped weapon stats (if any) */
    LootItem* weapon = inventory_get_equipped();
    int dmg = player_state.atk;
    int base_cooldown;

    if (weapon) {
        /* Weapon adds to damage and modifies fire rate */
        dmg += weapon->stat1;
        base_cooldown = weapon->stat2; /* Lower = faster */
    } else {
        base_cooldown = 0; /* No weapon = use class default */
    }

    /* Weapon type modifies projectile behavior */
    int wtype = weapon ? weapon->type : WEAPON_BUSTER;

    /* Per-weapon projectile color — write 4 key palette entries to bank 14 */
    {
        u16 c1, c2, c3, c4; /* bright, mid, dark, glow */
        switch (wtype) {
        case WEAPON_RAPID:
            c1 = RGB15_C(4,31,12);  c2 = RGB15_C(2,22,8);
            c3 = RGB15_C(0,14,4);   c4 = RGB15_C(12,31,20);
            break;
        case WEAPON_SPREAD:
            c1 = RGB15_C(31,24,4);  c2 = RGB15_C(24,16,2);
            c3 = RGB15_C(16,10,0);  c4 = RGB15_C(31,28,12);
            break;
        case WEAPON_CHARGER:
            c1 = RGB15_C(31,31,20); c2 = RGB15_C(24,24,14);
            c3 = RGB15_C(16,16,8);  c4 = RGB15_C(31,31,28);
            break;
        case WEAPON_BEAM:
            c1 = RGB15_C(28,8,31);  c2 = RGB15_C(20,4,24);
            c3 = RGB15_C(12,2,16);  c4 = RGB15_C(31,16,31);
            break;
        default: /* WEAPON_BUSTER — cyan (default) */
            c1 = RGB15_C(0,28,31);  c2 = RGB15_C(0,20,24);
            c3 = RGB15_C(0,12,16);  c4 = RGB15_C(8,31,31);
            break;
        }
        pal_obj_mem[14*16 + 1] = c1;
        pal_obj_mem[14*16 + 2] = c2;
        pal_obj_mem[14*16 + 3] = c3;
        pal_obj_mem[14*16 + 4] = c4;
    }

    switch (cls) {
    case CLASS_ASSAULT:
    {
        int cd = weapon ? base_cooldown : 12;
        if (wtype == WEAPON_SPREAD && weapon) {
            /* 3 projectiles in a spread, 2/3 damage each */
            s16 sdmg = (s16)(dmg * 2 / 3);
            projectile_spawn(spawn_x, spawn_y, dir_x, 0, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, -96, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            projectile_spawn(spawn_x, spawn_y, dir_x, 96, sdmg, SUBTYPE_PROJ_BUSTER, 0, 0);
            cd += 4; /* Spread fires slower */
        } else if (wtype == WEAPON_BEAM && weapon) {
            /* Piercing beam, slightly slower */
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BEAM, PROJ_PIERCE, 0);
            cd += 6;
        } else if (wtype == WEAPON_CHARGER && weapon) {
            /* Slow but 2x damage */
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 2 / 3), 0,
                             (s16)(dmg * 2), SUBTYPE_PROJ_CHARGE, 0, 0);
            cd += 8;
        } else {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BUSTER, 0, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        audio_play_sfx(SFX_SHOOT);
        break;
    }
    case CLASS_INFILTRATOR:
    {
        int cd = weapon ? GP_MAX(base_cooldown - 3, 4) : 6;
        if (wtype == WEAPON_RAPID && weapon) {
            /* Extra fast with bonus speed */
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 3 / 2), 0,
                             (s16)(dmg * 2 / 3), SUBTYPE_PROJ_RAPID, 0, 0);
            cd = GP_MAX(cd - 2, 3);
        } else if (wtype == WEAPON_SPREAD && weapon) {
            s16 sdmg = (s16)(dmg / 2);
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), -64, sdmg, SUBTYPE_PROJ_RAPID, 0, 0);
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), 64, sdmg, SUBTYPE_PROJ_RAPID, 0, 0);
            cd += 2;
        } else {
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x + dir_x / 4), 0,
                             (s16)(dmg * 2 / 3), SUBTYPE_PROJ_RAPID, 0, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        audio_play_sfx(SFX_SHOOT_RAPID);
        break;
    }
    case CLASS_TECHNOMANCER:
    {
        int cd = weapon ? base_cooldown : 10;
        if (wtype == WEAPON_BEAM && weapon) {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BEAM, PROJ_PIERCE, 0);
            cd += 4;
        } else if (wtype == WEAPON_CHARGER && weapon) {
            projectile_spawn(spawn_x, spawn_y, (s16)(dir_x * 2 / 3), 0,
                             (s16)(dmg * 2), SUBTYPE_PROJ_CHARGE, 0, 0);
            cd += 6;
        } else {
            projectile_spawn(spawn_x, spawn_y, dir_x, 0,
                             (s16)dmg, SUBTYPE_PROJ_BUSTER, 0, 0);
        }
        player_state.shoot_cooldown = (u8)cd;
        audio_play_sfx(SFX_SHOOT);
        break;
    }
    }

    /* Overclock: halve cooldown when active (Assault ability) */
    if (ability_is_overclock_active()) {
        player_state.shoot_cooldown = (u8)(player_state.shoot_cooldown / 2);
        if (player_state.shoot_cooldown < 1) player_state.shoot_cooldown = 1;
    }
}

/* ---- Movement + state machine ---- */

void player_update(void) {
    if (!p_ent || player_state.state == PSTATE_DEAD) return;

    int cls = player_state.player_class;
    const PhysicsParams* phys = &physics_class[cls];

    /* Tick timers */
    if (player_state.shoot_cooldown > 0) player_state.shoot_cooldown--;
    if (player_state.invincible_timer > 0) player_state.invincible_timer--;
    if (player_state.dash_timer > 0) player_state.dash_timer--;
    if (player_state.dash_cooldown > 0) player_state.dash_cooldown--;

    /* Hit stun */
    if (player_state.state == PSTATE_HIT) {
        physics_update(p_ent, phys);
        if (player_state.invincible_timer < 50) {
            player_state.state = PSTATE_IDLE;
        }
        return;
    }

    /* Dash state */
    if (player_state.state == PSTATE_DASH) {
        if (player_state.dash_timer == 0) {
            player_state.state = p_ent->on_ground ? PSTATE_IDLE : PSTATE_FALL;
            player_state.dash_cooldown = phys->dash_cooldown;
        }
        physics_update(p_ent, phys);
        return;
    }

    /* Update animation state (before input for immediate draw response).
     * Preserve PSTATE_SHOOT for 6 frames so mid-air shooting is visible. */
    p_ent->anim_timer++;
    int keep_shoot = (player_state.state == PSTATE_SHOOT && player_state.shoot_cooldown > 0);
    if (p_ent->on_ground) {
        if (!keep_shoot) {
            if (p_ent->vx != 0) {
                player_state.state = PSTATE_RUN;
            } else {
                player_state.state = PSTATE_IDLE;
            }
        }
        player_state.jumps_remaining = phys->max_jumps;
        coyote_timer = 0;
    } else {
        /* Coyote time: 4 frames after leaving ground where jump still counts */
        if (coyote_timer < 255) coyote_timer++;
    }
    if (!p_ent->on_ground && !keep_shoot) {
        if (p_ent->on_wall) {
            player_state.state = PSTATE_WALL_SLIDE;
        } else if (p_ent->vy < 0) {
            player_state.state = PSTATE_JUMP;
        } else {
            player_state.state = PSTATE_FALL;
        }
    }

    /* ---- Input ---- */

    /* Horizontal movement */
    if (input_held(KEY_RIGHT)) {
        p_ent->facing = FACING_RIGHT;
        if (p_ent->on_ground) {
            p_ent->vx += phys->accel;
        } else {
            p_ent->vx += phys->air_accel;
        }
        if (p_ent->vx > phys->move_speed) p_ent->vx = phys->move_speed;
    } else if (input_held(KEY_LEFT)) {
        p_ent->facing = FACING_LEFT;
        if (p_ent->on_ground) {
            p_ent->vx -= phys->accel;
        } else {
            p_ent->vx -= phys->air_accel;
        }
        if (p_ent->vx < -phys->move_speed) p_ent->vx = -phys->move_speed;
    } else {
        /* Decelerate — full on ground, half in air for platformer feel */
        s16 dec = p_ent->on_ground ? phys->decel : (s16)(phys->decel / 2);
        if (p_ent->vx > 0) {
            p_ent->vx -= dec;
            if (p_ent->vx < 0) p_ent->vx = 0;
        } else if (p_ent->vx < 0) {
            p_ent->vx += dec;
            if (p_ent->vx > 0) p_ent->vx = 0;
        }
    }

    /* Jump (with 4-frame coyote time) */
    if (input_hit(KEY_A)) {
        if (p_ent->on_ground || coyote_timer <= 4) {
            /* Normal/coyote jump */
            p_ent->vy = phys->jump_vel;
            player_state.jumps_remaining = (u8)(phys->max_jumps - 1);
            p_ent->on_ground = 0;
            coyote_timer = 255; /* Consume coyote window */
            audio_play_sfx(SFX_JUMP);
        } else if (p_ent->on_wall && phys->can_wall_jump) {
            /* Wall jump */
            p_ent->vy = phys->wall_jump_vy;
            /* Kick away from wall */
            int wall_side = physics_check_wall(p_ent, -1) ? -1 : 1;
            p_ent->vx = (wall_side < 0) ? phys->wall_jump_vx : -phys->wall_jump_vx;
            p_ent->facing = (wall_side < 0) ? FACING_RIGHT : FACING_LEFT;
            player_state.jumps_remaining = (u8)(phys->max_jumps - 1);
            audio_play_sfx(SFX_WALL_JUMP);
        } else if (player_state.jumps_remaining > 0) {
            /* Double jump (Infiltrator) */
            p_ent->vy = (s16)(phys->jump_vel * 7 / 8);
            player_state.jumps_remaining--;
            audio_play_sfx(SFX_JUMP);
        }
    }

    /* Variable-height jump: cut velocity on button release */
    if (input_released(KEY_A) && p_ent->vy < phys->jump_cut) {
        p_ent->vy = phys->jump_cut;
    }

    /* Shooting (B button) */
    if (input_held(KEY_B) && player_state.shoot_cooldown == 0) {
        do_shoot();
        player_state.state = PSTATE_SHOOT;
    }

    /* Dash (R button, Infiltrator only) */
    int did_dash = 0;
    if (input_hit(KEY_R) && phys->can_dash &&
        player_state.dash_timer == 0 && player_state.dash_cooldown == 0) {
        player_state.dash_timer = phys->dash_frames;
        p_ent->vx = p_ent->facing == FACING_LEFT ? -phys->dash_speed : phys->dash_speed;
        p_ent->vy = 0;
        player_state.state = PSTATE_DASH;
        audio_play_sfx(SFX_DASH);
        did_dash = 1;
    }

    /* Abilities: L = cycle selection, R = activate selected */
    if (input_hit(KEY_L)) {
        /* Cycle to next unlocked ability */
        for (int n = 1; n <= 4; n++) {
            int next = (selected_ability + n) & 3;
            if (player_state.ability_unlocks & (1 << next)) {
                selected_ability = next;
                break;
            }
        }
    }
    if (input_hit(KEY_R) && !did_dash) {
        ability_activate(cls, selected_ability);
    }

    /* Drop through platform (DOWN on one-way platform) */
    if (input_held(KEY_DOWN) && p_ent->on_ground) {
        int foot_x = (int)(p_ent->x >> 8) + p_ent->width / 2;
        int foot_y = (int)(p_ent->y >> 8) + p_ent->height;
        if (collision_tile_at(foot_x, foot_y) == TILE_PLATFORM) {
            p_ent->y += FP8(2); /* Nudge past platform top */
            p_ent->vy = 64;     /* Small downward velocity */
            p_ent->on_ground = 0;
        }
    }

    /* Physics */
    physics_update(p_ent, phys);

    /* Screen shake from video */
    video_shake_update();

    /* Abilities update */
    ability_update();

    /* Projectiles updated by state_net_update — NOT here (avoid double-update) */
}

/* ---- Damage ---- */

void player_take_damage(int dmg, s16 kb_vx, s16 kb_vy) {
    if (!p_ent || player_state.invincible_timer > 0) return;
    if (player_state.state == PSTATE_DEAD) return;

    /* Diminishing returns defense: actual = dmg * 256 / (256 + def * 8)
     * At DEF=16, reduces damage by ~33%. At DEF=32, ~50%. At DEF=64, ~67%. */
    int def_factor = 256 + player_state.def * 8;
    int actual = dmg * 256 / def_factor;
    /* Data Shield (Technomancer ability): halve incoming damage */
    if (ability_is_data_shield_active()) {
        actual = actual / 2;
    }
    if (actual < 1) actual = 1;

    player_state.hp -= (s16)actual;
    if (player_state.hp <= 0) {
        player_state.hp = 0;
        player_state.state = PSTATE_DEAD;
        audio_play_sfx(SFX_PLAYER_DIE);
        video_shake(15, 3);
        return;
    }

    p_ent->vx = kb_vx;
    p_ent->vy = kb_vy;
    player_state.invincible_timer = 60;
    player_state.state = PSTATE_HIT;
    audio_play_sfx(SFX_PLAYER_HIT);
    video_shake(6, 2);
}

/* ---- XP / Level-up ---- */

int player_xp_to_next(void) {
    /* Linear: BASE_XP * level (20hr pacing with side contracts) */
    int lv = player_state.level;
    return BASE_XP * lv;
}

void player_add_xp(int amount) {
    /* Use int accumulator to prevent u16 overflow/wrap */
    int xp = (int)player_state.xp + amount;
    while (player_state.level < MAX_LEVEL) {
        int needed = player_xp_to_next();
        if (xp < needed) break;
        xp -= needed;
        /* Apply stat GAINS as deltas to preserve any shop upgrade bonuses */
        {
            int cls = (int)player_state.player_class;
            int old_lv = (int)player_state.level;
            player_state.level++;
            int new_lv = (int)player_state.level;
            s16 old_hp, old_atk, old_def, old_spd, old_lck;
            s16 new_hp, new_atk, new_def, new_spd, new_lck;
            player_get_base_stats(cls, old_lv, &old_hp, &old_atk, &old_def, &old_spd, &old_lck);
            player_get_base_stats(cls, new_lv, &new_hp, &new_atk, &new_def, &new_spd, &new_lck);
            player_state.max_hp = (s16)(player_state.max_hp + (new_hp  - old_hp));
            player_state.atk    = (s16)(player_state.atk    + (new_atk - old_atk));
            player_state.def    = (s16)(player_state.def    + (new_def - old_def));
            player_state.spd    = (s16)(player_state.spd    + (new_spd - old_spd));
            player_state.lck    = (s16)(player_state.lck    + (new_lck - old_lck));
        }
        /* 75% heal on level up — maintains endurance tension */
        player_state.hp = (s16)(player_state.max_hp * 3 / 4);
        if (player_state.hp < 1) player_state.hp = 1;
        check_ability_unlocks();
        hud_notify("LEVEL UP!", 90);
    }
    if (xp > 65535) xp = 65535;
    if (xp < 0) xp = 0;
    player_state.xp = (u16)xp;
}

/* ---- Render ---- */

void player_draw(s32 cam_x, s32 cam_y) {
    if (!p_ent || p_ent->oam_index == OAM_NONE) return;

    /* Invincibility flash */
    if (player_state.invincible_timer > 0 && (player_state.invincible_timer & 2)) {
        OBJ_ATTR* spr = sprite_get(p_ent->oam_index);
        if (spr) obj_hide(spr);
        return;
    }

    int cx = (int)(cam_x >> 8);
    int cy = (int)(cam_y >> 8);
    int sx = (int)(p_ent->x >> 8) - cx - 2;  /* Center 12px hitbox in 16px sprite */
    int sy = (int)(p_ent->y >> 8) - cy - 1;

    /* Select animation frame (12 frames: idle0-1, run0-3, jump, fall,
     * shoot0-1, wallslide, dash) */
    int frame;
    switch (player_state.state) {
    case PSTATE_RUN:
        frame = 2 + ((p_ent->anim_timer >> 2) & 3); /* 4-frame run cycle @ ~15fps */
        break;
    case PSTATE_JUMP:
        frame = 6;
        break;
    case PSTATE_FALL:
        frame = 7;
        break;
    case PSTATE_SHOOT:
        frame = 8 + ((p_ent->anim_timer >> 3) & 1); /* shoot0/shoot1 */
        break;
    case PSTATE_WALL_SLIDE:
        frame = 10;
        break;
    case PSTATE_DASH:
        frame = 11;
        break;
    default:
        frame = (p_ent->anim_timer >> 4) & 1; /* idle0/idle1 breathing @ ~4fps */
        break;
    }

    int tile_id = PLAYER_TILE_BASE + frame * 4;

    OBJ_ATTR* spr = sprite_get(p_ent->oam_index);
    if (!spr) return;

    u16 flip = p_ent->facing ? ATTR1_HFLIP : 0;  /* sprite faces RIGHT natively */

    obj_unhide(spr, ATTR0_REG);
    spr->attr0 = (u16)((sy & ATTR0_Y_MASK) | ATTR0_SQUARE | ATTR0_4BPP);
    spr->attr1 = (u16)((sx & ATTR1_X_MASK) | ATTR1_SIZE_16 | flip);
    spr->attr2 = (u16)(ATTR2_ID(tile_id) | ATTR2_PALBANK(PLAYER_PAL_BANK));

    /* Projectiles drawn by state_net_draw — NOT here (avoid double-draw) */
}
