#!/usr/bin/env python3
"""Ghost Protocol Audio Generator v5.

SFX  -- generated by sox with echo/overdrive/Hann-fade effects.
Music -- MOD tracker: 4-channel (melody, counter-melody, bass, percussion).

Composition approach: motif-based melodies with call-and-response,
pentatonic/minor scale consistency, syncopated drum patterns,
per-act musical identity, and boosted channel volumes.

GBA constraints:
  - 16 kHz mixer: Oct 2 periods (226-428) safe, Oct 3 (113-214) aliases
  - 4 MOD channels max, 31 instruments, 128 pattern order, 64 rows/pattern
  - WAV SFX: 8-bit unsigned, mono, 16000 Hz

File naming matches audio.c sfx_map / music_map.
"""

import math, os, struct, subprocess

MUSIC_DIR = "audio/music"
SFX_DIR   = "audio/sfx"

MOD_ROWS = 64
MOD_CHAN = 4

# Standard Amiga period table (3 octaves).
# Oct 2 (periods 226-428) all have step_size < 1.0 at 16 kHz -- safe.
# Oct 3 (periods 113-214) have step_size > 1.0 -- alias into garbage on GBA.
PERIODS = [
    856,808,762,720,678,640,604,570,538,508,480,453,   # Oct 1
    428,404,381,360,339,320,302,285,269,254,240,226,   # Oct 2
    214,202,190,180,170,160,151,143,135,127,120,113,   # Oct 3 (unsafe)
]
C1,Cs1,D1,Ds1,E1,F1,Fs1,G1,Gs1,A1,As1,B1 = range(12)
C2,Cs2,D2,Ds2,E2,F2,Fs2,G2,Gs2,A2,As2,B2 = range(12, 24)
# C3-B3 alias to Oct 2 indices -- GBA 16 kHz cannot play Oct 3
C3,Cs3,D3,Ds3,E3,F3,Fs3,G3,Gs3,A3,As3,B3 = range(12, 24)
REST = -1

VC = 0x0C   # volume effect command (Cxx)
FC = 0x0F   # speed/BPM effect command


# -- Scale helpers -------------------------------------------------------

def minor_scale(root):
    """Return note indices for natural minor scale in Oct 1 and Oct 2."""
    intervals = [0, 2, 3, 5, 7, 8, 10]
    notes = []
    for octave_base in [0, 12]:
        for iv in intervals:
            idx = root + octave_base + iv
            if 0 <= idx < 24:
                notes.append(idx)
    return notes

def pentatonic_minor(root):
    """Return pentatonic minor scale notes across Oct 1 and Oct 2."""
    intervals = [0, 3, 5, 7, 10]
    notes = []
    for octave_base in [0, 12]:
        for iv in intervals:
            idx = root + octave_base + iv
            if 0 <= idx < 24:
                notes.append(idx)
    return notes


# -- SFX via sox ---------------------------------------------------------

def sox_wav(outpath, *args):
    """Run sox to generate a 16384 Hz / 8-bit unsigned / mono WAV."""
    cmd = ['sox', '-n',
           '-r', '16384', '-b', '8', '-e', 'unsigned-integer', '-c', '1',
           outpath] + [str(a) for a in args]
    subprocess.run(cmd, check=True, capture_output=True)


def make_sfx():
    d = SFX_DIR

    # -- Weapon-type fire sounds (01-08) --
    # 01 -- Pulse Pistol: clean mid-freq chirp
    sox_wav(f'{d}/01_shoot.wav',
        'synth','0.11','sine','900:350',
        'echo','0.5','0.3','40','0.4',
        'fade','h','0','0.18','0.04', 'gain','-4')

    # 02 -- Charge Shot: long rising whine with harmonic buildup
    sox_wav(f'{d}/02_shoot_charge.wav',
        'synth','0.45','sine','280:1350',
        'echo','0.5','0.3','80','0.4',
        'fade','h','0.03','0.52','0.05', 'gain','-3')

    # 03 -- Rapid Fire: very short blip
    sox_wav(f'{d}/03_shoot_rapid.wav',
        'synth','0.06','sine','1100:650',
        'fade','h','0','0.06','0.012', 'gain','-4')

    # 04 -- enemy hit: thud with overdrive harmonics
    sox_wav(f'{d}/04_enemy_hit.wav',
        'synth','0.10','sine','450:90',
        'overdrive','12','15',
        'fade','h','0','0.10','0.04', 'gain','-5')

    # 05 -- enemy die: descending sweep + echo
    sox_wav(f'{d}/05_enemy_die.wav',
        'synth','0.28','sine','580:50',
        'echo','0.5','0.4','70','0.4',
        'fade','h','0','0.36','0.08', 'gain','-3')

    # 06 -- player hit: heavy low impact
    sox_wav(f'{d}/06_player_hit.wav',
        'synth','0.15','sine','160:55',
        'overdrive','18','22',
        'fade','h','0','0.15','0.05', 'gain','-3')

    # 07 -- player die: long falling sweep + echo
    sox_wav(f'{d}/07_player_die.wav',
        'synth','0.55','sine','320:28',
        'echo','0.5','0.4','120','0.5',
        'fade','h','0','0.65','0.10', 'gain','-3')

    # 08 -- jump: quick upward chirp
    sox_wav(f'{d}/08_jump.wav',
        'synth','0.09','sine','180:520',
        'fade','h','0','0.09','0.02', 'gain','-6')

    # 09 -- wall jump: slightly higher pitch
    sox_wav(f'{d}/09_wall_jump.wav',
        'synth','0.09','sine','260:680',
        'fade','h','0','0.09','0.02', 'gain','-6')

    # 10 -- dash: whoosh downward
    sox_wav(f'{d}/10_dash.wav',
        'synth','0.12','sine','800:200',
        'fade','h','0','0.12','0.03', 'gain','-3')

    # 11 -- item pickup: bright chime + echo
    sox_wav(f'{d}/11_pickup.wav',
        'synth','0.22','sine','880',
        'echo','0.5','0.4','65','0.3',
        'fade','h','0.01','0.30','0.10', 'gain','-3')

    # 12 -- menu select: clean tone
    sox_wav(f'{d}/12_menu_select.wav',
        'synth','0.08','sine','880',
        'fade','h','0','0.10','0.03', 'gain','-6')

    # 13 -- menu back: lower tone
    sox_wav(f'{d}/13_menu_back.wav',
        'synth','0.08','sine','660',
        'fade','h','0','0.10','0.03', 'gain','-6')

    # 14 -- ability: power chord sweep + echo
    sox_wav(f'{d}/14_ability.wav',
        'synth','0.30','sine','440:660',
        'echo','0.4','0.3','85','0.4',
        'fade','h','0.01','0.38','0.08', 'gain','-3')

    # 15 -- boss roar: low rising rumble + long echo
    sox_wav(f'{d}/15_boss_roar.wav',
        'synth','0.50','sine','75:180',
        'echo','0.5','0.4','140','0.5',
        'fade','h','0.04','0.60','0.10', 'gain','-3')

    # 16 -- level done: ascending sweep + echo
    sox_wav(f'{d}/16_level_done.wav',
        'synth','0.40','sine','523:1047',
        'echo','0.4','0.3','75','0.4',
        'fade','h','0.01','0.50','0.10', 'gain','-3')

    # 17 -- save: gentle confirmation tone + echo
    sox_wav(f'{d}/17_save.wav',
        'synth','0.20','sine','440',
        'echo','0.4','0.3','55','0.3',
        'fade','h','0','0.28','0.08', 'gain','-6')

    # 18 -- transition: mid sweep + echo
    sox_wav(f'{d}/18_transition.wav',
        'synth','0.30','sine','280:580',
        'echo','0.4','0.3','75','0.4',
        'fade','h','0.02','0.38','0.08', 'gain','-3')

    # 19 -- wall slide: slight detuning creates beating
    sox_wav(f'{d}/19_wall_slide.wav',
        'synth','0.15','sine','158:162',
        'fade','h','0.02','0.15','0.04', 'gain','-6')

    # 20 -- heavy land: deep thud with overdrive
    sox_wav(f'{d}/20_land_heavy.wav',
        'synth','0.14','sine','90:35',
        'overdrive','14','18',
        'fade','h','0','0.14','0.05', 'gain','-3')

    # 21 -- double jump: two-note feel via fast sweep
    sox_wav(f'{d}/21_double_jump.wav',
        'synth','0.12','sine','240:630',
        'fade','h','0','0.12','0.02', 'gain','-6')

    # 22 -- beam hum: sustained with slow beating + echo
    sox_wav(f'{d}/22_beam_hum.wav',
        'synth','0.35','sine','220:226',
        'echo','0.5','0.4','55','0.5',
        'fade','h','0.04','0.40','0.07', 'gain','-3')

    # 23 -- spread burst: rising burst + short echo
    sox_wav(f'{d}/23_spread_burst.wav',
        'synth','0.12','sine','580:880',
        'echo','0.4','0.3','35','0.4',
        'fade','h','0','0.18','0.04', 'gain','-3')

    # 24 -- charger whine: long rising tone
    sox_wav(f'{d}/24_charger_whine.wav',
        'synth','0.40','sine','300:1200',
        'fade','h','0.03','0.40','0.05', 'gain','-3')

    # 25 -- boss phase: dramatic sweep + long echo
    sox_wav(f'{d}/25_boss_phase.wav',
        'synth','0.50','sine','140:380',
        'echo','0.5','0.4','115','0.5',
        'fade','h','0.01','0.60','0.10', 'gain','-3')

    # 26 -- boss explode: overdrive low sweep + echo
    sox_wav(f'{d}/26_boss_explode.wav',
        'synth','0.50','sine','55:190',
        'overdrive','22','28',
        'echo','0.5','0.4','95','0.5',
        'fade','h','0','0.60','0.10', 'gain','-3')

    # 27 -- tesla zap: high-freq burst with overdrive
    sox_wav(f'{d}/27_tesla_zap.wav',
        'synth','0.09','sine','1350:750',
        'overdrive','14','18',
        'fade','h','0','0.09','0.025', 'gain','-3')

    # 28 -- craft success: rising sweep + echo
    sox_wav(f'{d}/28_craft_success.wav',
        'synth','0.35','sine','392:784',
        'echo','0.4','0.3','65','0.4',
        'fade','h','0.01','0.43','0.10', 'gain','-3')

    # 29 -- evolve: wide triumphant sweep + echo
    sox_wav(f'{d}/29_evolve.wav',
        'synth','0.60','sine','196:784',
        'echo','0.4','0.3','95','0.4',
        'fade','h','0.02','0.72','0.12', 'gain','-3')

    # 30 -- achievement: bright ascending sweep + echo
    sox_wav(f'{d}/30_achievement.wav',
        'synth','0.40','sine','523:1047',
        'echo','0.4','0.3','75','0.5',
        'fade','h','0.01','0.50','0.12', 'gain','-3')

    # 31 -- beam fire: sustained low hum (Beam weapon)
    sox_wav(f'{d}/31_beam_fire.wav',
        'synth','0.30','sine','180:200',
        'echo','0.6','0.5','40','0.5',
        'fade','h','0.02','0.35','0.05', 'gain','-4')

    # 32 -- laser crack: sharp high-freq snap (Laser weapon)
    sox_wav(f'{d}/32_laser_crack.wav',
        'synth','0.06','sine','2000:800',
        'overdrive','10','12',
        'fade','h','0','0.06','0.01', 'gain','-3')

    # 33 -- nova whoosh: expanding low sweep (Nova weapon)
    sox_wav(f'{d}/33_nova_whoosh.wav',
        'synth','0.25','sine','120:450',
        'echo','0.5','0.4','60','0.4',
        'fade','h','0.01','0.30','0.06', 'gain','-3')

    # 34 -- homing whine: rising engine whistle (Homing weapon)
    sox_wav(f'{d}/34_homing_whine.wav',
        'synth','0.20','sine','400:900',
        'fade','h','0.02','0.20','0.04', 'gain','-5')

    # 35 -- mechanical enemy hit: metallic clank
    sox_wav(f'{d}/35_enemy_hit_mech.wav',
        'synth','0.08','sine','800:200',
        'overdrive','20','25',
        'fade','h','0','0.08','0.02', 'gain','-4')

    # 36 -- mechanical enemy die: grinding halt
    sox_wav(f'{d}/36_enemy_die_mech.wav',
        'synth','0.30','sine','400:40',
        'overdrive','15','20',
        'echo','0.4','0.3','50','0.4',
        'fade','h','0','0.38','0.08', 'gain','-3')

    # 37 -- digital enemy hit: glitch stutter
    sox_wav(f'{d}/37_enemy_hit_digi.wav',
        'synth','0.06','sine','1200:400',
        'echo','0.3','0.2','15','0.3',
        'fade','h','0','0.08','0.02', 'gain','-4')

    # 38 -- digital enemy die: data dissolution
    sox_wav(f'{d}/38_enemy_die_digi.wav',
        'synth','0.25','sine','900:100',
        'echo','0.5','0.4','30','0.5',
        'fade','h','0','0.32','0.07', 'gain','-3')


# -- MOD tracker music ---------------------------------------------------
# 4 channels: ch0=melody, ch1=counter-melody/response, ch2=bass, ch3=drums
# Instruments: 1=melody(sine), 2=bass(triangle), 3=counter(organ),
#              4=kick(noise low), 5=snare(noise high), 6=hihat(noise very high)

def sine32():
    """32-sample looping sine wave, 8-bit signed PCM."""
    return bytes((int(118 * math.sin(2 * math.pi * i / 32)) & 0xFF)
                 for i in range(32))

def triangle32():
    """32-sample looping triangle wave."""
    data = bytearray(32)
    for i in range(32):
        if i < 8:
            data[i] = (i * 16) & 0xFF
        elif i < 24:
            data[i] = (255 - (i - 8) * 16) & 0xFF
        else:
            data[i] = ((i - 24) * 16 - 128) & 0xFF
    return bytes(data)

def organ32():
    """32-sample organ-like wave (fundamental + 2nd + 3rd harmonic)."""
    data = bytearray(32)
    for i in range(32):
        val = int(80 * math.sin(2 * math.pi * i / 32)
                + 35 * math.sin(4 * math.pi * i / 32)
                + 15 * math.sin(6 * math.pi * i / 32))
        data[i] = val & 0xFF
    return bytes(data)

def noise32():
    """32-sample pseudo-noise for percussion."""
    import hashlib
    h = hashlib.sha256(b'ghost_protocol_drums').digest()
    return bytes(h[:32])


def smp_hdr(name, data, vol=56):
    words = len(data) // 2
    return struct.pack('>22sHBBHH',
                       name.encode()[:22].ljust(22, b'\0'),
                       words, 0, vol, 0, words)  # loop_start=0, loop_len=words


def note_cell(note_idx, smp, effect=0, param=0):
    period = PERIODS[note_idx] if 0 <= note_idx < len(PERIODS) else 0
    b1 = ((smp >> 4) << 4) | ((period >> 8) & 0xF)
    b2 = period & 0xFF
    b3 = ((smp & 0xF) << 4) | (effect & 0xF)
    b4 = param & 0xFF
    return bytes([b1, b2, b3, b4])


def build_pattern(cells):
    """cells: [(row, ch, note_idx, smp, effect, param), ...]"""
    pat = bytearray(MOD_ROWS * MOD_CHAN * 4)
    for row, ch, n, smp, fx, param in cells:
        if 0 <= row < MOD_ROWS and 0 <= ch < MOD_CHAN:
            off = (row * MOD_CHAN + ch) * 4
            pat[off:off+4] = note_cell(n, smp, fx, param)
    return bytes(pat)


def build_mod(title, patterns, order, speed=6, bpm=90):
    """Assemble a MOD file with 6 instruments (melody, bass, organ, kick, snare, hihat)."""
    sd_mel   = sine32()
    sd_bass  = triangle32()
    sd_organ = organ32()
    sd_kick  = noise32()
    sd_snare = noise32()
    sd_hihat = noise32()

    title_b = title.encode()[:20].ljust(20, b'\0')
    # Instrument headers: boosted volumes for music prominence
    hdrs  = smp_hdr('Melody',   sd_mel,   64)   # instrument 1
    hdrs += smp_hdr('Bass',     sd_bass,  58)   # instrument 2
    hdrs += smp_hdr('Counter',  sd_organ, 56)   # instrument 3
    hdrs += smp_hdr('Kick',     sd_kick,  52)   # instrument 4
    hdrs += smp_hdr('Snare',    sd_snare, 48)   # instrument 5
    hdrs += smp_hdr('HiHat',    sd_hihat, 40)   # instrument 6
    for _ in range(25):
        hdrs += struct.pack('>22sHBBHH', b'\0'*22, 0, 0, 0, 0, 0)

    # Inject BPM+speed into row 0 of first pattern
    if patterns:
        p0 = bytearray(patterns[0])
        # ch0 row0: BPM
        p0[0]=0x00; p0[1]=0x00; p0[2]=0x0F; p0[3]=bpm & 0xFF
        # ch1 row0: speed
        p0[4]=0x00; p0[5]=0x00; p0[6]=0x0F; p0[7]=speed & 0x1F
        patterns[0] = bytes(p0)

    n_pat = max(order) + 1 if order else 1
    mod   = title_b + hdrs
    mod  += struct.pack('BB', len(order), 0)
    mod  += bytes(order + [0] * (128 - len(order)))
    mod  += b'M.K.'
    for i in range(n_pat):
        mod += patterns[i] if i < len(patterns) else bytes(MOD_ROWS * MOD_CHAN * 4)
    # Sample data
    mod += sd_mel + sd_bass + sd_organ + sd_kick + sd_snare + sd_hihat
    return mod


# Instrument numbers
S = 1   # melody (sine)
B = 2   # bass (triangle)
O = 3   # counter-melody (organ)
K = 4   # kick drum
SN = 5  # snare
HH = 6  # hihat

def n(row, ch, note, smp, vol=48):
    """Convenience: returns a pattern cell tuple with volume effect."""
    return (row, ch, note, smp, VC, vol)


# -- Drum pattern helpers ------------------------------------------------
# Drums use very low note indices (Oct 1) -- the noise sample sounds
# the same regardless, but lower periods give lower-pitched noise
# approximation through the sample loop.

def drums_sparse(cells, vol_k=42, vol_s=38, vol_h=34):
    """Sparse ambient drums: kick on 0,32; snare on 16,48; hihat on 8,24,40,56."""
    cells.append(n(0,  3, C1, K, vol_k))
    cells.append(n(16, 3, E1, SN, vol_s))
    cells.append(n(32, 3, C1, K, vol_k))
    cells.append(n(48, 3, E1, SN, vol_s))
    for r in [8, 24, 40, 56]:
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_rock(cells, vol_k=45, vol_s=42, vol_h=36):
    """Standard rock pattern with off-beat hihats."""
    for r in [0, 24, 32, 56]:
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [16, 48]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in range(4, 60, 8):
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_driving(cells, vol_k=48, vol_s=44, vol_h=38):
    """Driving pattern: kick every 8, snare 16/48, hi-hat rolls."""
    for r in range(0, 64, 8):
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [16, 48]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in range(2, 60, 4):
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_syncopated(cells, vol_k=46, vol_s=42, vol_h=36):
    """Syncopated: kick off-beats, snare on-beats, hihat 16ths."""
    for r in [0, 6, 16, 22, 32, 38, 48, 54]:
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [12, 28, 44, 60]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in range(2, 60, 4):
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_military(cells, vol_k=48, vol_s=46, vol_h=40):
    """Military march: double snare hits, heavy kick."""
    for r in [0, 16, 32, 48]:
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [8, 10, 24, 26, 40, 42, 56, 58]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in range(4, 60, 8):
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_boss(cells, vol_k=50, vol_s=46, vol_h=40):
    """Boss fight: aggressive double-time kick, rapid snare fills."""
    for r in range(0, 64, 4):
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [8, 24, 40, 56]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in [6, 14, 22, 30, 38, 46, 54, 62]:
        cells.append(n(r, 3, E1, SN, vol_s - 6))
    for r in range(2, 60, 4):
        cells.append(n(r, 3, G2, HH, vol_h))

def drums_glitch(cells, vol_k=46, vol_s=44, vol_h=38):
    """Glitchy erratic: irregular placement, volume variation."""
    for r in [0, 5, 14, 18, 27, 32, 37, 48, 53]:
        cells.append(n(r, 3, C1, K, vol_k - (r % 7)))
    for r in [3, 10, 22, 30, 42, 50, 58]:
        cells.append(n(r, 3, E1, SN, vol_s - (r % 5)))
    for r in range(2, 60, 3):
        cells.append(n(r, 3, G2, HH, vol_h - (r % 8)))

def drums_epic(cells, vol_k=50, vol_s=48, vol_h=42):
    """Epic layered: building intensity with rolls."""
    for r in range(0, 64, 4):
        cells.append(n(r, 3, C1, K, vol_k))
    for r in [8, 12, 24, 28, 40, 44, 56, 60]:
        cells.append(n(r, 3, E1, SN, vol_s))
    for r in range(2, 62, 2):
        cells.append(n(r, 3, G2, HH, vol_h - 4 + (r % 8)))


# -- Motif-based melody composition helpers ------------------------------

def motif_repeat(motif, transpose=0, vol_adj=0):
    """Transpose a motif (list of (row_offset, note, vol))."""
    result = []
    for roff, nt, vol in motif:
        new_note = nt + transpose if nt >= 0 else nt
        # Clamp to safe range (0-23, Oct 1-2 only)
        if new_note >= 0:
            new_note = max(0, min(23, new_note))
        result.append((roff, new_note, vol + vol_adj))
    return result

def place_motif(cells, motif, start_row, ch, smp):
    """Place a motif starting at start_row on given channel."""
    for roff, nt, vol in motif:
        row = start_row + roff
        if 0 < row < 64 and nt >= 0:
            cells.append(n(row, ch, nt, smp, max(20, min(64, vol))))


# -- Track builders (16 original tracks) ---------------------------------

# Volume ranges (boosted ~30%):
# Melody:  C40-C50 (was C28-C36)
# Counter: C36-C44
# Bass:    C38-C45
# Drums:   C42-C50

def track_title():
    """Title screen: atmospheric C minor, mysterious arpeggios."""
    # Motif A: descending minor 3rds
    motifA = [(0, C2, 48), (4, Ds2, 44), (8, G2, 48), (12, C2, 42)]
    # Motif B: ascending resolution
    motifB = [(0, G2, 46), (4, As2, 50), (8, C2, 44), (12, Ds2, 48)]

    pats = []
    for pi in range(4):
        cells = []
        # Melody: motif A then B with variation
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motif_repeat(motifB, 0 if pi % 2 == 0 else 2), 20, 0, S)
        place_motif(cells, motif_repeat(motifA, pi, 2), 36, 0, S)
        place_motif(cells, motifB, 52, 0, S)
        # Counter melody: sparse response on ch1
        if pi >= 1:
            place_motif(cells, [(0, Ds2, 40), (8, G2, 38), (16, As2, 42)], 12, 1, O)
            place_motif(cells, [(0, C2, 38), (8, Ds2, 40)], 44, 1, O)
        # Bass: whole notes
        cells.append(n(4,  2, C1, B, 42))
        cells.append(n(20, 2, As1, B, 40))
        cells.append(n(36, 2, G1, B, 40))
        cells.append(n(52, 2, F1, B, 40))
        # Sparse drums on later patterns
        if pi >= 2:
            drums_sparse(cells, 36, 32, 28)
        pats.append(build_pattern(cells))
    return build_mod('Ghost Protocol', pats, [0,1,2,3,0,1,2,3], speed=7, bpm=75)


def track_terminal():
    """Terminal hub: chill ambient, D dorian, 85 BPM."""
    # Dreamy pad-like melody
    motifA = [(0, D2, 44), (6, F2, 42), (12, A2, 46), (18, G2, 44)]
    motifB = [(0, E2, 42), (6, G2, 44), (12, A2, 46), (18, F2, 42)]

    pats = []
    for pi in range(3):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 28, 0, S)
        # Counter: melodic flourish
        cells.append(n(8,  1, A2, O, 38))
        cells.append(n(16, 1, G2, O, 36))
        cells.append(n(36, 1, F2, O, 38))
        cells.append(n(44, 1, D2, O, 36))
        if pi == 2:
            cells.append(n(52, 1, A2, O, 40))
            cells.append(n(56, 1, B2, O, 42))
        # Bass: slow whole notes
        cells.append(n(4,  2, D1, B, 42))
        cells.append(n(20, 2, A1, B, 40))
        cells.append(n(36, 2, G1, B, 40))
        cells.append(n(52, 2, F1, B, 40))
        # Very gentle percussion
        if pi >= 1:
            for r in [0, 32]:
                cells.append(n(r, 3, C1, K, 30))
            for r in [16, 48]:
                cells.append(n(r, 3, G2, HH, 24))
        pats.append(build_pattern(cells))
    return build_mod('Terminal', pats, [0,1,2,1,0,1,2], speed=7, bpm=85)


def track_act1():
    """Act 1 - The Glitch: A minor, 110 BPM, uneasy ambient, sparse."""
    scale = [A1, C2, D2, E2, G2, A2, C2, E2]  # A minor pentatonic
    # Motif: hesitant ascending
    motifA = [(0, A2, 46), (6, C2, 44), (10, E2, 48), (16, D2, 44)]
    motifB = [(0, E2, 46), (4, D2, 44), (8, C2, 46), (14, A1, 42)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 24, 0, S)
        place_motif(cells, motif_repeat(motifA, 2 if pi >= 2 else 0), 40, 0, S)
        # Response on ch1
        if pi % 2 == 1:
            place_motif(cells, [(0, E2, 40), (6, G2, 38), (12, A2, 42)], 16, 1, O)
        if pi >= 2:
            place_motif(cells, [(0, C2, 38), (6, D2, 40), (12, E2, 42)], 48, 1, O)
        # Bass
        cells.append(n(4,  2, A1, B, 44))
        cells.append(n(20, 2, E1, B, 42))
        cells.append(n(36, 2, G1, B, 42))
        cells.append(n(52, 2, D1, B, 42))
        # Drums: sparse
        drums_sparse(cells, 38, 34, 30)
        pats.append(build_pattern(cells))
    return build_mod('Act I Glitch', pats, [0,1,0,1,2,3,2,3], speed=6, bpm=110)


def track_act2():
    """Act 2 - Traceback: C minor, 120 BPM, methodical pulsing bass."""
    motifA = [(0, C2, 48), (4, Ds2, 46), (8, G2, 50), (12, F2, 46), (16, Ds2, 44)]
    motifB = [(0, G2, 48), (4, As2, 50), (8, G2, 46), (12, F2, 44), (16, Ds2, 48)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 28, 0, S)
        if pi >= 2:
            place_motif(cells, motif_repeat(motifA, 3, 2), 48, 0, S)
        # Counter-melody: call and response
        place_motif(cells, [(0, Ds2, 40), (6, F2, 38), (12, G2, 42)], 16, 1, O)
        if pi >= 1:
            place_motif(cells, [(0, As2, 40), (6, G2, 38), (12, F2, 42)], 40, 1, O)
        # Pulsing bass: 8th notes
        for r in range(4, 60, 8):
            bn = [C1, C1, G1, G1, As1, As1, F1, F1][(r-4)//8 % 8]
            cells.append(n(r, 2, bn, B, 44))
        drums_rock(cells, 44, 40, 34)
        pats.append(build_pattern(cells))
    return build_mod('Act II Trace', pats, [0,1,2,3,0,1,2,3], speed=6, bpm=120)


def track_act3():
    """Act 3 - Deep Packet: D minor, 128 BPM, dark driving industrial."""
    motifA = [(0, D2, 50), (3, F2, 48), (6, A2, 52), (10, G2, 48), (14, F2, 46)]
    motifB = [(0, A2, 50), (4, G2, 48), (8, F2, 52), (12, E2, 48), (16, D2, 50)]

    pats = []
    for pi in range(5):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 22, 0, S)
        # Variation in later patterns
        if pi >= 2:
            place_motif(cells, motif_repeat(motifA, -2, 2), 42, 0, S)
        else:
            place_motif(cells, motifA, 42, 0, S)
        # Response
        place_motif(cells, [(0, F2, 42), (4, A2, 40), (8, D2, 44)], 12, 1, O)
        if pi >= 3:
            place_motif(cells, [(0, G2, 44), (4, A2, 42), (8, As2, 46)], 34, 1, O)
        # Driving bass
        for r in range(4, 60, 4):
            bn = [D1, D1, A1, A1, G1, G1, F1, F1, D1, D1, C1, C1, As1, As1, A1]
            cells.append(n(r, 2, bn[min((r-4)//4, len(bn)-1)], B, 44))
        drums_driving(cells, 46, 42, 36)
        pats.append(build_pattern(cells))
    return build_mod('Act III Deep', pats, [0,1,2,3,4,0,1,2,3,4], speed=5, bpm=128)


def track_act4():
    """Act 4 - Zero Day: E minor, 135 BPM, aggressive military percussion."""
    motifA = [(0, E2, 52), (3, G2, 50), (6, B2, 54), (9, A2, 50), (12, G2, 48)]
    motifB = [(0, B2, 52), (3, A2, 50), (6, G2, 54), (9, Fs2, 50), (12, E2, 52)]
    # Tension motif: chromatic ascent
    motifC = [(0, E2, 50), (3, F2, 52), (6, Fs2, 54), (9, G2, 56), (12, Gs2, 58)]

    pats = []
    for pi in range(5):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        if pi < 3:
            place_motif(cells, motifB, 20, 0, S)
        else:
            place_motif(cells, motifC, 20, 0, S)
        place_motif(cells, motif_repeat(motifA, 2 if pi >= 3 else 0), 38, 0, S)
        # Counter: military call
        place_motif(cells, [(0, G2, 44), (3, A2, 42), (6, B2, 46)], 14, 1, O)
        place_motif(cells, [(0, E2, 42), (4, Fs2, 44), (8, G2, 46)], 50, 1, O)
        # Bass
        cells.append(n(4,  2, E1, B, 44))
        cells.append(n(16, 2, B1, B, 44))
        cells.append(n(28, 2, A1, B, 42))
        cells.append(n(40, 2, G1, B, 42))
        cells.append(n(52, 2, D1, B, 44))
        drums_military(cells, 48, 44, 38)
        pats.append(build_pattern(cells))
    return build_mod('Act IV Zero', pats, [0,1,2,3,4,0,1,2,3,4], speed=5, bpm=135)


def track_act5():
    """Act 5 - Ghost Protocol: F# minor, 140 BPM, intense glitchy erratic."""
    motifA = [(0, Fs2, 52), (3, A2, 50), (5, Cs2, 54), (8, B2, 50), (12, A2, 48)]
    motifB = [(0, Cs2, 54), (2, D2, 52), (4, Cs2, 50), (7, B2, 54), (10, A2, 50)]
    # Glitch motif: rapid alternation
    motifG = [(0, Fs2, 56), (2, A2, 52), (4, Fs2, 56), (6, Cs2, 58),
              (8, B2, 54), (10, A2, 56), (12, Gs2, 58)]

    pats = []
    for pi in range(6):
        cells = []
        if pi < 3:
            place_motif(cells, motifA, 4, 0, S)
            place_motif(cells, motifB, 20, 0, S)
        else:
            place_motif(cells, motifG, 4, 0, S)
            place_motif(cells, motif_repeat(motifG, -2, -2), 20, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 3), 38, 0, S)
        # Counter: erratic response
        if pi % 2 == 0:
            place_motif(cells, [(0, A2, 44), (3, B2, 42), (5, Cs2, 46)], 12, 1, O)
        else:
            place_motif(cells, [(0, Cs2, 46), (2, B2, 44), (5, A2, 42)], 30, 1, O)
        place_motif(cells, [(0, Fs2, 44), (4, E2, 42)], 52, 1, O)
        # Bass
        cells.append(n(4,  2, Fs1, B, 44))
        cells.append(n(16, 2, Cs1, B, 44))
        cells.append(n(28, 2, D1, B, 42))
        cells.append(n(40, 2, A1, B, 42))
        cells.append(n(52, 2, E1, B, 44))
        drums_glitch(cells, 46, 42, 36)
        pats.append(build_pattern(cells))
    return build_mod('Act V Ghost', pats, [0,1,2,3,4,5,0,1,2,3,4,5], speed=4, bpm=140)


def track_act6():
    """Act 6 - Trace Route: B minor, 145 BPM, epic layered building."""
    motifA = [(0, B2, 54), (3, D2, 50), (6, Fs2, 54), (9, A2, 56), (12, B2, 58)]
    motifB = [(0, Fs2, 52), (3, E2, 50), (6, D2, 54), (9, Cs2, 52), (12, B2, 56)]
    # Climax motif: wide ascending
    motifC = [(0, B2, 56), (2, Cs2, 54), (4, D2, 56), (6, E2, 58),
              (8, Fs2, 60), (10, G2, 58), (12, A2, 60), (14, B2, 62)]

    pats = []
    for pi in range(6):
        cells = []
        if pi < 4:
            place_motif(cells, motifA, 4, 0, S)
            place_motif(cells, motifB, 22, 0, S)
        else:
            place_motif(cells, motifC, 4, 0, S)
            place_motif(cells, motif_repeat(motifC, -2), 22, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 4, pi), 40, 0, S)
        # Counter: layered response building with pattern
        place_motif(cells, [(0, D2, 44), (4, Fs2, 42), (8, A2, 46)], 14, 1, O)
        if pi >= 2:
            place_motif(cells, [(0, E2, 44), (3, Fs2, 46), (6, G2, 48)], 34, 1, O)
        if pi >= 4:
            place_motif(cells, [(0, A2, 48), (2, B2, 50), (4, Cs2, 52)], 52, 1, O)
        # Bass
        cells.append(n(4,  2, B1, B, 46))
        cells.append(n(16, 2, Fs1, B, 44))
        cells.append(n(28, 2, G1, B, 44))
        cells.append(n(40, 2, A1, B, 44))
        cells.append(n(52, 2, E1, B, 46))
        drums_epic(cells, 48, 46, 40)
        pats.append(build_pattern(cells))
    return build_mod('Act VI Trace', pats, [0,1,2,3,4,5,0,1,2,3,4,5], speed=4, bpm=145)


# -- Boss tracks: 6 unique bosses, each with own musical identity --------

def track_boss_microslop():
    """Boss: Microslop (Act 1) -- C phrygian, menacing corporate."""
    motifA = [(0, C2, 56), (3, Cs2, 52), (6, Ds2, 56), (9, F2, 60), (12, G2, 58)]
    motifB = [(0, G2, 58), (3, F2, 54), (6, Ds2, 56), (9, Cs2, 54), (12, C2, 58)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 20, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 3, pi), 36, 0, S)
        # Response
        place_motif(cells, [(0, Ds2, 46), (4, F2, 44), (8, G2, 48)], 12, 1, O)
        place_motif(cells, [(0, C2, 44), (4, As1, 46)], 46, 1, O)
        # Bass
        cells.append(n(4,  2, C1, B, 46))
        cells.append(n(16, 2, As1, B, 44))
        cells.append(n(32, 2, G1, B, 44))
        cells.append(n(48, 2, F1, B, 44))
        drums_boss(cells, 48, 44, 38)
        pats.append(build_pattern(cells))
    return build_mod('Boss Microslop', pats, [0,1,2,3,0,1,2,3], speed=4, bpm=132)


def track_boss_gogol():
    """Boss: Gogol (Act 2) -- D minor, systematic hunter."""
    motifA = [(0, D2, 56), (3, F2, 54), (6, A2, 58), (9, G2, 54), (12, F2, 56)]
    motifB = [(0, A2, 58), (3, G2, 56), (6, F2, 58), (9, E2, 56), (12, D2, 58)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 20, 0, S)
        place_motif(cells, motif_repeat(motifA, -1 if pi >= 2 else 0, pi), 38, 0, S)
        # Counter
        place_motif(cells, [(0, F2, 44), (4, G2, 42), (8, A2, 46)], 14, 1, O)
        place_motif(cells, [(0, D2, 44), (6, E2, 42)], 48, 1, O)
        # Bass
        cells.append(n(4,  2, D1, B, 46))
        cells.append(n(16, 2, A1, B, 44))
        cells.append(n(32, 2, G1, B, 44))
        cells.append(n(48, 2, F1, B, 44))
        drums_boss(cells, 48, 44, 38)
        pats.append(build_pattern(cells))
    return build_mod('Boss Gogol', pats, [0,1,2,3,0,1,2,3], speed=4, bpm=134)


def track_boss_amazomb():
    """Boss: Amazomb (Act 3) -- F minor, relentless machine."""
    motifA = [(0, F2, 58), (3, Gs2, 54), (6, C2, 58), (9, As2, 56)]
    motifB = [(0, C2, 56), (3, As1, 54), (6, Gs1, 58), (9, F1, 60)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motif_repeat(motifA, 2), 18, 0, S)
        place_motif(cells, motifB, 32, 0, S)
        place_motif(cells, motif_repeat(motifA, pi), 48, 0, S)
        # Counter
        place_motif(cells, [(0, Gs2, 44), (4, As2, 42), (8, C2, 46)], 12, 1, O)
        place_motif(cells, [(0, F2, 42), (6, Ds2, 44)], 40, 1, O)
        # Bass
        cells.append(n(4,  2, F1, B, 46))
        cells.append(n(16, 2, C1, B, 46))
        cells.append(n(32, 2, Gs1, B, 44))
        cells.append(n(48, 2, As1, B, 44))
        drums_boss(cells, 50, 46, 40)
        pats.append(build_pattern(cells))
    return build_mod('Boss Amazomb', pats, [0,1,2,3,0,1,2,3], speed=4, bpm=136)


def track_boss_crapple():
    """Boss: Crapple (Act 4) -- G minor, elegant menace."""
    motifA = [(0, G2, 58), (3, As2, 54), (6, D2, 58), (10, C2, 54), (14, As1, 56)]
    motifB = [(0, D2, 56), (4, F2, 58), (8, G2, 60), (12, As2, 58)]

    pats = []
    for pi in range(4):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 22, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 3, pi), 38, 0, S)
        # Counter
        place_motif(cells, [(0, As2, 44), (4, C2, 42), (8, D2, 46)], 14, 1, O)
        place_motif(cells, [(0, G2, 44), (6, F2, 42)], 50, 1, O)
        # Bass
        cells.append(n(4,  2, G1, B, 46))
        cells.append(n(16, 2, D1, B, 44))
        cells.append(n(32, 2, C1, B, 44))
        cells.append(n(48, 2, As1, B, 44))
        drums_boss(cells, 48, 44, 38)
        pats.append(build_pattern(cells))
    return build_mod('Boss Crapple', pats, [0,1,2,3,0,1,2,3], speed=4, bpm=138)


def track_boss_faceplant():
    """Boss: Faceplant (Act 5) -- E minor, intense and erratic."""
    motifA = [(0, E2, 58), (2, Fs2, 54), (4, G2, 58), (7, A2, 62), (10, B2, 60)]
    motifB = [(0, B2, 60), (2, A2, 56), (4, G2, 58), (7, Fs2, 56), (10, E2, 60)]
    motifG = [(0, E2, 58), (2, G2, 56), (3, Fs2, 60), (5, A2, 58),
              (7, G2, 62), (9, B2, 60), (11, A2, 64)]

    pats = []
    for pi in range(5):
        cells = []
        if pi < 3:
            place_motif(cells, motifA, 4, 0, S)
            place_motif(cells, motifB, 18, 0, S)
        else:
            place_motif(cells, motifG, 4, 0, S)
            place_motif(cells, motif_repeat(motifG, -1), 18, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 3, pi), 34, 0, S)
        # Counter
        place_motif(cells, [(0, G2, 46), (3, A2, 44), (6, B2, 48)], 12, 1, O)
        place_motif(cells, [(0, E2, 44), (4, D2, 46)], 48, 1, O)
        # Bass
        cells.append(n(4,  2, E1, B, 46))
        cells.append(n(16, 2, B1, B, 44))
        cells.append(n(28, 2, A1, B, 44))
        cells.append(n(40, 2, G1, B, 44))
        cells.append(n(52, 2, D1, B, 46))
        drums_glitch(cells, 48, 44, 38)
        pats.append(build_pattern(cells))
    return build_mod('Boss Faceplant', pats, [0,1,2,3,4,0,1,2,3,4], speed=4, bpm=140)


def track_boss_daemon():
    """Boss: DAEMON (Act 6 final) -- chromatic chaos, building intensity."""
    # Phase 1: ominous chromatic descent
    motifP1 = [(0, A2, 58), (2, Gs2, 56), (4, G2, 58), (6, Fs2, 60),
               (8, F2, 58), (10, E2, 62), (12, Ds2, 60)]
    # Phase 2: ascending aggression
    motifP2 = [(0, E2, 60), (2, F2, 58), (4, Fs2, 62), (6, G2, 64),
               (8, Gs2, 62), (10, A2, 64), (12, As2, 66)]
    # Phase 3: chaotic alternation
    motifP3 = [(0, A2, 64), (1, Ds2, 60), (3, G2, 64), (4, Cs2, 62),
               (6, Fs2, 66), (7, C2, 62), (9, E2, 66), (11, As2, 68)]

    pats = []
    for pi in range(6):
        cells = []
        if pi < 2:
            place_motif(cells, motifP1, 4, 0, S)
            place_motif(cells, motif_repeat(motifP1, 2), 22, 0, S)
        elif pi < 4:
            place_motif(cells, motifP2, 4, 0, S)
            place_motif(cells, motif_repeat(motifP2, -3), 22, 0, S)
        else:
            place_motif(cells, motifP3, 4, 0, S)
            place_motif(cells, motif_repeat(motifP3, 1, 2), 22, 0, S)
        place_motif(cells, motif_repeat(motifP1, pi, pi), 42, 0, S)
        # Counter: dissonant response
        place_motif(cells, [(0, Ds2, 48), (3, F2, 46), (6, G2, 50)], 14, 1, O)
        if pi >= 2:
            place_motif(cells, [(0, Gs2, 50), (2, A2, 48), (4, As2, 52)], 34, 1, O)
        if pi >= 4:
            place_motif(cells, [(0, B2, 52), (2, C2, 50), (3, Cs2, 54)], 52, 1, O)
        # Bass: chromatic descent
        cells.append(n(4,  2, A1, B, 48))
        cells.append(n(16, 2, D1, B, 46))
        cells.append(n(28, 2, G1, B, 46))
        cells.append(n(40, 2, Ds1, B, 46))
        cells.append(n(52, 2, E1, B, 48))
        drums_boss(cells, 50, 48, 42)
        pats.append(build_pattern(cells))
    return build_mod('Boss DAEMON', pats,
                     [0,1,0,1,2,3,2,3,4,5,4,5], speed=4, bpm=142)


def track_miniboss():
    """Mini-boss: G minor, driving."""
    motifA = [(0, G2, 54), (3, As2, 50), (6, D2, 54), (9, C2, 52), (12, As1, 50)]
    motifB = [(0, D2, 52), (4, F2, 54), (8, G2, 56), (12, As2, 54)]

    pats = []
    for pi in range(3):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 22, 0, S)
        place_motif(cells, motif_repeat(motifA, pi, pi), 40, 0, S)
        # Counter
        place_motif(cells, [(0, As2, 42), (4, C2, 40), (8, D2, 44)], 14, 1, O)
        place_motif(cells, [(0, G2, 40), (6, F2, 42)], 50, 1, O)
        # Bass
        cells.append(n(4,  2, G1, B, 44))
        cells.append(n(16, 2, F1, B, 42))
        cells.append(n(32, 2, D1, B, 42))
        cells.append(n(48, 2, C1, B, 42))
        drums_boss(cells, 46, 42, 36)
        pats.append(build_pattern(cells))
    return build_mod('Mini Boss', pats, [0,1,2,0,1,2], speed=4, bpm=128)


def track_victory():
    """Victory: C major, triumphant ascending."""
    motifA = [(0, C2, 54), (4, E2, 50), (8, G2, 54), (12, C2, 58)]
    motifB = [(0, G2, 54), (4, E2, 50), (8, C2, 54), (12, G1, 50)]

    cells = []
    place_motif(cells, motifA, 4, 0, S)
    place_motif(cells, motifB, 20, 0, S)
    place_motif(cells, motif_repeat(motifA, 0, 4), 36, 0, S)
    # Fanfare counter
    place_motif(cells, [(0, E2, 44), (4, G2, 42), (8, C2, 46)], 12, 1, O)
    place_motif(cells, [(0, G2, 46), (4, C2, 44), (8, E2, 48)], 44, 1, O)
    # Bass
    cells.append(n(4,  2, C1, B, 44))
    cells.append(n(20, 2, G1, B, 42))
    cells.append(n(36, 2, F1, B, 42))
    cells.append(n(52, 2, G1, B, 42))
    drums_rock(cells, 42, 38, 32)
    p = build_pattern(cells)
    return build_mod('Victory', [p], [0, 0], speed=5, bpm=112)


def track_gameover():
    """Game Over: D minor, mournful descent."""
    cells = []
    mel = [(4, D2, 46), (10, C2, 42), (16, As1, 40), (22, A1, 42),
           (28, G1, 38), (34, F1, 36), (40, E1, 38), (46, D1, 42),
           (52, C1, 38)]
    for row, nt, vol in mel:
        cells.append(n(row, 0, nt, S, vol))
    # Sparse counter
    cells.append(n(8,  1, F2, O, 34))
    cells.append(n(24, 1, D2, O, 32))
    cells.append(n(40, 1, C2, O, 34))
    # Bass
    cells.append(n(4,  2, D1, B, 38))
    cells.append(n(28, 2, G1, B, 36))
    cells.append(n(52, 2, C1, B, 36))
    p = build_pattern(cells)
    return build_mod('Game Over', [p], [0, 0, 0], speed=8, bpm=62)


def track_credits():
    """Credits: A major, reflective and warm."""
    motifA = [(0, A2, 48), (4, Cs2, 44), (8, E2, 48), (12, A2, 52)]
    motifB = [(0, Fs2, 46), (4, E2, 44), (8, D2, 48), (12, Cs2, 46)]

    pats = []
    for pi in range(3):
        cells = []
        place_motif(cells, motifA, 4, 0, S)
        place_motif(cells, motifB, 20, 0, S)
        place_motif(cells, motif_repeat(motifA, pi % 2, 2), 36, 0, S)
        # Counter
        cells.append(n(12, 1, E2, O, 38))
        cells.append(n(28, 1, Cs2, O, 36))
        cells.append(n(44, 1, D2, O, 38))
        cells.append(n(56, 1, E2, O, 40))
        # Bass
        cells.append(n(4,  2, A1, B, 40))
        cells.append(n(20, 2, E1, B, 38))
        cells.append(n(36, 2, D1, B, 38))
        cells.append(n(52, 2, A1, B, 40))
        if pi >= 1:
            drums_sparse(cells, 30, 26, 22)
        pats.append(build_pattern(cells))
    return build_mod('Credits', pats, [0, 1, 2, 0, 1, 2], speed=6, bpm=85)


def track_evolution():
    """Evolution: E major, epic ascending fanfare."""
    motifA = [(0, E2, 58), (3, Gs2, 54), (6, B2, 58), (10, E2, 62)]
    motifB = [(0, B2, 56), (4, Gs2, 54), (8, E2, 58), (12, B1, 52)]

    cells = []
    place_motif(cells, motifA, 4, 0, S)
    place_motif(cells, motifB, 18, 0, S)
    place_motif(cells, motif_repeat(motifA, 0, 6), 34, 0, S)
    place_motif(cells, motif_repeat(motifB, 2, 4), 50, 0, S)
    # Triumphant counter
    place_motif(cells, [(0, Gs2, 48), (4, B2, 46), (8, E2, 50)], 12, 1, O)
    place_motif(cells, [(0, Gs2, 50), (4, B2, 52)], 42, 1, O)
    # Bass
    cells.append(n(4,  2, E1, B, 48))
    cells.append(n(20, 2, B1, B, 46))
    cells.append(n(36, 2, Gs1, B, 46))
    cells.append(n(52, 2, E1, B, 48))
    drums_rock(cells, 44, 40, 34)
    p = build_pattern(cells)
    return build_mod('Evolution', [p, p], [0, 0], speed=4, bpm=115)


MUSIC_TRACKS = {
    '00_title.mod':       track_title,
    '01_terminal.mod':    track_terminal,
    '02_act1.mod':        track_act1,
    '03_act2.mod':        track_act2,
    '04_act3.mod':        track_act3,
    '05_act4.mod':        track_act4,
    '06_act5.mod':        track_act5,
    '07_act6.mod':        track_act6,
    '08_boss_corp.mod':   track_boss_microslop,
    '09_boss_gate.mod':   track_boss_gogol,
    '10_boss_daemon.mod': track_boss_daemon,
    '11_miniboss.mod':    track_miniboss,
    '12_victory.mod':     track_victory,
    '13_gameover.mod':    track_gameover,
    '14_credits.mod':     track_credits,
    '15_evolution.mod':   track_evolution,
}


# -- Expanded SFX via parameterized generation ----------------------------

EXPANDED_SFX = []

def _sfx(num, name, synth_type, freq_start, freq_end, dur, echo_params=None,
          overdrive_params=None, fade_in=0, fade_out=0.05, gain=-3):
    """Register a parameterized SFX."""
    EXPANDED_SFX.append((num, name, synth_type, freq_start, freq_end, dur,
                         echo_params, overdrive_params, fade_in, fade_out, gain))

# --- Ambient / Environment (39-78) ---
_sfx(39,'ambient_wind','sine',80,120,2.0,(0.6,0.5,200,0.6),None,0.1,0.3,-8)
_sfx(40,'ambient_rain','sine',2000,200,1.5,(0.5,0.4,30,0.5),None,0.1,0.2,-6)
_sfx(41,'ambient_static','sine',800,1200,1.0,(0.3,0.2,10,0.3),(8,10),0,0.1,-5)
_sfx(42,'ambient_hum','sine',110,115,2.5,(0.7,0.6,100,0.7),None,0.2,0.3,-8)
_sfx(43,'ambient_drip','sine',1400,200,0.3,(0.5,0.4,120,0.5),None,0,0.08,-4)
_sfx(44,'ambient_sparks','sine',1800,400,0.2,(0.4,0.3,40,0.4),(12,15),0,0.04,-3)
_sfx(45,'ambient_machinery','sine',150,160,2.0,(0.6,0.5,80,0.6),(6,8),0.1,0.2,-7)
_sfx(46,'ambient_dataflow','sine',440,880,1.5,(0.5,0.4,60,0.5),None,0.05,0.15,-5)
_sfx(47,'ambient_alarm','sine',800,800,0.8,(0.4,0.3,100,0.4),None,0,0.1,-4)
_sfx(48,'ambient_ventilation','sine',200,220,2.0,(0.6,0.5,150,0.6),None,0.15,0.25,-8)
_sfx(49,'ambient_electric_arc','sine',2200,600,0.15,(0.3,0.2,20,0.3),(15,20),0,0.03,-3)
_sfx(50,'ambient_server_hum','sine',90,95,3.0,(0.7,0.6,120,0.7),None,0.2,0.4,-9)
_sfx(51,'ambient_water_drip','sine',1600,180,0.25,(0.5,0.4,140,0.5),None,0,0.06,-4)
_sfx(52,'ambient_pipe_creak','sine',300,150,0.4,(0.4,0.3,80,0.4),(10,12),0,0.1,-5)
_sfx(53,'ambient_fan_spin','sine',180,190,2.5,(0.6,0.5,90,0.6),None,0.1,0.3,-7)
_sfx(54,'ambient_distant_rumble','sine',55,40,2.0,(0.6,0.5,180,0.6),(8,10),0.1,0.3,-6)
_sfx(55,'ambient_digital_whisper','sine',600,900,1.0,(0.5,0.4,45,0.5),None,0.05,0.15,-7)
_sfx(56,'ambient_crackle','sine',1500,300,0.3,(0.3,0.2,25,0.3),(14,18),0,0.05,-4)
_sfx(57,'ambient_magnetic_pulse','sine',250,500,0.6,(0.5,0.4,70,0.5),None,0.02,0.1,-5)
_sfx(58,'ambient_cooling_system','sine',170,175,3.0,(0.7,0.6,110,0.7),None,0.2,0.4,-8)
# 20 more ambient variants
for i in range(20):
    freq = 100 + i * 50
    _sfx(59+i, f'ambient_drone_{i:02d}', 'sine', freq, freq+20, 2.0+i*0.1,
         (0.6, 0.5, 100+i*10, 0.6), None, 0.1, 0.3, -7)

# --- Combat variants (79-128) ---
_sfx(79,'impact_light','sine',600,100,0.08,None,(16,20),0,0.02,-3)
_sfx(80,'impact_heavy','sine',250,40,0.15,None,(22,28),0,0.04,-2)
_sfx(81,'impact_critical','sine',400,60,0.2,(0.4,0.3,40,0.4),(18,22),0,0.05,-2)
_sfx(82,'impact_shield','sine',900,400,0.12,(0.3,0.2,30,0.3),(10,12),0,0.03,-3)
_sfx(83,'impact_armor_clank','sine',1200,300,0.1,(0.3,0.2,20,0.3),(20,25),0,0.03,-3)
_sfx(84,'impact_parry','sine',1500,800,0.08,(0.4,0.3,25,0.4),(12,15),0,0.02,-3)
_sfx(85,'impact_ricochet','sine',1800,600,0.15,(0.5,0.4,60,0.5),None,0,0.04,-3)
_sfx(86,'impact_deflect','sine',1100,700,0.1,(0.4,0.3,35,0.4),(8,10),0,0.03,-3)
_sfx(87,'impact_pierce','sine',2000,500,0.06,None,(14,18),0,0.015,-3)
_sfx(88,'impact_slash','sine',1400,200,0.12,None,(10,14),0,0.03,-3)
_sfx(89,'impact_crush','sine',180,30,0.2,None,(24,30),0,0.06,-2)
_sfx(90,'impact_shock','sine',2500,800,0.1,(0.3,0.2,15,0.3),(16,20),0,0.02,-3)
for i in range(20):
    freq = 300 + i * 80
    dur = 0.08 + (i % 5) * 0.04
    _sfx(91+i, f'weapon_impact_{i:02d}', 'sine', freq, freq//3, dur,
         None, (12+i%8, 15+i%8), 0, 0.02, -3)
for i in range(18):
    _sfx(111+i, f'projectile_hit_{i:02d}', 'sine', 500+i*60, 100+i*20, 0.1+i*0.01,
         (0.3, 0.2, 20+i*3, 0.3), None, 0, 0.03, -4)

# --- Movement sounds (129-168) ---
_sfx(129,'footstep_metal','sine',800,200,0.05,None,(20,24),0,0.01,-6)
_sfx(130,'footstep_tile','sine',1200,400,0.04,None,(16,20),0,0.01,-6)
_sfx(131,'footstep_grate','sine',1500,500,0.05,None,(18,22),0,0.01,-5)
_sfx(132,'footstep_dirt','sine',400,100,0.06,None,(8,10),0,0.015,-6)
_sfx(133,'slide_long','sine',300,200,0.4,(0.4,0.3,50,0.4),None,0.02,0.08,-5)
_sfx(134,'climb_grip','sine',500,700,0.1,None,(6,8),0,0.03,-5)
_sfx(135,'teleport_out','sine',200,2000,0.3,(0.5,0.4,40,0.5),None,0,0.06,-3)
_sfx(136,'teleport_in','sine',2000,200,0.3,(0.5,0.4,40,0.5),None,0,0.06,-3)
_sfx(137,'hover_loop','sine',150,160,1.5,(0.6,0.5,80,0.6),None,0.1,0.2,-6)
_sfx(138,'landing_light','sine',300,80,0.08,None,(10,12),0,0.02,-5)
_sfx(139,'landing_heavy_2','sine',150,30,0.15,None,(16,20),0,0.04,-3)
_sfx(140,'swim_stroke','sine',400,300,0.2,(0.4,0.3,60,0.4),None,0.02,0.05,-6)
for i in range(28):
    freq = 200 + i * 40
    _sfx(141+i, f'movement_var_{i:02d}', 'sine', freq, freq//2, 0.1+i*0.02,
         (0.3, 0.2, 30+i*2, 0.3) if i%3==0 else None,
         (10+i%6, 12+i%6) if i%3==1 else None, 0, 0.03, -5)

# --- UI / Feedback (169-218) ---
_sfx(169,'ui_confirm','sine',660,880,0.12,(0.3,0.2,40,0.3),None,0,0.04,-5)
_sfx(170,'ui_cancel','sine',440,330,0.1,None,None,0,0.03,-5)
_sfx(171,'ui_scroll','sine',1000,1000,0.04,None,None,0,0.01,-7)
_sfx(172,'ui_error','sine',220,180,0.15,None,(8,10),0,0.04,-4)
_sfx(173,'ui_open_menu','sine',500,800,0.15,(0.3,0.2,30,0.3),None,0,0.04,-5)
_sfx(174,'ui_close_menu','sine',800,400,0.12,None,None,0,0.03,-5)
_sfx(175,'stat_up','sine',523,1047,0.25,(0.4,0.3,50,0.4),None,0.01,0.06,-4)
_sfx(176,'stat_down','sine',523,262,0.25,None,None,0,0.06,-4)
_sfx(177,'buff_apply','sine',660,990,0.3,(0.4,0.3,65,0.4),None,0.01,0.08,-4)
_sfx(178,'debuff_apply','sine',440,220,0.3,(0.3,0.2,50,0.3),(6,8),0,0.08,-4)
_sfx(179,'warning_beep','sine',880,880,0.1,None,None,0,0.03,-4)
_sfx(180,'alarm_siren','sine',600,1200,0.5,(0.4,0.3,80,0.4),None,0.02,0.1,-4)
_sfx(181,'codex_unlock','sine',784,1568,0.4,(0.5,0.4,70,0.5),None,0.01,0.1,-3)
_sfx(182,'map_reveal','sine',440,660,0.35,(0.4,0.3,55,0.4),None,0.01,0.08,-4)
_sfx(183,'quest_update','sine',523,784,0.3,(0.4,0.3,45,0.4),None,0.01,0.07,-4)
_sfx(184,'quest_complete','sine',523,1047,0.5,(0.5,0.4,80,0.5),None,0.01,0.12,-3)
for i in range(34):
    freq = 400 + i * 30
    _sfx(185+i, f'ui_tone_{i:02d}', 'sine', freq, freq + 100 + i*20, 0.1+i*0.01,
         (0.3, 0.2, 30+i*2, 0.3) if i%2==0 else None, None, 0, 0.03, -5)

# --- Boss attack sounds (219-248) ---
bosses = ['microslop','gogol','amazomb','crapple','faceplant','daemon']
for bi, boss in enumerate(bosses):
    base_freq = 150 + bi * 40
    _sfx(219+bi*5, f'boss_{boss}_atk1', 'sine', base_freq*2, base_freq//2, 0.3,
         (0.5, 0.4, 80, 0.5), (14+bi*2, 18+bi*2), 0, 0.08, -3)
    _sfx(220+bi*5, f'boss_{boss}_atk2', 'sine', base_freq*3, base_freq, 0.25,
         (0.4, 0.3, 60, 0.4), (12+bi*2, 16+bi*2), 0, 0.06, -3)
    _sfx(221+bi*5, f'boss_{boss}_atk3', 'sine', base_freq, base_freq*4, 0.35,
         (0.5, 0.4, 100, 0.5), None, 0.01, 0.09, -2)
    _sfx(222+bi*5, f'boss_{boss}_roar', 'sine', base_freq//2, base_freq*2, 0.5,
         (0.6, 0.5, 120, 0.6), (10+bi*2, 14+bi*2), 0.02, 0.12, -3)
    _sfx(223+bi*5, f'boss_{boss}_death', 'sine', base_freq*3, 30, 0.7,
         (0.6, 0.5, 140, 0.6), (20+bi*2, 24+bi*2), 0, 0.15, -2)

# --- Enemy type sounds (249-296) ---
enemies = ['sentry','patrol','flyer','shield','spike','hunter',
           'drone','turret','mimic','corruptor','ghost','bomber']
for ei, ename in enumerate(enemies):
    base = 300 + ei * 50
    _sfx(249+ei*4, f'enemy_{ename}_alert', 'sine', base, base*2, 0.15,
         (0.3, 0.2, 30, 0.3), None, 0, 0.04, -4)
    _sfx(250+ei*4, f'enemy_{ename}_atk', 'sine', base*2, base//2, 0.12,
         None, (10+ei, 14+ei), 0, 0.03, -3)
    _sfx(251+ei*4, f'enemy_{ename}_hurt', 'sine', base+200, base-100, 0.1,
         None, (12+ei, 16+ei), 0, 0.03, -4)
    _sfx(252+ei*4, f'enemy_{ename}_spawn', 'sine', base//2, base*3, 0.2,
         (0.4, 0.3, 40, 0.4), None, 0.01, 0.05, -4)

# --- Ability sounds (297-320) ---
abilities = ['overcharge','iron_skin','berserk','war_cry','plasma_burst',
             'charged_beam','adrenaline','rage_mode','cloak','backstab',
             'blink','smoke_bomb','poison_blade','trap_set','shadow_strike',
             'vanish','data_shield','upload','firewall','drone_deploy',
             'emp_blast','hack','nanobots','overclock']
for ai, aname in enumerate(abilities):
    base = 350 + ai * 30
    _sfx(297+ai, f'ability_{aname}', 'sine', base, base + 200 + ai*20, 0.3 + ai*0.01,
         (0.4, 0.3, 60+ai*3, 0.4), (8+ai%6, 12+ai%6) if ai%3==0 else None,
         0.01, 0.08, -3)

# --- Hazard sounds (321-340) ---
hazards = ['acid_sizzle','fire_burst','electric_zap','ice_crack','corruption_pulse',
           'laser_sweep','trap_trigger','gas_leak','plasma_field','gravity_well',
           'radiation_tick','emp_wave','toxin_cloud','steam_vent','blade_spin',
           'spike_extend','mine_arm','turret_lock','barrier_hum','field_collapse']
for hi, hname in enumerate(hazards):
    base = 400 + hi * 60
    _sfx(321+hi, f'hazard_{hname}', 'sine', base, base//2 if hi%2==0 else base*2,
         0.2 + hi*0.02, (0.4, 0.3, 50+hi*3, 0.4),
         (10+hi%8, 14+hi%8) if hi%2==1 else None, 0, 0.05, -3)

# --- Loot / Crafting sounds (341-360) ---
loot_sfx = [('forge_hammer',300,100,0.2,(0.4,0.3,50,0.4),(18,22)),
            ('salvage_crunch',600,150,0.15,None,(14,18)),
            ('dismantle_snap',900,200,0.1,None,(10,14)),
            ('enhance_shimmer',500,1000,0.4,(0.5,0.4,80,0.5),None),
            ('rare_drop',784,1568,0.5,(0.5,0.4,90,0.5),None),
            ('mythic_drop',392,1568,0.7,(0.6,0.5,120,0.6),None),
            ('set_bonus',523,1047,0.6,(0.5,0.4,100,0.5),None),
            ('common_drop',600,400,0.15,(0.3,0.2,30,0.3),None),
            ('uncommon_drop',660,550,0.2,(0.3,0.2,40,0.3),None),
            ('epic_drop',700,1200,0.45,(0.5,0.4,85,0.5),None),
            ('equip_weapon',800,400,0.1,None,(8,10)),
            ('equip_armor',500,200,0.12,None,(12,15)),
            ('equip_accessory',1000,600,0.08,None,None),
            ('unequip',400,600,0.08,None,None),
            ('inventory_open',700,900,0.1,(0.3,0.2,25,0.3),None),
            ('inventory_close',900,600,0.08,None,None),
            ('credits_gain',880,1100,0.12,(0.3,0.2,35,0.3),None),
            ('credits_spend',600,400,0.1,None,None),
            ('shard_collect',1200,800,0.08,(0.3,0.2,20,0.3),None),
            ('recipe_learn',660,1320,0.4,(0.5,0.4,70,0.5),None)]
for li, (lname,fs,fe,dur,echo,od) in enumerate(loot_sfx):
    EXPANDED_SFX.append((341+li, lname, 'sine', fs, fe, dur, echo, od, 0.01, 0.05, -3))

# --- Story / Narrative (361-380) ---
story_sfx = [('data_upload',300,1500,0.5),('decrypt_start',400,800,0.4),
             ('decrypt_success',600,1200,0.35),('hack_attempt',500,900,0.3),
             ('hack_success',700,1400,0.4),('connection_open',440,880,0.3),
             ('connection_close',880,440,0.25),('transmission_send',350,700,0.35),
             ('transmission_recv',700,350,0.3),('firewall_breach',250,1000,0.4),
             ('system_boot',200,800,0.5),('system_shutdown',800,100,0.5),
             ('alert_level_up',500,1000,0.3),('alert_level_down',1000,500,0.3),
             ('virus_detected',900,300,0.2),('patch_applied',600,900,0.25),
             ('memory_corrupt',1200,200,0.3),('memory_restore',200,1200,0.35),
             ('trace_start',350,600,0.3),('trace_complete',600,1100,0.4)]
for si, (sname,fs,fe,dur) in enumerate(story_sfx):
    EXPANDED_SFX.append((361+si, sname, 'sine', fs, fe, dur,
                         (0.5, 0.4, 70+si*3, 0.5), None, 0.01, 0.08, -4))


def make_expanded_sfx():
    """Generate all expanded SFX (39+)."""
    d = SFX_DIR
    for num, name, synth, fs, fe, dur, echo, od, fi, fo, gain in EXPANDED_SFX:
        path = f'{d}/{num:02d}_{name}.wav'
        args = ['synth', str(dur), synth, f'{fs}:{fe}']
        if od:
            args += ['overdrive', str(od[0]), str(od[1])]
        if echo:
            args += ['echo', str(echo[0]), str(echo[1]), str(echo[2]), str(echo[3])]
        total_dur = dur + (echo[2]/1000 + dur * echo[3] if echo else 0) + fi + fo + 0.02
        args += ['fade', 'h', str(fi), str(round(total_dur, 2)), str(fo)]
        args += ['gain', str(gain)]
        sox_wav(path, *args)


# -- Expanded MOD tracks with larger waveforms ----------------------------

def wave_triangle(length=1024):
    """1024-sample triangle wave, 8-bit signed."""
    data = bytearray(length)
    for i in range(length):
        phase = (i * 4 * 256) // length
        if phase < 256:
            data[i] = phase & 0xFF
        elif phase < 768:
            data[i] = (512 - phase) & 0xFF
        else:
            data[i] = (phase - 1024) & 0xFF
    return bytes(data)

def wave_sawtooth(length=1024):
    """1024-sample sawtooth wave, 8-bit signed."""
    return bytes(((i * 256 // length) - 128) & 0xFF for i in range(length))

def wave_square(length=1024, duty=50):
    """1024-sample square wave with variable duty cycle."""
    threshold = length * duty // 100
    return bytes(100 if i < threshold else (256-100) for i in range(length))

def wave_organ(length=1024):
    """1024-sample organ (additive synthesis), 8-bit signed."""
    data = bytearray(length)
    for i in range(length):
        val = 0
        for h, amp in [(1, 80), (2, 40), (3, 20), (4, 10)]:
            val += int(amp * math.sin(2 * math.pi * h * i / length))
        data[i] = max(0, min(255, val + 128)) & 0xFF
    return bytes(data)

def wave_sine_large(length=1024):
    """1024-sample sine wave."""
    return bytes((int(118 * math.sin(2 * math.pi * i / length)) & 0xFF)
                 for i in range(length))


def smp_hdr_large(name, data, vol=56):
    """Sample header for larger samples."""
    words = len(data) // 2
    return struct.pack('>22sHBBHH',
                       name.encode()[:22].ljust(22, b'\0'),
                       words, 0, vol, 0, words)


def build_mod_large(title, patterns, order, speed=6, bpm=90,
                    samples=None):
    """Assemble a MOD with up to 4 large-sample instruments."""
    if samples is None:
        sd = wave_sine_large(1024)
        samples = [('Melody', sd, 56), ('Bass', sd, 48)]

    title_b = title.encode()[:20].ljust(20, b'\0')
    hdrs = b''
    for i in range(31):
        if i < len(samples):
            name, data, vol = samples[i]
            hdrs += smp_hdr_large(name, data, vol)
        else:
            hdrs += struct.pack('>22sHBBHH', b'\0'*22, 0, 0, 0, 0, 0)

    # Inject BPM+speed into first pattern
    if patterns:
        p0 = bytearray(patterns[0])
        p0[0]=0; p0[1]=0; p0[2]=0x0F; p0[3]=bpm & 0xFF
        p0[4]=0; p0[5]=0; p0[6]=0x0F; p0[7]=speed & 0x1F
        patterns[0] = bytes(p0)

    n_pat = max(order) + 1 if order else 1
    mod = title_b + hdrs
    mod += struct.pack('BB', len(order), 0)
    mod += bytes(order + [0] * (128 - len(order)))
    mod += b'M.K.'
    for i in range(n_pat):
        mod += patterns[i] if i < len(patterns) else bytes(MOD_ROWS * MOD_CHAN * 4)
    # Append sample data
    for i in range(len(samples)):
        mod += samples[i][1]
    return mod


def gen_expanded_track(idx, title, key_notes, bass_notes, bpm, speed,
                       n_patterns, wave_fns):
    """Generate an expanded MOD track with motif-based composition."""
    samps = []
    for i, wfn in enumerate(wave_fns):
        name = f'Inst{i+1}'
        data = wfn(2048)
        vol = 60 - i * 4  # boosted volumes
        samps.append((name, data, vol))

    # Build motifs from the key notes
    motif_len = min(4, len(key_notes))

    pats = []
    for pi in range(n_patterns):
        cells = []
        # Melody on channel 0: motif-based with variation
        motif_start = (pi * 3) % len(key_notes)
        for r in range(4, 56, 4):
            ni = (motif_start + (r - 4) // 4) % len(key_notes)
            nt = key_notes[ni]
            # Volume contour: crescendo within each half
            vol_base = 44 + (r % 32) // 4
            if pi % 2 == 1:
                vol_base += 2
            cells.append(n(r, 0, nt, 1, min(64, vol_base)))
        # Bass on channel 1: whole notes with variation
        for r in range(4, 60, 16):
            ni = (r // 16 + pi * 2) % len(bass_notes)
            nt = bass_notes[ni]
            cells.append(n(r, 1, nt, 2, 44))
        # Counter melody on channel 2 (if 3+ instruments): call-response
        if len(samps) >= 3:
            response_offset = (pi * 2 + 1) % len(key_notes)
            for r in range(8, 56, 8):
                ni = (response_offset + r // 8) % len(key_notes)
                nt = key_notes[ni]
                cells.append(n(r, 2, nt, 3, 40))
        # Drums on channel 3 (if 4 instruments)
        if len(samps) >= 4:
            for r in range(0, 64, 8):
                cells.append(n(r, 3, C1, 4, 38))
            for r in range(4, 60, 8):
                cells.append(n(r, 3, G2, 4, 30))
        pats.append(build_pattern(cells))

    order = []
    for _ in range(4):
        order.extend(range(n_patterns))
    order = order[:128]

    return build_mod_large(title, pats, order, speed, bpm, samps)


EXPANDED_TRACKS = {}

# Ambient tracks -- boosted volumes, motif-based
EXPANDED_TRACKS['16_ambient_hub.mod'] = lambda: gen_expanded_track(
    16, 'Ambient Hub', [C2,E2,G2,A2,C2,E2], [C1,G1,A1,E1], 65, 8, 4,
    [wave_sine_large, wave_triangle, wave_organ])
EXPANDED_TRACKS['17_ambient_shop.mod'] = lambda: gen_expanded_track(
    17, 'Shop Theme', [D2,F2,A2,C2,D2,F2], [D1,A1,F1,C1], 72, 7, 4,
    [wave_triangle, wave_sine_large, wave_organ])
EXPANDED_TRACKS['18_ambient_codex.mod'] = lambda: gen_expanded_track(
    18, 'Codex Browse', [E2,G2,B2,D2,E2,G2], [E1,B1,G1,D1], 60, 8, 3,
    [wave_sine_large, wave_organ])
EXPANDED_TRACKS['19_tension_01.mod'] = lambda: gen_expanded_track(
    19, 'Tension I', [A2,C2,E2,G2,A2,C2], [A1,E1,C1,G1], 85, 6, 6,
    [wave_sawtooth, wave_sine_large, wave_square, wave_organ])
EXPANDED_TRACKS['20_tension_02.mod'] = lambda: gen_expanded_track(
    20, 'Tension II', [D2,F2,Gs2,B2,D2,F2], [D1,Gs1,F1,B1], 90, 6, 6,
    [wave_square, wave_sawtooth, wave_sine_large, wave_triangle])
EXPANDED_TRACKS['21_tension_03.mod'] = lambda: gen_expanded_track(
    21, 'Tension III', [F2,Gs2,B2,Cs2,F2,Gs2], [F1,B1,Gs1,Cs1], 95, 5, 8,
    [wave_sawtooth, wave_square, wave_organ, wave_triangle])
EXPANDED_TRACKS['22_tension_04.mod'] = lambda: gen_expanded_track(
    22, 'Tension IV', [B2,D2,F2,Gs2,B2,D2], [B1,F1,D1,Gs1], 100, 5, 8,
    [wave_square, wave_sawtooth, wave_triangle, wave_organ])
EXPANDED_TRACKS['23_boss_phase2.mod'] = lambda: gen_expanded_track(
    23, 'Boss Phase 2', [E2,Fs2,G2,A2,B2,Cs2], [E1,B1,A1,G1], 135, 4, 6,
    [wave_sawtooth, wave_square, wave_sine_large, wave_organ])
EXPANDED_TRACKS['24_boss_phase3.mod'] = lambda: gen_expanded_track(
    24, 'Boss Phase 3', [A2,B2,C2,D2,E2,F2,G2,Gs2], [A1,E1,C1,D1], 145, 4, 8,
    [wave_square, wave_sawtooth, wave_organ, wave_triangle])
EXPANDED_TRACKS['25_cutscene_intro.mod'] = lambda: gen_expanded_track(
    25, 'Cutscene Intro', [C2,Ds2,G2,As2,C2], [C1,G1,As1,Ds1], 70, 7, 4,
    [wave_sine_large, wave_organ, wave_triangle])
EXPANDED_TRACKS['26_cutscene_mid.mod'] = lambda: gen_expanded_track(
    26, 'Cutscene Mid', [D2,F2,A2,C2,D2], [D1,A1,F1,C1], 78, 7, 4,
    [wave_organ, wave_sine_large, wave_triangle])
EXPANDED_TRACKS['27_cutscene_end.mod'] = lambda: gen_expanded_track(
    27, 'Cutscene End', [G2,B2,D2,Fs2,G2], [G1,D1,B1,Fs1], 80, 7, 4,
    [wave_triangle, wave_organ, wave_sine_large])
EXPANDED_TRACKS['28_endgame_01.mod'] = lambda: gen_expanded_track(
    28, 'Endgame I', [A2,C2,E2,G2,A2,B2], [A1,E1,C1,G1], 115, 5, 8,
    [wave_sawtooth, wave_square, wave_sine_large, wave_organ])
EXPANDED_TRACKS['29_endgame_02.mod'] = lambda: gen_expanded_track(
    29, 'Endgame II', [D2,F2,A2,C2,D2,E2], [D1,A1,F1,C1], 120, 5, 8,
    [wave_square, wave_sawtooth, wave_organ, wave_triangle])
EXPANDED_TRACKS['30_bugbounty_01.mod'] = lambda: gen_expanded_track(
    30, 'Bug Bounty I', [E2,G2,A2,B2,D2,E2], [E1,B1,A1,G1], 108, 5, 6,
    [wave_sawtooth, wave_sine_large, wave_organ])
EXPANDED_TRACKS['31_bugbounty_02.mod'] = lambda: gen_expanded_track(
    31, 'Bug Bounty II', [Fs2,A2,B2,Cs2,E2,Fs2], [Fs1,Cs1,A1,E1], 112, 5, 6,
    [wave_square, wave_triangle, wave_organ])
EXPANDED_TRACKS['32_achieve_jingle.mod'] = lambda: gen_expanded_track(
    32, 'Achievement', [C2,E2,G2,C2,E2,G2], [C1,G1], 100, 5, 2,
    [wave_sine_large, wave_organ])
EXPANDED_TRACKS['33_levelup_jingle.mod'] = lambda: gen_expanded_track(
    33, 'Level Up', [E2,G2,B2,E2,G2,B2], [E1,B1], 105, 5, 2,
    [wave_organ, wave_triangle])
EXPANDED_TRACKS['34_raredrop_jingle.mod'] = lambda: gen_expanded_track(
    34, 'Rare Drop', [A2,Cs2,E2,A2,Cs2,E2], [A1,E1], 95, 5, 2,
    [wave_triangle, wave_sine_large])
EXPANDED_TRACKS['35_crafting.mod'] = lambda: gen_expanded_track(
    35, 'Crafting', [D2,F2,A2,C2,D2,F2], [D1,A1,F1,C1], 82, 6, 4,
    [wave_organ, wave_triangle, wave_sine_large])
EXPANDED_TRACKS['36_stealth_01.mod'] = lambda: gen_expanded_track(
    36, 'Stealth I', [C2,Ds2,F2,Gs2,As2], [C1,Gs1,F1,Ds1], 68, 7, 4,
    [wave_sine_large, wave_triangle])
EXPANDED_TRACKS['37_stealth_02.mod'] = lambda: gen_expanded_track(
    37, 'Stealth II', [D2,F2,Gs2,B2,D2], [D1,Gs1,F1,B1], 72, 7, 4,
    [wave_triangle, wave_sine_large])
EXPANDED_TRACKS['38_chase_01.mod'] = lambda: gen_expanded_track(
    38, 'Chase I', [E2,G2,A2,B2,D2,E2], [E1,B1,A1,G1], 130, 4, 6,
    [wave_sawtooth, wave_square, wave_sine_large, wave_organ])
EXPANDED_TRACKS['39_chase_02.mod'] = lambda: gen_expanded_track(
    39, 'Chase II', [A2,C2,D2,E2,G2,A2], [A1,E1,D1,C1], 138, 4, 6,
    [wave_square, wave_sawtooth, wave_triangle, wave_organ])


def main():
    os.makedirs(MUSIC_DIR, exist_ok=True)
    os.makedirs(SFX_DIR,   exist_ok=True)

    print('Generating original SFX via sox...')
    make_sfx()
    print(f'  Generated 38 original SFX')

    print('Generating expanded SFX via sox...')
    make_expanded_sfx()
    print(f'  Generated {len(EXPANDED_SFX)} expanded SFX')

    total_sfx = len([f for f in os.listdir(SFX_DIR) if f.endswith('.wav')])
    print(f'  Total SFX: {total_sfx}')

    print('Generating original MOD music...')
    for fname, fn in sorted(MUSIC_TRACKS.items()):
        data = fn()
        path = os.path.join(MUSIC_DIR, fname)
        with open(path, 'wb') as fh:
            fh.write(data)
        print(f'  MOD  {fname} ({len(data)} bytes)')

    print('Generating expanded MOD tracks...')
    for fname, fn in sorted(EXPANDED_TRACKS.items()):
        data = fn()
        path = os.path.join(MUSIC_DIR, fname)
        with open(path, 'wb') as fh:
            fh.write(data)
        print(f'  MOD  {fname} ({len(data)} bytes)')

    total_mod = len([f for f in os.listdir(MUSIC_DIR) if f.endswith('.mod')])
    print(f'\nTotal: {total_sfx} SFX + {total_mod} MOD tracks generated.')


if __name__ == '__main__':
    main()
