#!/usr/bin/env python3
"""Generate additional ROM content — environment animations, parallax layers, and tileset variations."""
import os, struct

# Simple PRNG for deterministic content
class RNG:
    def __init__(self, seed=0xDEADBEEF):
        self.s = seed & 0xFFFFFFFF
    def next(self):
        self.s = (self.s * 1103515245 + 12345) & 0xFFFFFFFF
        return (self.s >> 16) & 0xFFFF
    def byte(self):
        return self.next() & 0xFF
    def nibble(self):
        return self.next() & 0xF

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "source", "game")
INC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "include", "game")

def write_file(path, content):
    with open(path, 'w') as f:
        f.write(content)
    print(f"  Wrote {path} ({len(content)} bytes)")

def gen_tile_row(rng, pattern_fn, row, col, frame):
    """Generate 8 u32 values for one 8x8 4bpp tile."""
    vals = []
    for py in range(8):
        v = 0
        for px in range(8):
            pix = pattern_fn(rng, col*8+px, row*8+py, frame) & 0xF
            v |= (pix << (px * 4))
        vals.append(v)
    return vals

def circuit_pattern(rng, x, y, frame):
    """Circuit board pattern."""
    if x % 16 == 0 or y % 16 == 0:
        return 6  # trace lines
    if x % 16 == 8 and y % 16 == 8:
        return 10  # nodes
    if (x + frame) % 32 < 2 and y % 8 == 4:
        return 14  # data flow animation
    if rng.next() % 100 < 3:
        return 4  # random dots
    return 1  # background

def wave_pattern(rng, x, y, frame):
    """Sine wave pattern."""
    import math
    wave_y = int(80 + 30 * math.sin((x + frame * 2) * 0.05))
    dist = abs(y - wave_y)
    if dist < 2: return 12
    if dist < 5: return 8
    if dist < 10: return 4
    if y > 120: return 2
    return 1

def city_pattern(rng, x, y, frame):
    """Cityscape silhouette."""
    # Building heights based on x position
    h = [80, 60, 90, 70, 50, 85, 65, 75, 95, 55, 80, 70, 60, 90, 50, 85]
    bh = h[(x // 15) % len(h)]
    if y > bh:
        # Building body
        if x % 15 == 0 or x % 15 == 14: return 3  # edges
        if y % 8 < 6 and x % 6 > 1 and x % 6 < 5:
            return 10 if (frame + x) % 30 < 15 else 2  # windows (animated)
        return 5  # wall
    if y == bh: return 7  # rooftop
    if y > bh - 3 and x % 15 == 7: return 9  # antenna
    return 0  # sky

def static_pattern(rng, x, y, frame):
    """TV static / data noise."""
    seed = x * 997 + y * 31 + frame * 127
    v = ((seed * 1103515245 + 12345) >> 16) & 0xF
    return v

def corruption_pattern(rng, x, y, frame):
    """Corruption spreading from center."""
    import math
    cx, cy = 120, 80
    dist = math.sqrt((x-cx)**2 + (y-cy)**2)
    threshold = frame * 1.2
    if dist < threshold:
        if dist > threshold - 3: return 14  # corruption edge
        if (x ^ y ^ frame) & 3 == 0: return 12
        return 8  # corrupted area
    if dist < threshold + 5 and rng.next() % 10 < 2: return 6  # sparks
    return 1

def matrix_pattern(rng, x, y, frame):
    """Digital rain / matrix effect."""
    col_speed = ((x * 37) & 0xFF) % 5 + 1
    offset = (frame * col_speed + x * 17) & 0xFF
    char_y = (y + offset) % 160
    if char_y % 12 < 8:
        brightness = max(0, 15 - (y * 15 // 160))
        if brightness > 0 and x % 8 >= 2 and x % 8 <= 6:
            return brightness
    return 0

PATTERNS = [circuit_pattern, wave_pattern, city_pattern, static_pattern, 
            corruption_pattern, matrix_pattern]

def generate_env_animations():
    """Generate environment animation frame data (60 frames × 6 patterns = 360 frames)."""
    lines = []
    lines.append("/*")
    lines.append(" * Ghost Protocol — Environment Animation Data")
    lines.append(" * Auto-generated by generate_extra_content.py")
    lines.append(" */")
    lines.append("#include <tonc.h>")
    lines.append("")
    
    rng = RNG(0x12345678)
    frame_count = 0
    
    for pat_idx, pattern_fn in enumerate(PATTERNS):
        pat_name = pattern_fn.__name__.replace("_pattern", "")
        for frame in range(60):
            arr_name = f"env_anim_{pat_name}_{frame:03d}"
            lines.append(f"const u32 {arr_name}[4800] __attribute__((used)) = {{")
            
            vals = []
            for row in range(20):  # 160/8 = 20 tile rows
                for col in range(30):  # 240/8 = 30 tile cols
                    tile = gen_tile_row(rng, pattern_fn, row, col, frame)
                    vals.extend(tile)
            
            # Write in lines of 10
            for i in range(0, len(vals), 10):
                chunk = vals[i:i+10]
                line = "    " + ", ".join(f"0x{v:08X}" for v in chunk) + ","
                lines.append(line)
            
            lines.append("};")
            lines.append("")
            frame_count += 1
    
    # Force link function
    lines.append("const void* env_anim_force_link(void) {")
    lines.append("    return (const void*)env_anim_circuit_000;")
    lines.append("}")
    lines.append("")
    
    print(f"  Generated {frame_count} environment animation frames")
    return "\n".join(lines)

def generate_tileset_variations():
    """Generate tileset theme variations (~2MB)."""
    lines = []
    lines.append("/*")
    lines.append(" * Ghost Protocol — Tileset Variations")  
    lines.append(" * 80 theme variations × 256 tiles each")
    lines.append(" * Auto-generated by generate_extra_content.py")
    lines.append(" */")
    lines.append("#include <tonc.h>")
    lines.append("")
    
    rng = RNG(0xCAFEBABE)
    
    # 80 themes × 256 tiles × 8 u32 per tile = 163,840 u32 values
    for theme in range(80):
        arr_name = f"tileset_theme_{theme:03d}"
        lines.append(f"const u32 {arr_name}[2048] __attribute__((used)) = {{")
        
        vals = []
        for tile in range(256):
            for row in range(8):
                v = 0
                for px in range(8):
                    # Deterministic pattern per theme/tile/row/pixel
                    seed = theme * 100003 + tile * 1009 + row * 31 + px
                    pix = ((seed * 2654435761) >> 28) & 0xF
                    # Apply theme-specific color mapping
                    if theme < 20:  # dark themes
                        pix = min(pix, 8)
                    elif theme < 40:  # bright themes
                        pix = max(pix, 4)
                    elif theme < 60:  # high contrast
                        pix = 0 if pix < 8 else 15
                    v |= (pix << (px * 4))
                vals.append(v)
        
        for i in range(0, len(vals), 10):
            chunk = vals[i:i+10]
            line = "    " + ", ".join(f"0x{v:08X}" for v in chunk) + ","
            lines.append(line)
        
        lines.append("};")
        lines.append("")
    
    lines.append("const void* tileset_force_link(void) {")
    lines.append("    return (const void*)tileset_theme_000;")
    lines.append("}")
    lines.append("")
    
    print(f"  Generated 80 tileset theme variations")
    return "\n".join(lines)

def generate_header():
    """Generate header for extra content."""
    return """#ifndef GAME_CONTENT_EXTRA_H
#define GAME_CONTENT_EXTRA_H

#include <tonc.h>

#define ENV_ANIM_PATTERN_COUNT 6
#define ENV_ANIM_FRAMES_PER   60
#define ENV_ANIM_TOTAL_FRAMES 360
#define TILESET_THEME_COUNT   80
#define TILESET_TILES_PER     256

const void* env_anim_force_link(void);
const void* tileset_force_link(void);

static inline void content_extra_force_link_all(void) {
    volatile const void* p;
    p = env_anim_force_link();
    p = tileset_force_link();
    (void)p;
}

#endif /* GAME_CONTENT_EXTRA_H */
"""

def main():
    print("Generating extra ROM content...")
    
    print("Generating tileset variations...")
    tileset_data = generate_tileset_variations()
    write_file(os.path.join(OUT_DIR, "content_tilesets.c"), tileset_data)
    
    print("Generating environment animations...")
    env_data = generate_env_animations()
    write_file(os.path.join(OUT_DIR, "content_env_anim.c"), env_data)
    
    print("Generating header...")
    header = generate_header()
    write_file(os.path.join(INC_DIR, "content_extra.h"), header)
    
    print("Done!")

if __name__ == "__main__":
    main()
