#!/usr/bin/env python3
"""Ghost Protocol Audio Generator v4.

SFX  — generated by sox with echo/overdrive/Hann-fade effects.
Music — MOD tracker: 2-channel sine-wave only (melody + bass, no drums).

Root cause of previous "static/garbage": Python-synthesised oscillators at
16 kHz 8-bit produce bleepy artifacts.  sox handles anti-aliasing, proper
dithering, and real effects chains.  Removing percussion eliminates the
click/burst noise from poorly-synthesised drum samples.

File naming MUST match audio.c sfx_map / music_map:
  SFX:   01_shoot.wav .. 30_achievement.wav   (30 files)
  Music: 00_title.mod .. 15_evolution.mod     (16 files)
"""

import math, os, struct, subprocess

MUSIC_DIR = "audio/music"
SFX_DIR   = "audio/sfx"

MOD_ROWS = 64
MOD_CHAN = 4

# Standard Amiga period table (3 octaves).
# GBA Maxmod mixes at ~16 kHz.  Safe period: clock/period < mix_rate  →  period ≥ 219.
# Oct 2 (periods 226-428) all have step_size < 1.0 at 16 kHz — safe.
# Oct 3 (periods 113-214) have step_size > 1.0 — alias into garbage on GBA hardware.
# clock / (period * 32) = tone_freq_Hz
# Period 856 (C1)  → 131 Hz bass  |  Period 428 (C2/C3) → 261 Hz lead  |  Period 226 (B2/B3) → 494 Hz
PERIODS = [
    856,808,762,720,678,640,604,570,538,508,480,453,   # Oct 1
    428,404,381,360,339,320,302,285,269,254,240,226,   # Oct 2
    214,202,190,180,170,160,151,143,135,127,120,113,   # Oct 3 (unsafe on GBA — do not use)
]
C1,Cs1,D1,Ds1,E1,F1,Fs1,G1,Gs1,A1,As1,B1 = range(12)
C2,Cs2,D2,Ds2,E2,F2,Fs2,G2,Gs2,A2,As2,B2 = range(12, 24)
# C3-B3 map to Oct 2 periods — GBA 16 kHz mixer cannot play Oct 3 without aliasing.
C3,Cs3,D3,Ds3,E3,F3,Fs3,G3,Gs3,A3,As3,B3 = range(12, 24)
REST = -1

VC = 0x0C   # volume effect command


# ── SFX via sox ──────────────────────────────────────────────────────────────

def sox_wav(outpath, *args):
    """Run sox to generate a 16384 Hz / 8-bit unsigned / mono WAV."""
    cmd = ['sox', '-n',
           '-r', '16384', '-b', '8', '-e', 'unsigned-integer', '-c', '1',
           outpath] + [str(a) for a in args]
    subprocess.run(cmd, check=True, capture_output=True)


def make_sfx():
    d = SFX_DIR

    # 01 — laser fire: descending chirp + echo tail
    sox_wav(f'{d}/01_shoot.wav',
        'synth','0.13','sine','1000:250',
        'echo','0.6','0.4','50','0.5',
        'fade','h','0','0.23','0.05', 'gain','-3')

    # 02 — charge shot: rising whine
    sox_wav(f'{d}/02_shoot_charge.wav',
        'synth','0.45','sine','280:1350',
        'echo','0.5','0.3','80','0.4',
        'fade','h','0.03','0.52','0.05', 'gain','-3')

    # 03 — rapid fire: short blip
    sox_wav(f'{d}/03_shoot_rapid.wav',
        'synth','0.07','sine','1100:600',
        'fade','h','0','0.07','0.015', 'gain','-3')

    # 04 — enemy hit: thud (overdrive adds harmonics → less pure "beep")
    sox_wav(f'{d}/04_enemy_hit.wav',
        'synth','0.10','sine','450:90',
        'overdrive','12','15',
        'fade','h','0','0.10','0.04', 'gain','-5')

    # 05 — enemy die: descending + echo
    sox_wav(f'{d}/05_enemy_die.wav',
        'synth','0.28','sine','580:50',
        'echo','0.5','0.4','70','0.4',
        'fade','h','0','0.36','0.08', 'gain','-3')

    # 06 — player hit: heavy low impact
    sox_wav(f'{d}/06_player_hit.wav',
        'synth','0.15','sine','160:55',
        'overdrive','18','22',
        'fade','h','0','0.15','0.05', 'gain','-3')

    # 07 — player die: long falling sweep + echo
    sox_wav(f'{d}/07_player_die.wav',
        'synth','0.55','sine','320:28',
        'echo','0.5','0.4','120','0.5',
        'fade','h','0','0.65','0.10', 'gain','-3')

    # 08 — jump: quick upward chirp
    sox_wav(f'{d}/08_jump.wav',
        'synth','0.09','sine','180:520',
        'fade','h','0','0.09','0.02', 'gain','-6')

    # 09 — wall jump: slightly higher
    sox_wav(f'{d}/09_wall_jump.wav',
        'synth','0.09','sine','260:680',
        'fade','h','0','0.09','0.02', 'gain','-6')

    # 10 — dash: whoosh downward
    sox_wav(f'{d}/10_dash.wav',
        'synth','0.12','sine','800:200',
        'fade','h','0','0.12','0.03', 'gain','-3')

    # 11 — item pickup: bright chime + echo
    sox_wav(f'{d}/11_pickup.wav',
        'synth','0.22','sine','880',
        'echo','0.5','0.4','65','0.3',
        'fade','h','0.01','0.30','0.10', 'gain','-3')

    # 12 — menu select: clean tone
    sox_wav(f'{d}/12_menu_select.wav',
        'synth','0.08','sine','880',
        'fade','h','0','0.10','0.03', 'gain','-6')

    # 13 — menu back: lower tone
    sox_wav(f'{d}/13_menu_back.wav',
        'synth','0.08','sine','660',
        'fade','h','0','0.10','0.03', 'gain','-6')

    # 14 — ability: power chord sweep + echo
    sox_wav(f'{d}/14_ability.wav',
        'synth','0.30','sine','440:660',
        'echo','0.4','0.3','85','0.4',
        'fade','h','0.01','0.38','0.08', 'gain','-3')

    # 15 — boss roar: low rising rumble + long echo
    sox_wav(f'{d}/15_boss_roar.wav',
        'synth','0.50','sine','75:180',
        'echo','0.5','0.4','140','0.5',
        'fade','h','0.04','0.60','0.10', 'gain','-3')

    # 16 — level done: ascending sweep + echo
    sox_wav(f'{d}/16_level_done.wav',
        'synth','0.40','sine','523:1047',
        'echo','0.4','0.3','75','0.4',
        'fade','h','0.01','0.50','0.10', 'gain','-3')

    # 17 — save: gentle confirmation tone + echo
    sox_wav(f'{d}/17_save.wav',
        'synth','0.20','sine','440',
        'echo','0.4','0.3','55','0.3',
        'fade','h','0','0.28','0.08', 'gain','-6')

    # 18 — transition: mid sweep + echo
    sox_wav(f'{d}/18_transition.wav',
        'synth','0.30','sine','280:580',
        'echo','0.4','0.3','75','0.4',
        'fade','h','0.02','0.38','0.08', 'gain','-3')

    # 19 — wall slide: slight detuning creates gentle beating
    sox_wav(f'{d}/19_wall_slide.wav',
        'synth','0.15','sine','158:162',
        'fade','h','0.02','0.15','0.04', 'gain','-6')

    # 20 — heavy land: deep thud with overdrive
    sox_wav(f'{d}/20_land_heavy.wav',
        'synth','0.14','sine','90:35',
        'overdrive','14','18',
        'fade','h','0','0.14','0.05', 'gain','-3')

    # 21 — double jump: two-note feel via fast sweep
    sox_wav(f'{d}/21_double_jump.wav',
        'synth','0.12','sine','240:630',
        'fade','h','0','0.12','0.02', 'gain','-6')

    # 22 — beam hum: sustained with very slow beating + echo
    sox_wav(f'{d}/22_beam_hum.wav',
        'synth','0.35','sine','220:226',
        'echo','0.5','0.4','55','0.5',
        'fade','h','0.04','0.40','0.07', 'gain','-3')

    # 23 — spread burst: rising burst + short echo
    sox_wav(f'{d}/23_spread_burst.wav',
        'synth','0.12','sine','580:880',
        'echo','0.4','0.3','35','0.4',
        'fade','h','0','0.18','0.04', 'gain','-3')

    # 24 — charger whine: long rising tone
    sox_wav(f'{d}/24_charger_whine.wav',
        'synth','0.40','sine','300:1200',
        'fade','h','0.03','0.40','0.05', 'gain','-3')

    # 25 — boss phase: dramatic sweep + long echo
    sox_wav(f'{d}/25_boss_phase.wav',
        'synth','0.50','sine','140:380',
        'echo','0.5','0.4','115','0.5',
        'fade','h','0.01','0.60','0.10', 'gain','-3')

    # 26 — boss explode: overdrive low sweep + echo
    sox_wav(f'{d}/26_boss_explode.wav',
        'synth','0.50','sine','55:190',
        'overdrive','22','28',
        'echo','0.5','0.4','95','0.5',
        'fade','h','0','0.60','0.10', 'gain','-3')

    # 27 — tesla zap: high-freq burst with overdrive
    sox_wav(f'{d}/27_tesla_zap.wav',
        'synth','0.09','sine','1350:750',
        'overdrive','14','18',
        'fade','h','0','0.09','0.025', 'gain','-3')

    # 28 — craft success: rising sweep + echo
    sox_wav(f'{d}/28_craft_success.wav',
        'synth','0.35','sine','392:784',
        'echo','0.4','0.3','65','0.4',
        'fade','h','0.01','0.43','0.10', 'gain','-3')

    # 29 — evolve: wide triumphant sweep + echo
    sox_wav(f'{d}/29_evolve.wav',
        'synth','0.60','sine','196:784',
        'echo','0.4','0.3','95','0.4',
        'fade','h','0.02','0.72','0.12', 'gain','-3')

    # 30 — achievement: bright ascending sweep + echo
    sox_wav(f'{d}/30_achievement.wav',
        'synth','0.40','sine','523:1047',
        'echo','0.4','0.3','75','0.5',
        'fade','h','0.01','0.50','0.12', 'gain','-3')

    # 31 — beam fire: sustained low hum with overtones
    sox_wav(f'{d}/31_beam_fire.wav',
        'synth','0.30','sine','180:200',
        'echo','0.6','0.5','40','0.5',
        'fade','h','0.02','0.35','0.05', 'gain','-4')

    # 32 — laser crack: sharp high-freq snap
    sox_wav(f'{d}/32_laser_crack.wav',
        'synth','0.06','sine','2000:800',
        'overdrive','10','12',
        'fade','h','0','0.06','0.01', 'gain','-3')

    # 33 — nova whoosh: expanding low sweep outward
    sox_wav(f'{d}/33_nova_whoosh.wav',
        'synth','0.25','sine','120:450',
        'echo','0.5','0.4','60','0.4',
        'fade','h','0.01','0.30','0.06', 'gain','-3')

    # 34 — homing whine: rising engine whistle
    sox_wav(f'{d}/34_homing_whine.wav',
        'synth','0.20','sine','400:900',
        'fade','h','0.02','0.20','0.04', 'gain','-5')

    # 35 — mechanical enemy hit: metallic clank
    sox_wav(f'{d}/35_enemy_hit_mech.wav',
        'synth','0.08','sine','800:200',
        'overdrive','20','25',
        'fade','h','0','0.08','0.02', 'gain','-4')

    # 36 — mechanical enemy die: grinding halt
    sox_wav(f'{d}/36_enemy_die_mech.wav',
        'synth','0.30','sine','400:40',
        'overdrive','15','20',
        'echo','0.4','0.3','50','0.4',
        'fade','h','0','0.38','0.08', 'gain','-3')

    # 37 — digital enemy hit: glitch stutter
    sox_wav(f'{d}/37_enemy_hit_digi.wav',
        'synth','0.06','sine','1200:400',
        'echo','0.3','0.2','15','0.3',
        'fade','h','0','0.08','0.02', 'gain','-4')

    # 38 — digital enemy die: data dissolution
    sox_wav(f'{d}/38_enemy_die_digi.wav',
        'synth','0.25','sine','900:100',
        'echo','0.5','0.4','30','0.5',
        'fade','h','0','0.32','0.07', 'gain','-3')


# ── MOD tracker music ────────────────────────────────────────────────────────
# 2 channels only: ch0 = melody (smp 1), ch1 = bass (smp 2).
# Both use the same 32-sample looping sine wave.
# No drums — drum synthesis sounds like static on GBA hardware.

def sine32():
    """32-sample looping sine wave, 8-bit signed PCM."""
    return bytes((int(118 * math.sin(2 * math.pi * i / 32)) & 0xFF)
                 for i in range(32))


def smp_hdr(name, data, vol=56):
    words = len(data) // 2
    return struct.pack('>22sHBBHH',
                       name.encode()[:22].ljust(22, b'\0'),
                       words, 0, vol, 0, words)  # loop_start=0, loop_len=words


def note_cell(note_idx, smp, effect=0, param=0):
    period = PERIODS[note_idx] if 0 <= note_idx < len(PERIODS) else 0
    b1 = ((smp >> 4) << 4) | ((period >> 8) & 0xF)
    b2 = period & 0xFF
    b3 = ((smp & 0xF) << 4) | (effect & 0xF)
    b4 = param & 0xFF
    return bytes([b1, b2, b3, b4])


def build_pattern(cells):
    """cells: [(row, ch, note_idx, smp, effect, param), ...]"""
    pat = bytearray(MOD_ROWS * MOD_CHAN * 4)
    for row, ch, note, smp, fx, param in cells:
        if 0 <= row < MOD_ROWS and 0 <= ch < MOD_CHAN:
            off = (row * MOD_CHAN + ch) * 4
            pat[off:off+4] = note_cell(note, smp, fx, param)
    return bytes(pat)


def build_mod(title, patterns, order, speed=6, bpm=90):
    """Assemble a 2-instrument MOD file (both use the same 32-byte sine)."""
    sd = sine32()
    title_b = title.encode()[:20].ljust(20, b'\0')
    hdrs  = smp_hdr('Melody', sd, 56)
    hdrs += smp_hdr('Bass',   sd, 48)
    for _ in range(29):
        hdrs += struct.pack('>22sHBBHH', b'\0'*22, 0, 0, 0, 0, 0)

    # Inject BPM+speed into row 0 channels 0/1 of first pattern
    if patterns:
        p0 = bytearray(patterns[0])
        p0[0]=0x00; p0[1]=0x00; p0[2]=0x0F; p0[3]=bpm & 0xFF
        p0[4]=0x00; p0[5]=0x00; p0[6]=0x0F; p0[7]=speed & 0x1F
        patterns[0] = bytes(p0)

    n_pat = max(order) + 1 if order else 1
    mod   = title_b + hdrs
    mod  += struct.pack('BB', len(order), 0)
    mod  += bytes(order + [0] * (128 - len(order)))
    mod  += b'M.K.'
    for i in range(n_pat):
        mod += patterns[i] if i < len(patterns) else bytes(MOD_ROWS * MOD_CHAN * 4)
    mod += sd + sd   # sample data for instrument 1 and 2
    return mod


def note(row, ch, n, smp, vol=48):
    """Convenience: returns a pattern cell tuple."""
    return (row, ch, n, smp, VC, vol)


S = 1   # melody instrument number
B = 2   # bass instrument number

# ─── Track builders ───────────────────────────────────────────────────────────
# Melody rows start at 4 (row 0 is reserved for BPM injection).
# Notes every 4 rows at speed=6, bpm=90 → ~1.8 notes/sec (moderate pace).

def _track(title, mel, bass, bpm=90, speed=6, loops=4):
    cells = []
    for row, n, vol in mel:
        if row > 0:
            cells.append(note(row, 0, n, S, vol))
    for row, n, vol in bass:
        if row > 0:
            cells.append(note(row, 1, n, B, vol))
    p = build_pattern(cells)
    return build_mod(title, [p], [0] * loops, speed, bpm)


def track_title():
    # C minor, slow atmospheric
    mel = [(4,C3,52),(8,Ds3,48),(12,G3,52),(16,As3,50),(20,G3,48),
           (24,Ds3,46),(28,C3,50),(32,As2,46),(36,G2,44),(40,As2,46),
           (44,C3,50),(48,Ds3,52),(52,F3,50),(56,G3,52),(60,As3,54)]
    bass= [(4,C1,40),(20,As1,38),(36,G1,38),(52,F1,38)]
    return _track('Ghost Protocol', mel, bass, bpm=75, speed=7, loops=4)


def track_terminal():
    # D dorian, mysterious
    mel = [(4,D3,50),(8,F3,46),(12,A3,50),(16,C3,48),(20,A3,46),
           (24,G3,44),(28,F3,46),(32,E3,48),(36,D3,50),(40,E3,46),
           (44,F3,50),(48,A3,52),(52,G3,50),(56,F3,48),(60,E3,46)]
    bass= [(4,D1,38),(20,A1,36),(36,G1,36),(52,F1,36)]
    return _track('Terminal', mel, bass, bpm=70, speed=7, loops=4)


def track_act1():
    # E natural minor, moderate
    mel = [(4,E3,52),(8,G3,48),(12,B3,52),(16,D3,50),(20,B2,48),
           (24,A2,46),(28,G2,48),(32,Fs2,50),(36,E3,52),(40,Fs3,50),
           (44,G3,52),(48,A3,54),(52,B3,56),(56,D3,54),(60,E3,56)]
    bass= [(4,E1,40),(20,A1,38),(36,G1,38),(52,B1,40)]
    return _track('Act I', mel, bass, bpm=100, speed=6, loops=4)


def track_act2():
    # G minor, urban
    mel = [(4,G3,52),(8,As3,48),(12,D3,52),(16,F3,50),(20,D3,48),
           (24,C3,46),(28,As2,48),(32,A2,46),(36,G3,52),(40,F3,50),
           (44,G3,52),(48,As3,54),(52,C3,52),(56,D3,54),(60,F3,52)]
    bass= [(4,G1,40),(20,D2,38),(36,C2,38),(52,As1,38)]
    return _track('Act II', mel, bass, bpm=105, speed=6, loops=4)


def track_act3():
    # A minor, tense
    mel = [(4,A3,54),(8,C3,50),(12,E3,54),(16,G3,52),(20,E3,50),
           (24,D3,48),(28,C3,50),(32,B2,48),(36,A3,54),(40,B2,50),
           (44,C3,54),(48,E3,56),(52,G3,54),(56,F3,52),(60,E3,54)]
    bass= [(4,A1,40),(20,E2,38),(36,D2,38),(52,C2,38)]
    return _track('Act III', mel, bass, bpm=110, speed=6, loops=4)


def track_act4():
    # D minor, driving
    mel = [(4,D3,54),(6,F3,50),(8,A3,54),(10,C3,52),(12,A3,50),
           (14,G3,50),(16,F3,52),(18,E3,50),(20,D3,54),(22,C3,50),
           (24,D3,56),(26,F3,52),(28,A3,56),(30,C3,54),(32,As2,52),
           (36,A2,50),(40,G2,52),(44,F2,50),(48,D3,56),(52,F3,54),
           (56,A3,58),(60,C3,56)]
    bass= [(4,D1,42),(20,G1,40),(36,F1,40),(52,C2,40)]
    return _track('Act IV', mel, bass, bpm=118, speed=5, loops=4)


def track_act5():
    # F minor, dark
    mel = [(4,F3,52),(8,Gs3,48),(12,C3,52),(16,Ds3,50),(20,C3,48),
           (24,As2,46),(28,Gs2,48),(32,G2,46),(36,F3,52),(40,G2,48),
           (44,Gs2,52),(48,As2,52),(52,C3,54),(56,Ds3,52),(60,F3,54)]
    bass= [(4,F1,40),(20,C2,38),(36,As1,38),(52,Gs1,38)]
    return _track('Act V', mel, bass, bpm=108, speed=6, loops=4)


def track_act6():
    # B minor, intense chromatic
    mel = [(4,B3,56),(6,Cs3,52),(8,D3,56),(10,E3,58),(12,Fs3,56),
           (14,E3,52),(16,D3,56),(18,Cs3,52),(20,B3,58),(22,A3,54),
           (24,B3,56),(26,Cs3,52),(28,D3,58),(30,E3,60),(32,Fs3,60),
           (36,G3,58),(40,Fs3,56),(44,E3,54),(48,D3,56),(52,Cs3,54),
           (56,B3,58),(60,A3,56)]
    bass= [(4,B1,42),(20,A1,40),(36,G1,40),(52,Fs1,40)]
    return _track('Act VI', mel, bass, bpm=120, speed=5, loops=4)


def _boss(title, mel, bass, bpm=130):
    cells = []
    for row, n, vol in mel:
        if row > 0:
            cells.append(note(row, 0, n, S, vol))
    for row, n, vol in bass:
        if row > 0:
            cells.append(note(row, 1, n, B, vol))
    p = build_pattern(cells)
    return build_mod(title, [p], [0]*6, speed=4, bpm=bpm)


def track_boss_corp():
    # C phrygian, aggressive
    mel = [(4,C3,58),(6,Cs3,54),(8,Ds3,58),(10,F3,62),(12,G3,60),
           (14,F3,56),(16,Ds3,58),(18,Cs3,54),(20,C3,60),(22,As2,56),
           (24,C3,62),(26,Cs3,58),(28,Ds3,62),(30,F3,64),(32,G3,66),
           (34,As2,62),(36,G3,60),(38,F3,58),(40,Ds3,60),(44,Cs3,56),
           (48,C3,62),(52,Ds3,60),(56,G3,64),(60,As2,62)]
    bass= [(4,C1,46),(16,As1,44),(32,G1,44),(48,F1,44)]
    return _boss('Boss Corp', mel, bass, 132)


def track_boss_gate():
    # E minor, intense
    mel = [(4,E3,60),(6,Fs3,56),(8,G3,60),(10,A3,64),(12,B3,62),
           (14,A3,58),(16,G3,60),(18,Fs3,56),(20,E3,62),(22,D3,58),
           (24,E3,62),(26,Fs3,58),(28,G3,62),(30,A3,64),(32,B3,66),
           (34,C3,64),(36,B3,62),(38,A3,60),(40,G3,62),(44,Fs3,58),
           (48,E3,64),(52,G3,62),(56,B3,66),(60,A3,64)]
    bass= [(4,E1,46),(16,D2,44),(32,C2,44),(48,B1,46)]
    return _boss('Boss Gate', mel, bass, 138)


def track_boss_daemon():
    # Chromatic, chaotic
    mel = [(4,A3,62),(6,As3,60),(8,B3,62),(10,C3,64),(12,Cs3,60),
           (14,D3,64),(16,Ds3,62),(18,E3,60),(20,F3,62),(22,Fs3,64),
           (24,G3,62),(26,Gs3,60),(28,A3,64),(30,As3,62),(32,B3,66),
           (34,C3,64),(36,B3,62),(38,As3,60),(40,A3,64),(44,Gs3,60),
           (48,G3,62),(52,Fs3,60),(56,F3,64),(60,E3,62)]
    bass= [(4,A1,48),(16,D2,46),(32,G1,46),(48,Ds1,46)]
    return _boss('Boss DAEMON', mel, bass, 142)


def track_miniboss():
    # G minor, driving
    mel = [(4,G3,56),(6,A3,52),(8,As3,56),(10,C3,60),(12,D3,58),
           (14,C3,54),(16,As2,56),(18,A2,52),(20,G3,58),(22,F3,54),
           (24,G3,60),(26,A3,56),(28,As3,60),(30,C3,62),(32,D3,64),
           (36,Ds3,62),(40,D3,60),(44,C3,58),(48,As2,60),(52,A2,58),
           (56,G3,62),(60,F3,60)]
    bass= [(4,G1,44),(16,F2,42),(32,D2,42),(48,C2,42)]
    return _boss('Mini Boss', mel, bass, 128)


def track_victory():
    # C major, triumphant
    mel = [(4,C3,56),(8,E3,52),(12,G3,56),(16,C3,60),(20,G2,54),
           (24,E2,50),(28,G2,54),(32,C3,58),(36,F3,54),(40,A3,58),
           (44,G3,56),(48,E3,54),(52,C3,58),(56,G2,54),(60,C3,60)]
    bass= [(4,C1,44),(20,G1,42),(36,F1,42),(52,G1,42)]
    cells = [note(r, 0, n, S, v) for r,n,v in mel if r>0]
    cells += [note(r, 1, n, B, v) for r,n,v in bass if r>0]
    p = build_pattern(cells)
    return build_mod('Victory', [p], [0,0], speed=5, bpm=112)


def track_gameover():
    # D minor, mournful descent
    mel = [(4,D3,50),(10,C3,46),(16,As2,44),(22,A2,46),
           (28,G2,42),(34,F2,40),(40,E2,42),(46,D2,46),
           (52,C2,42),(58,As1,40)]
    bass= [(4,D1,38),(28,G1,36),(52,C1,36)]
    cells = [note(r, 0, n, S, v) for r,n,v in mel if r>0]
    cells += [note(r, 1, n, B, v) for r,n,v in bass if r>0]
    p = build_pattern(cells)
    return build_mod('Game Over', [p], [0,0,0], speed=8, bpm=62)


def track_credits():
    # A major, reflective
    mel = [(4,A3,50),(8,Cs3,46),(12,E3,50),(16,A3,54),(20,G3,50),
           (24,E3,46),(28,Cs3,50),(32,A2,48),(36,D3,50),(40,E3,48),
           (44,Fs3,52),(48,A3,54),(52,G3,52),(56,E3,50),(60,Cs3,50)]
    bass= [(4,A1,38),(20,E2,36),(36,D2,36),(52,A1,38)]
    cells = [note(r, 0, n, S, v) for r,n,v in mel if r>0]
    cells += [note(r, 1, n, B, v) for r,n,v in bass if r>0]
    p0 = build_pattern(cells)
    mel2= [(4,Cs3,50),(8,E3,48),(12,Fs3,52),(16,A3,54),(20,G3,50),
           (24,Fs3,46),(28,E3,50),(32,Cs3,50),(36,D3,48),(40,E3,50),
           (44,Fs3,52),(48,A3,54),(52,G3,52),(56,Fs3,50),(60,E3,50)]
    cells2 = [note(r, 0, n, S, v) for r,n,v in mel2 if r>0]
    cells2 += [note(r, 1, n, B, v) for r,n,v in bass if r>0]
    p1 = build_pattern(cells2)
    return build_mod('Credits', [p0, p1], [0,1,0,1,0], speed=6, bpm=85)


def track_evolution():
    # E major, epic
    mel = [(4,E3,60),(8,Gs3,56),(12,B3,60),(16,E3,64),
           (20,B2,56),(24,Gs2,54),(28,B2,58),(32,E3,62),
           (36,Gs3,64),(40,B3,66),(44,E3,68),(48,Gs3,66),
           (52,B3,68),(56,E3,72),(60,Gs3,68)]
    bass= [(4,E1,48),(20,B1,46),(36,Gs1,46),(52,E1,48)]
    cells = [note(r, 0, n, S, v) for r,n,v in mel if r>0]
    cells += [note(r, 1, n, B, v) for r,n,v in bass if r>0]
    p = build_pattern(cells)
    return build_mod('Evolution', [p, p], [0, 0], speed=4, bpm=115)


MUSIC_TRACKS = {
    '00_title.mod':       track_title,
    '01_terminal.mod':    track_terminal,
    '02_act1.mod':        track_act1,
    '03_act2.mod':        track_act2,
    '04_act3.mod':        track_act3,
    '05_act4.mod':        track_act4,
    '06_act5.mod':        track_act5,
    '07_act6.mod':        track_act6,
    '08_boss_corp.mod':   track_boss_corp,
    '09_boss_gate.mod':   track_boss_gate,
    '10_boss_daemon.mod': track_boss_daemon,
    '11_miniboss.mod':    track_miniboss,
    '12_victory.mod':     track_victory,
    '13_gameover.mod':    track_gameover,
    '14_credits.mod':     track_credits,
    '15_evolution.mod':   track_evolution,
}


def main():
    os.makedirs(MUSIC_DIR, exist_ok=True)
    os.makedirs(SFX_DIR,   exist_ok=True)

    print('Generating SFX via sox...')
    make_sfx()
    for f in sorted(os.listdir(SFX_DIR)):
        if f.endswith('.wav'):
            sz = os.path.getsize(os.path.join(SFX_DIR, f))
            print(f'  SFX  {f} ({sz} bytes)')

    print('Generating MOD music...')
    for fname, fn in sorted(MUSIC_TRACKS.items()):
        data = fn()
        path = os.path.join(MUSIC_DIR, fname)
        with open(path, 'wb') as fh:
            fh.write(data)
        print(f'  MOD  {fname} ({len(data)} bytes)')

    print(f'\n30 SFX + {len(MUSIC_TRACKS)} MOD tracks generated.')


if __name__ == '__main__':
    main()
